Repository Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2, pull requests merged in 2020-12, with the labels that each got.

#32 Court chaplain title
  common/council_positions/00_council_positions.txt
  common/customizable_localization/00_divinity_custom_loc.txt
  localization/english/wc_council_l_english.yml
Labels: :exclamation: priority high, :page_facing_up: localisation :pen:

#53 the Hakkari are now considered evil by every order and life faction
  common/religion/doctrines/00_core_tenets.txt
  common/religion/doctrines/wc_doctrines_religions.txt
  common/religion/religions/loa_group.txt
  common/trigger_localization/wc_doctrine_triggers.txt
  localization/english/religion/wc_core_tenets_l_english.yml
Labels: :balance_scale: balance :balance_scale:, :books: lore :books:, :exclamation: priority high

#57 Vanilla (Not Really) Localization
  localization/english/gui/wc_succession_event_window_l_english.yml
  localization/english/religion/wc_gods_and_titles_l_english.yml
  localization/english/wc_general_l_english.yml
  localization/german/gui/wc_succession_event_window_l_german.yml
  localization/german/religion/wc_gods_and_titles_l_german.yml
  localization/german/wc_general_l_german.yml
  localization/replace/english/wc_replacements_l_english.yml
  localization/replace/german/wc_replacements_l_german.yml
Labels: :exclamation: priority critical, :page_facing_up: localisation :pen:

#68 Vanilla MaAs
  common/culture/innovations/00_cultural_maa_innovations.txt
  common/men_at_arms_types/00_cultural_maa_types.txt
  common/men_at_arms_types/00_regional_maa_types.txt
  common/script_values/00_men_at_arms_values.txt
Labels: :hammer: maintenance :wrench:, :ice_cream: vanilla modification :icecream:

#71 Daradorism Religion
  common/religion/doctrines/wc_doctrines_religions.txt
  common/religion/religions/daradorism.txt
  common/religion/religions/druidism_group.txt
  common/scripted_triggers/wc_religious_triggers.txt
  localization/english/religion/wc_religion_l_english.yml
Labels: :balance_scale: balance :balance_scale:, :books: lore :books:, :exclamation: priority high, :page_facing_up: localisation :pen:

#73 New Highborne Ethnicity
  common/ethnicities/wc_ethnicities_elven.txt
Labels: :art: graphics :paintbrush:, :exclamation: priority high

#74 Blending Dwarves
  common/culture/cultures/dwarf.txt
  common/culture/cultures/gnome.txt
  common/ethnicities/00_ethnicities_templates.txt
  common/ethnicities/01_ethnicities_caucasian.txt
  common/ethnicities/wc_ethnicities_dwarven.txt
  common/ethnicities/wc_ethnicities_elven.txt
  common/genes/03_genes_accessories_beards.txt
  common/genes/wc_genes_accessories_eyebrows.txt
  common/scripted_modifiers/wc_portrait_modifiers.txt
  common/scripted_triggers/wc_portrait_triggers.txt
  common/scripted_triggers/wc_race_triggers.txt
  common/traits/wc_race_traits.txt
  gfx/models/portraits/attachments/male_eyebrows/hair00_00_hd.dds
  gfx/models/portraits/attachments/male_eyebrows/male_dwarven_eyebrows_0.mesh
  gfx/models/portraits/attachments/male_eyebrows/male_elven_eyebrows_0.asset
  gfx/portraits/accessories/wc_eyebrows.txt
  gfx/portraits/eye_palette.dds
  gfx/portraits/hair_palette.dds
  gfx/portraits/portrait_modifiers/01_animation_expressions.txt
  gfx/portraits/portrait_modifiers/01_event_hair.txt
  gfx/portraits/portrait_modifiers/wc_custom_eyebrows.txt
  gfx/portraits/skin_palette.dds
  gfx/portraits/trait_portrait_modifiers/00_trait_modifiers.txt
  localization/english/wc_portraits_l_english.yml
Labels: :art: graphics :paintbrush:, :books: lore :books:, :grey_exclamation: priority medium, :star: new feature :new:
