Repository Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2, pull requests merged in 2020-11, with the labels that each got.

#26 Missed Adaptation
  history/characters/100000_vrykul.txt
  history/characters/10000_orc.txt
  history/characters/11000_dark_iron.txt
  history/characters/140000_satyr.txt
  history/characters/15000_gurubashi.txt
  history/characters/160000_quilboar.txt
  history/characters/16000_gnome.txt
  history/characters/170000_tuskarr.txt
  history/characters/17000_28000_bronzebeard.txt
  history/characters/180000_magnataur.txt
  history/characters/190000_taunka.txt
  history/characters/1_azerothian.txt
  history/characters/200000_farraki.txt
  history/characters/210000_tauren.txt
  history/characters/220000_dark_troll.txt
  history/characters/230000_hozen.txt
  history/characters/250000_harpy.txt
  history/characters/260000_northern.txt
  history/characters/270000_tolvir.txt
  history/characters/280000_pygmy.txt
  history/characters/29000_gnoll.txt
  history/characters/310000_patron_characters.txt
  history/characters/320000_centaur.txt
  history/characters/32000_frostmane.txt
  history/characters/34000_murloc.txt
  history/characters/42000_high_elf.txt
  history/characters/48000_tirassian.txt
  history/characters/500000_pandaren.txt
  history/characters/50000_kobold.txt
  history/characters/510000_jinyu.txt
  history/characters/520000_mogu.txt
  history/characters/530000_saurok.txt
  history/characters/53000_hillsbrad.txt
  history/characters/540000_mantid.txt
  history/characters/550000_yaungol.txt
  history/characters/560000_grummle.txt
  history/characters/60000_63000_lordaeronian.txt
  history/characters/6000_gurubashi.txt
  history/characters/64000_goblin.txt
  history/characters/66000_zandalari.txt
  history/characters/68000_darkspear.txt
  history/characters/76000_nerubian.txt
  history/characters/77000_wolvar.txt
  history/characters/78000_gorloc.txt
  history/characters/79000_130000_furbolg.txt
  history/characters/80000_drakkari.txt
  history/characters/90000_pirate.txt
Labels: :exclamation: priority critical, :hammer: maintenance :wrench:, :wrench: bug fix :hammer:

#28 1st New Religions
  common/religion/religions/druidism_group.txt
  common/religion/religions/light_group.txt
  history/characters/11000_dark_iron.txt
  history/characters/16000_gnome.txt
  history/characters/17000_28000_bronzebeard.txt
  history/characters/22000_wildhammer.txt
  history/characters/260000_northern.txt
  history/characters/310000_patron_characters.txt
  history/characters/60000_63000_lordaeronian.txt
  history/characters/75000_old_dwarven.txt
  history/provinces/00_k_blackrock.txt
  history/provinces/00_k_dragonblight.txt
  history/provinces/00_k_frostmane.txt
  history/provinces/00_k_grizzly_hills.txt
  history/provinces/00_k_howling_fjord.txt
  history/provinces/00_k_ironforge.txt
  history/provinces/00_k_wetlands.txt
  localization/english/religion/wc_religion_l_english.yml
Labels: :exclamation: priority critical, :star: new feature :new:

#22 Religious Heads and Holy Sites
  common/dynasties/8000_troll.txt
  common/flavorization/wc_title_holders.txt
  common/landed_titles/wc_religious_titles.txt
  common/landed_titles/wc_titular_titles.txt
  common/nicknames/wc_nicknames.txt
  common/religion/holy_sites/01_holy_sites.txt
  common/religion/holy_sites/wc_holy_sites.txt
  common/religion/religions/air_group.txt
  common/religion/religions/ape_group.txt
  common/religion/religions/arcane_group.txt
  common/religion/religions/deathbringer.txt
  common/religion/religions/doombringer.txt
  common/religion/religions/druidism_group.txt
  common/religion/religions/earth_group.txt
  common/religion/religions/fel_group.txt
  common/religion/religions/fire_group.txt
  common/religion/religions/grond_group.txt
  common/religion/religions/light_group.txt
  common/religion/religions/lizard_group.txt
  common/religion/religions/loa_group.txt
  common/religion/religions/naarism.txt
  common/religion/religions/necromancy_group.txt
  common/religion/religions/nerub_group.txt
  common/religion/religions/pandaren_religion_group.txt
  common/religion/religions/secular_group.txt
  common/religion/religions/shamanism_group.txt
  common/religion/religions/shathgral_group.txt
  common/religion/religions/titanic_group.txt
  common/religion/religions/void_group.txt
  common/religion/religions/water_group.txt
  history/characters/150000_naga.txt
  history/characters/15000_gurubashi.txt
  history/characters/200000_farraki.txt
  history/characters/57000_amani.txt
  history/characters/60000_63000_lordaeronian.txt
  history/characters/66000_zandalari.txt
  history/characters/80000_drakkari.txt
  history/titles/00_wc_other_titles.txt
  history/titles/00_wc_religious_head_titles.txt
  history/titles/k_voldun.txt
  localization/english/culture/wc_culture_titles_l_english.yml
  localization/english/names/wc_character_names_l_english.yml
  localization/english/religion/wc_gods_and_titles_l_english.yml
  localization/english/religion/wc_holy_sites_l_english.yml
  localization/english/wc_modifiers_l_english.yml
  localization/english/wc_nicknames_l_english.yml
  localization/english/wc_other_titles_l_english.yml
  localization/replace/english/wc_replacements_l_english.yml
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority high, :star: new feature :new:

#34 1st Tenet Icons
  common/religion/doctrines/00_core_tenets.txt
  gfx/interface/icons/faith_doctrines/wc_core_tenet_bow.dds
  gfx/interface/icons/faith_doctrines/wc_core_tenet_flexing_muscles.dds
Labels: :art: graphics :paintbrush:, :exclamation: priority critical

#31 Added knight titles
  common/customizable_localization/00_knight_culture.txt
  common/scripted_triggers/wc_localization_triggers.txt
  localization/english/wc_custom_titles_l_english.yml
  localization/english/wc_knight_titles_l_english.yml
Labels: :exclamation: priority high, :page_facing_up: localisation :pen:

#47 Gender equal zandalari
  common/religion/religions/loa_group.txt
Labels: :books: lore :books:, :exclamation: priority high
