Repository Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2, pull requests merged in 2021-08, with the labels that each got.

#564 Goblin Mouth Fix
  common/ethnicities/wc_ethnicities_goblin.txt
Labels: bug fix :hammer:, character designing 😶, priority critical :exclamation:

#567 Arthas Mouth Fix
  common/dna_data/wc_human_dna.txt
Labels: bug fix :hammer:, character designing 😶, priority critical :exclamation:

#474 Characters DNA Designs
  common/dna_data/wc_elf_dna.txt
  common/dna_data/wc_human_dna.txt
  common/dna_data/wc_orc_dna.txt
  common/dna_data/wc_troll_dna.txt
  common/genes/wc_gene_facial_markings.txt
  common/genes/wc_scripted_makeup.txt
  common/scripted_triggers/wc_his_character_triggers.txt
  gfx/models/portraits/decals/scripted_makeup/decal_Talanji_makeup.dds
  gfx/models/portraits/decals/scripted_makeup/decal_alleria_makeup.dds
  gfx/models/portraits/decals/scripted_makeup/decal_ateena_warpaint.dds
  gfx/portraits/portrait_modifiers/01_headgear.txt
  gfx/portraits/portrait_modifiers/50_beards_scripted_characters.txt
  gfx/portraits/portrait_modifiers/50_hairstyles_scripted_characters.txt
  gfx/portraits/portrait_modifiers/wc_facial_markings.txt
  gfx/portraits/portrait_modifiers/wc_scripted_appearances.txt
  history/characters/42000_high_elf.txt
  history/characters/48000_tirassian.txt
  history/characters/60000_63000_lordaeronian.txt
  history/characters/66000_zandalari.txt
  history/characters/80000_drakkari.txt
  localization/english/wc_portraits_l_english.yml
  localization/french/wc_portraits_l_french.yml
Labels: character designing 😶, priority high :exclamation:

#568 Rasta Clothes Fixes
  common/genes/05_genes_special_accessories_clothes.txt
  common/genes/06_genes_special_accessories_headgear.txt
  gfx/models/portraits/attachments/male_cloaks/secular/zandalari/rastakhan/male_cloaks_secular_zandalari_rastakhan.mesh
Labels: 3D graphics :triangular_ruler:, bug fix :hammer:, priority critical :exclamation:

#563 Cultural Dynasty Names
  common/culture/cultures/ancient.txt
  common/culture/cultures/aqir.txt
  common/culture/cultures/arakkoa.txt
  common/culture/cultures/centaur.txt
  common/culture/cultures/demonic.txt
  common/culture/cultures/draenei.txt
  common/culture/cultures/dragon.txt
  common/culture/cultures/dryad.txt
  common/culture/cultures/dwarf.txt
  common/culture/cultures/elemental.txt
  common/culture/cultures/elf.txt
  common/culture/cultures/furbolg.txt
  common/culture/cultures/gnoll.txt
  common/culture/cultures/gnome.txt
  common/culture/cultures/goblin.txt
  common/culture/cultures/harpy.txt
  common/culture/cultures/hozen.txt
  common/culture/cultures/human.txt
  common/culture/cultures/jinyu.txt
  common/culture/cultures/kobold.txt
  common/culture/cultures/magnataur.txt
  common/culture/cultures/mogu.txt
  common/culture/cultures/murloc.txt
  common/culture/cultures/ogre.txt
  common/culture/cultures/orc.txt
  common/culture/cultures/pandaren.txt
  common/culture/cultures/pygmy.txt
  common/culture/cultures/quilboar.txt
  common/culture/cultures/sethrak.txt
  common/culture/cultures/shathyar.txt
  common/culture/cultures/tauren.txt
  common/culture/cultures/titanforged.txt
  common/culture/cultures/tortollan.txt
  common/culture/cultures/trogg.txt
  common/culture/cultures/troll.txt
  common/culture/cultures/tuskarr.txt
  common/culture/cultures/undead.txt
  common/culture/cultures/vrykul.txt
  common/culture/cultures/vulpera.txt
  common/dynasties/100000_night_elf.txt
  common/dynasties/114000_magnataur.txt
  common/dynasties/116000_tauren.txt
  common/dynasties/121000_tolvir.txt
  common/dynasties/122000_pygmy.txt
  common/dynasties/126000_centaur.txt
  common/dynasties/127000_highborne.txt
  common/dynasties/128000_night_elf.txt
  common/dynasties/150000_titan.txt
  common/dynasties/172000_mogu.txt
  common/dynasties/175000_yaungol.txt
  common/dynasties/18000_kobold.txt
  common/dynasties/24000_gilnean.txt
  common/dynasties/42000_ogre.txt
  common/dynasties/60000_pirate.txt
  common/dynasties/70000_vrykul.txt
  common/dynasties/8000_troll.txt
  common/dynasties/wc_easter_egg_dynasties.txt
  history/characters/440000_storm_giant.txt
  localization/english/dynasties/wc_dynasty_names_l_english.yml
  localization/english/names/wc_character_names_l_english.yml
Labels: localisation :page_facing_up:, priority critical :exclamation:

#560 Naga Fixes
  common/ethnicities/00_ethnicities_templates.txt
  common/ethnicities/wc_ethnicities_elven.txt
  common/genes/01_genes_morph.txt
  common/genes/wc_gene_body_naga_test.txt
  gfx/models/portraits/male_head/male_head.asset
  gfx/portraits/accessories/cloaks.txt
  gfx/portraits/accessories/clothes.txt
  gfx/portraits/accessories/wc_back_fins.txt
  gfx/portraits/accessories/wc_head_fins.txt
  gfx/portraits/accessories/wc_tail.txt
Labels: bug fix :hammer:, character designing 😶

#380 Riflemen Unit
  common/men_at_arms_types/00_maa_types.txt
  common/script_values/00_men_at_arms_values.txt
  common/script_values/wc_men_at_arms_values.txt
  gfx/interface/icons/regimenttypes/gunmen.dds
  gfx/interface/illustrations/men_at_arms_big/gunmen.dds
  gfx/interface/illustrations/men_at_arms_small/gunmen.dds
  localization/english/wc_game_concepts_l_english.yml
  localization/english/wc_regiment_l_english.yml
  localization/replace/english/wc_game_concepts_l_english.yml
Labels: priority low :grey_exclamation:

#280 Dire Troll Trait
  common/customizable_localization/00_FR_custom_loc.txt
  common/customizable_localization/00_insult_custom_loc.txt
  common/customizable_localization/00_ruler_transition_loc.txt
  common/deathreasons/00_natural_deaths.txt
  common/ethnicities/wc_ethnicities_draenei.txt
  common/ethnicities/wc_ethnicities_dwarven.txt
  common/ethnicities/wc_ethnicities_elven.txt
  common/ethnicities/wc_ethnicities_goblin.txt
  common/ethnicities/wc_ethnicities_ogre.txt
  common/ethnicities/wc_ethnicities_orcish.txt
  common/ethnicities/wc_ethnicities_troll.txt
  common/ethnicities/wc_ethnicities_vrykul.txt
  common/on_action/child_birth_on_actions.txt
  common/script_values/01_dynamic_values.txt
  common/scripted_character_templates/00_pool_repopulation_character_templates.txt
  common/scripted_effects/wc_race_effects.txt
  common/scripted_modifiers/00_elective_successions_scripted_modifiers.txt
  common/scripted_modifiers/00_voter_strength_scripted_modifiers.txt
  common/scripted_triggers/00_scripted_triggers.txt
  common/scripted_triggers/wc_health_triggers.txt
  common/scripted_triggers/wc_portrait_triggers.txt
  common/traits/wc_genetic_traits.txt
  events/birth_events.txt
  events/education_and_childhood/coming_of_age_events.txt
  events/lifestyles/statecraft_lifestyle/diplomacy_generic_events.txt
  events/war_events/knight_events.txt
  gfx/interface/icons/traits/dire.dds
  gfx/portraits/trait_portrait_modifiers/wc_dire_modifier.txt
  localization/english/wc_traits_l_english.yml
Labels: new feature :star:, priority medium :grey_exclamation:, WIP :construction:

#546 Blood Troll Improvements
  common/culture/cultures/troll.txt
  common/ethnicities/00_ethnicities_templates.txt
  common/ethnicities/wc_ethnicities_troll.txt
  common/genes/wc_gene_body_markings.txt
  common/genes/wc_gene_facial_markings.txt
  common/scripted_triggers/wc_clothing_triggers.txt
  gfx/models/portraits/decals/bloodtroll_tattoos/decal_bloodtroll_bodypaint_01.dds
  gfx/models/portraits/decals/bloodtroll_tattoos/decal_bloodtroll_tattoo_01.dds
  gfx/models/portraits/decals/bloodtroll_tattoos/decal_bloodtroll_tattoo_02.dds
  gfx/models/portraits/decals/bloodtroll_tattoos/decal_bloodtroll_tattoo_03.dds
  gfx/models/portraits/decals/bloodtroll_tattoos/decal_bloodtroll_tattoo_04.dds
  gfx/models/portraits/decals/bloodtroll_tattoos/decal_bloodtroll_tattoo_05.dds
  gfx/models/portraits/decals/bloodtroll_tattoos/decal_bloodtroll_tattoo_06.dds
  gfx/models/portraits/decals/bloodtroll_tattoos/decal_bloodtroll_tattoo_07.dds
  gfx/models/portraits/decals/bloodtroll_tattoos/decal_bloodtroll_tattoo_08.dds
  gfx/models/portraits/decals/bloodtroll_tattoos/decal_bloodtroll_tattoo_09.dds
  gfx/models/portraits/decals/bloodtroll_tattoos/decal_bloodtroll_tattoo_10.dds
  gfx/models/portraits/decals/bloodtroll_tattoos/decal_bloodtroll_tattoo_11.dds
  gfx/models/portraits/decals/bloodtroll_tattoos/decal_bloodtroll_tattoo_12.dds
  gfx/models/portraits/decals/scripted_makeup/decal_ateena_warpaint.dds
  gfx/portraits/portrait_modifiers/wc_body_markings.txt
  gfx/portraits/portrait_modifiers/wc_facial_markings.txt
  gfx/portraits/portrait_modifiers/wc_scripted_appearances.txt
  gui/window_ruler_designer.gui
  localization/english/wc_portraits_l_english.yml
Labels: new feature :star:, priority medium :grey_exclamation:, 2D graphics :paintbrush:

#586 History Bug Fixes
  common/scripted_triggers/wc_maa_triggers.txt
  history/cultures/drakkari.txt
  history/cultures/elemental_group.txt
  history/cultures/frozen_giant.txt
  history/cultures/night_elf.txt
  history/cultures/troll_group.txt
Labels: bug fix :hammer:, priority critical :exclamation:

#581 Brotherhood of Bandits tech
  common/culture/innovations/wc_cultural_innovations.txt
  gfx/interface/icons/culture_innovations/innovation_brotherhood_of_bandits.dds
  history/cultures/blackwater.txt
  history/cultures/pirate_culture.txt
  history/cultures/wastewander.txt
  localization/english/culture/wc_cultural_innovations_l_english.yml
Labels: priority low :grey_exclamation:, history 👑

#573 Glowing Eyes
  common/dna_data/wc_dwarf_dna.txt
  common/dna_data/wc_easter_egg_dna.txt
  common/dna_data/wc_elf_dna.txt
  common/dna_data/wc_human_dna.txt
  common/dna_data/wc_nightelf_dna.txt
  common/dna_data/wc_orc_dna.txt
  common/dna_data/wc_troll_dna.txt
  common/ethnicities/00_ethnicities_templates.txt
  common/ethnicities/00_ethnicities_vanity_characters.txt
  common/ethnicities/wc_ethnicities_draenei.txt
  common/ethnicities/wc_ethnicities_dwarven.txt
  common/ethnicities/wc_ethnicities_elven.txt
  common/ethnicities/wc_ethnicities_goblin.txt
  common/ethnicities/wc_ethnicities_troll.txt
  common/ethnicities/wc_ethnicities_vrykul.txt
  common/genes/02_genes_accessories_misc.txt
  common/genes/wc_genes_special_eyes.txt
  gfx/FX/jomini/portrait.shader
  gfx/models/portraits/decals/male_head/glowing_eyes.dds
  gfx/models/portraits/decals/male_head/glowing_pupils_eyes.dds
  gfx/models/portraits/female_head/female_eyes.asset
  gfx/models/portraits/female_head/female_eyes.mesh
  gfx/models/portraits/female_head/female_eyes_left.mesh
  gfx/models/portraits/female_head/female_eyes_right.mesh
  gfx/models/portraits/male_head/male_eyes.asset
  gfx/models/portraits/male_head/male_eyes.mesh
  gfx/models/portraits/male_head/male_eyes_left.mesh
  gfx/models/portraits/male_head/male_eyes_magic_no_pupils_diffuse.dds
  gfx/models/portraits/male_head/male_eyes_magic_pupils_diffuse.dds
  gfx/models/portraits/male_head/male_eyes_right.mesh
  gfx/portraits/accessories/bodyparts.txt
  gfx/portraits/portrait_modifiers/01_animation_expressions.txt
  gfx/portraits/portrait_modifiers/99_special.txt
  gfx/portraits/portrait_modifiers/wc_custom_eyebrows.txt
  gfx/portraits/portrait_modifiers/wc_custom_eyes.txt
  gfx/portraits/portrait_modifiers/wc_custom_horns.txt
  gfx/portraits/portrait_modifiers/wc_eyes.txt
  gfx/portraits/portrait_modifiers/wc_facial_markings.txt
  gfx/portraits/trait_portrait_modifiers/00_trait_modifiers.txt
  gfx/portraits/trait_portrait_modifiers/wc_fel_orc_modifier.txt
  gfx/portraits/trait_portrait_modifiers/wc_undead_modifier.txt
  gui/window_ruler_designer.gui
  localization/english/wc_portraits_l_english.yml
Labels: priority high :exclamation:, 3D graphics :triangular_ruler:, character designing 😶

#591 More elemental trees
  common/focuses/wc_magic_lifestyle_focuses.txt
  common/lifestyle_perks/wc_elemental_air_magic_perks.txt
  common/lifestyle_perks/wc_elemental_earth_magic_perks.txt
  common/lifestyle_perks/wc_elemental_fire_magic_perks.txt
  common/lifestyle_perks/wc_elemental_water_magic_perks.txt
  common/script_values/wc_magic_lifestyles_values.txt
  common/scripted_triggers/00_lifestyle_triggers.txt
  common/scripted_triggers/wc_magic_lifestyles_triggers.txt
  gfx/interface/icons/lifestyle_tree_backgrounds/elemental_air_magic_tree_1.dds
  gfx/interface/icons/lifestyle_tree_backgrounds/elemental_air_magic_tree_2.dds
  gfx/interface/icons/lifestyle_tree_backgrounds/elemental_earth_magic_tree_1.dds
  gfx/interface/icons/lifestyle_tree_backgrounds/elemental_earth_magic_tree_2.dds
  gfx/interface/icons/lifestyle_tree_backgrounds/elemental_fire_magic_tree_1.dds
  gfx/interface/icons/lifestyle_tree_backgrounds/elemental_fire_magic_tree_2.dds
  gfx/interface/icons/lifestyle_tree_backgrounds/elemental_water_magic_tree_1.dds
  gfx/interface/icons/lifestyle_tree_backgrounds/elemental_water_magic_tree_2.dds
  localization/english/wc_magic_lifestyles_l_english.yml
Labels: bug fix :hammer:, new feature :star:, priority medium :grey_exclamation:

#597 Wizard Mustaches
  common/ethnicities/00_ethnicities_templates.txt
  common/genes/01_genes_morph.txt
  gfx/models/portraits/attachments/male_beards/western/male_beard_rtt_01/male_beard_rtt_01.asset
  gfx/models/portraits/attachments/male_beards/western/male_beard_rtt_01/male_beard_rtt_01.mesh
  gfx/models/portraits/attachments/male_beards/western/male_beard_rtt_01/male_beard_rtt_01_bs_mustaches.mesh
  gfx/models/portraits/male_head/male_head.asset
  gfx/portraits/portrait_modifiers/01_custom_beards.txt
  localization/english/wc_portraits_l_english.yml
  localization/replace/english/wc_replacements_l_english.yml
Labels: priority critical :exclamation:, 3D graphics :triangular_ruler:

#598 Long with Ponytail with Crowns
  common/genes/03_genes_special_accessories_hairstyles.txt
  gfx/models/portraits/attachments/male_hair/orcish/male_hair_long_with_ponytail/wc_male_hair_long_with_ponytail.asset
  gfx/models/portraits/attachments/male_hair/orcish/male_hair_long_with_ponytail/wc_male_hair_long_with_ponytail_crown.mesh
  gfx/portraits/accessories/headgear.txt
  gfx/portraits/accessories/wc_hairstyles.txt
Labels: priority critical :exclamation:, 3D graphics :triangular_ruler:

#607 Mustache with Goatee
  common/genes/04_genes_special_accessories_beards.txt
  gfx/models/portraits/attachments/male_beards/human/male_beard_human_01/wc_male_beard_human_01.asset
  gfx/models/portraits/attachments/male_beards/human/male_beard_human_01/wc_male_beard_human_01.mesh
  gfx/models/portraits/attachments/male_beards/human/male_beard_human_01/wc_male_beard_human_01_bs_fat.mesh
  gfx/portraits/accessories/wc_beards.txt
  gfx/portraits/portrait_modifiers/50_beards_scripted_characters.txt
  localization/english/wc_portraits_l_english.yml
Labels: priority high :exclamation:, 3D graphics :triangular_ruler:, character designing 😶

#609 Glowing Iris
  common/genes/wc_genes_special_eyes.txt
  gfx/models/portraits/decals/male_head/glowing_iris_eyes.dds
  localization/english/wc_portraits_l_english.yml
Labels: priority critical :exclamation:, 2D graphics :paintbrush:, character designing 😶

#617 Maiev Personality Traits
  history/characters/340000_night_elf.txt
Labels: suggestion :question:, lore :books:, history 👑

#612 DNA for Perenolde, Menethil, Fordragon, Trollbane + Others
  common/dna_data/wc_elf_dna.txt
  common/dna_data/wc_human_dna.txt
  common/dna_data/wc_nightelf_dna.txt
  common/dna_data/wc_troll_dna.txt
  common/genes/wc_gene_facial_markings.txt
  common/scripted_triggers/wc_his_character_triggers.txt
  gfx/models/portraits/decals/scripted_makeup/decal_malfurion_markings.dds
  gfx/portraits/portrait_modifiers/50_beards_scripted_characters.txt
  gfx/portraits/portrait_modifiers/50_hairstyles_scripted_characters.txt
  gfx/portraits/portrait_modifiers/wc_scripted_appearances.txt
  gfx/portraits/trait_portrait_modifiers/wc_undead_modifier.txt
  history/characters/1_azerothian.txt
  history/characters/340000_night_elf.txt
  history/characters/38000_arathorian.txt
  history/characters/48000_tirassian.txt
  history/characters/53000_hillsbrad.txt
  history/characters/58000_alteraci.txt
  history/characters/60000_63000_lordaeronian.txt
Labels: priority critical :exclamation:, character designing 😶, good first testing 🧪

#611 DNA for Greymane, Fordring, VanCleef, Wrynn + Others
  common/dna_data/wc_gnome_dna.txt
  common/dna_data/wc_human_dna.txt
  common/scripted_triggers/wc_his_character_triggers.txt
  gfx/portraits/portrait_modifiers/50_beards_scripted_characters.txt
  gfx/portraits/portrait_modifiers/50_hairstyles_scripted_characters.txt
  history/characters/16000_gnome.txt
  history/characters/1_azerothian.txt
  history/characters/46000_gilnean.txt
  history/characters/60000_63000_lordaeronian.txt
Labels: priority critical :exclamation:, character designing 😶, good first testing 🧪

#635 Gave Mechagnomes Tinekrs Tech
  common/culture/innovations/wc_cultural_innovations.txt
  history/cultures/mechagnome.txt
Labels: lore :books:

#634 Removed Titles/Fixed bug for Knights
  common/customizable_localization/00_knight_culture.txt
  common/scripted_triggers/wc_localization_triggers.txt
  localization/english/wc_knight_titles_l_english.yml
  localization/german/wc_knight_titles_l_german.yml
Labels: lore :books:, bug :bug:

#596 Update wc_traits_magic_lifestyles_l_english.yml
  localization/english/wc_traits_magic_lifestyles_l_english.yml
Labels: localisation :page_facing_up:, priority low :grey_exclamation:

#642 Jandice Trait Update
  history/characters/60000_63000_lordaeronian.txt
Labels: suggestion :question:, lore :books:, history 👑

#645 Sons of Lothar Death Dates
  history/characters/1_azerothian.txt
  history/characters/22000_wildhammer.txt
  history/characters/38000_arathorian.txt
  history/characters/42000_high_elf.txt
  history/characters/59000_dalaranian.txt
  history/characters/60000_63000_lordaeronian.txt
  history/provinces/00_k_ahnqiraj.txt
  history/provinces/00_k_black_morass.txt
  history/provinces/00_k_blackrock.txt
  history/provinces/00_k_silithus.txt
  history/provinces/00_k_wetlands.txt
  history/titles/000_wc_other_titles.txt
  history/titles/00_k_ahnqiraj.txt
  history/titles/00_k_black_morass.txt
  history/titles/00_k_blackrock.txt
  history/titles/00_k_silithus.txt
  history/titles/00_k_stormwind.txt
  history/titles/00_k_wetlands.txt
  history/titles/00_k_zulaman.txt
Labels: bug fix :hammer:, lore :books:, history 👑
