Repository Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2, pull requests merged in 2021-03, with the labels that each got.

#99 1st History Tweaks
  history/titles/wc_development_history.txt
Labels: :balance_scale: balance :balance_scale:, :books: lore :books:, :exclamation: priority high

#227 2nd Small Improvements
  common/laws/01_title_succession_laws.txt
  common/religion/doctrines/wc_doctrines_religions.txt
  common/religion/religions/air_group.txt
  common/religion/religions/fire_group.txt
  common/scripted_effects/wc_horde_invasion_effects.txt
  history/titles/00_wc_other_titles.txt
Labels: :balance_scale: balance :balance_scale:, :books: lore :books:, :exclamation: priority critical

#62 1st Hostility Tweaks
  common/religion/doctrines/wc_doctrines_religions.txt
  common/religion/religions/druidism_group.txt
  common/religion/religions/fel_group.txt
  common/religion/religions/necromancy_group.txt
Labels: :balance_scale: balance :balance_scale:, :books: lore :books:, :exclamation: priority high

#232 New unit type bug fix
  common/scripted_triggers/wc_maa_triggers.txt
Labels: :beetle: bug :beetle:, :exclamation: priority critical

#229 Union Renaming and Description
  common/customizable_localization/wc_general_custom_loc.txt
  common/on_action/death.txt
  common/scripted_effects/wc_gui_effects.txt
  common/scripted_effects/wc_pol_faction_effects.txt
  common/scripted_guis/wc_pol_faction.txt
  events/wc_events/wc_pol_faction_events.txt
  gui/hud.gui
  gui/window_decisions.gui
  localization/english/wc_gui_l_english.yml
  localization/english/wc_pol_faction_l_english.yml
  localization/german/wc_gui_l_german.yml
  localization/german/wc_pol_faction_l_german.yml
Labels: :page_facing_up: localisation - german :pen:, :page_facing_up: localisation :pen:, :star: new feature :new:, interface

#197 Goblin Ethnicity
  common/culture/cultures/goblin.txt
  common/ethnicities/wc_ethnicities_goblin.txt
  common/genes/02_genes_accessories_hairstyles.txt
  common/scripted_triggers/wc_portrait_triggers.txt
  common/scripted_triggers/wc_race_triggers.txt
  localization/english/wc_portraits_l_english.yml
Labels: :art: 3D graphics :triangular_ruler:, :exclamation: priority high, :star: new feature :new:

#186 Lore-Important Characters Generated Families - Gamerule
  common/game_rules/000_wc_game_rules.txt
  events/game_rule_events.txt
  localization/english/wc_game_rules_l_english.yml
Labels: :grey_exclamation: priority low, :star: new feature :new:

#235 Skin Value
  common/ethnicities/00_ethnicities_templates.txt
  common/genes/01_genes_morph.txt
  localization/english/wc_portraits_l_english.yml
Labels: :art: 3D graphics :triangular_ruler:, :exclamation: priority high

#245 Error fixes
  history/cultures/draenei.txt
  history/cultures/forsaken.txt
  history/cultures/scourge.txt
Labels: :beetle: bug :beetle:, :grey_exclamation: priority medium

#253 4th Bug Crusade
  common/casus_belli_types/00_religious_war.txt
  common/culture/cultures/elf.txt
  common/culture/cultures/gnome.txt
  common/culture/cultures/goblin.txt
  common/culture/cultures/ogre.txt
  common/culture/cultures/orc.txt
  common/culture/cultures/troll.txt
  common/culture/cultures/vrykul.txt
  common/scripted_effects/00_faction_effects.txt
  common/scripted_effects/00_mongol_invasion_effects.txt
  common/scripted_effects/00_stewardship_lifestyle_effects.txt
  events/activities/hunt_activity/hunt_events.txt
  events/activities/pilgrimage_activity/pilgrimage_events.txt
  events/government_events/clan_events.txt
  events/health_events.txt
  events/lifestyles/governance_lifestyle/stewardship_general_events.txt
  events/lifestyles/governance_lifestyle/stewardship_wealth_events.txt
  events/lifestyles/intrigue_lifestyle/intrigue_scheming_events.txt
  events/lifestyles/scholarship_lifestyle/learning_medicine_events.txt
  events/lifestyles/warfare_lifestyle/martial_authority_events.txt
  events/lifestyles/warfare_lifestyle/martial_chivalry_events.txt
  events/lifestyles/warfare_lifestyle/martial_strategy_events.txt
  events/religion_events/faith_creation_events.txt
  events/story_cycles/peasant_affair/story_cycle_peasant_affair_events.txt
  events/stress_events/stress_threshold_prison_events.txt
  events/stress_events/stress_threshold_special_events.txt
  events/varangian_events.txt
  localization/english/custom_localization/wc_insult_custom_loc_l_english.yml
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#257 Added support for other languages for mod insults
  common/customizable_localization/00_insult_custom_loc.txt
  localization/english/custom_localization/wc_insult_custom_loc_l_english.yml
Labels: :grey_exclamation: priority medium, :page_facing_up: localisation :pen:
