Repository Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2, pull requests merged in 2021-11, with the labels that each got.

#749 jomini_effect.cpp:311&318
  common/achievements/fp1_achievements.txt
  common/achievements/standard_achievements.txt
  common/buildings/00_special_buildings.txt
  common/customizable_localization/00_ruler_transition_loc.txt
  common/decisions/00_holy_order_decisions.txt
  common/decisions/10_religious_decisions.txt
  common/scripted_triggers/00_faction_triggers.txt
  common/succession_election/00_feudal_elective.txt
  events/error_suppression_events.txt
Labels: bug fix :hammer:, priority high :exclamation:

#747 Merge of physical lifestyle to magical lifestyles branch
  common/focuses/wc_physical_lifestyle_focuses.txt
  common/game_concepts/wc_lifestyles_concepts.txt
  common/game_concepts/wc_lifestyles_physical_concepts.txt
  common/lifestyle_perks/wc_physical_perks.txt
  common/lifestyles/wc_lifestyles.txt
  common/script_values/wc_lifestyles_magic_values.txt
  common/script_values/wc_lifestyles_physical_values.txt
  common/script_values/wc_physical_lifestyle_values.txt
  common/scripted_triggers/wc_lifestyles_magic_triggers.txt
  common/scripted_triggers/wc_lifestyles_physical_triggers.txt
  common/scripted_triggers/wc_physical_lifestyle_triggers.txt
  gfx/interface/icons/alerts/action_lifestyle_physical.dds
  gfx/interface/icons/focuses/death_magic_focus_1.dds
  gfx/interface/icons/focuses/physical_focus_1.dds
  gfx/interface/icons/focuses/physical_focus_2.dds
  gfx/interface/icons/focuses/physical_focus_3.dds
  gfx/interface/icons/lifestyle_tree_backgrounds/physical_tree_1.dds
  gfx/interface/icons/lifestyle_tree_backgrounds/physical_tree_2.dds
  gfx/interface/icons/lifestyle_tree_backgrounds/physical_tree_3.dds
  gfx/interface/icons/lifestyles/physical_lifestyle.dds
  gfx/interface/illustrations/lifestyles_background/physical_lifestyle.dds
  gui/window_character_lifestyle.gui
  localization/english/gui/wc_magic_lifestyles_window_character_lifestyle_l_english.yml
  localization/english/wc_game_concepts_lifestyles_l_english.yml
  localization/english/wc_lifestyles_l_english.yml
  localization/english/wc_lifestyles_physical_l_english.yml
  localization/english/wc_physical_lifestyle_l_english.yml
  localization/french/wc_lifestyles_physical_l_french.yml
  localization/french/wc_physical_lifestyle_l_french.yml
  localization/german/wc_lifestyles_l_german.yml
  localization/german/wc_lifestyles_physical_l_german.yml
  localization/german/wc_physical_lifestyle_l_german.yml
  localization/replace/english/wc_game_concepts_l_english.yml
Labels: maintenance :wrench:, priority medium :grey_exclamation:

#347 Physical Lifestyle
  common/focuses/wc_physical_lifestyle_focuses.txt
  common/game_concepts/wc_lifestyles_concepts.txt
  common/game_concepts/wc_lifestyles_physical_concepts.txt
  common/important_actions/00_lifestyle.txt
  common/important_actions/wc_lifestyle_actions.txt
  common/lifestyle_perks/wc_physical_perks.txt
  common/lifestyles/wc_lifestyles.txt
  common/script_values/wc_lifestyles_magic_values.txt
  common/script_values/wc_lifestyles_physical_values.txt
  common/scripted_triggers/wc_lifestyles_magic_triggers.txt
  common/scripted_triggers/wc_lifestyles_physical_triggers.txt
  gfx/interface/icons/alerts/action_lifestyle_physical.dds
  gfx/interface/icons/focuses/death_magic_focus_1.dds
  gfx/interface/icons/focuses/physical_focus_1.dds
  gfx/interface/icons/focuses/physical_focus_2.dds
  gfx/interface/icons/focuses/physical_focus_3.dds
  gfx/interface/icons/lifestyle_tree_backgrounds/physical_tree_1.dds
  gfx/interface/icons/lifestyle_tree_backgrounds/physical_tree_2.dds
  gfx/interface/icons/lifestyle_tree_backgrounds/physical_tree_3.dds
  gfx/interface/icons/lifestyles/physical_lifestyle.dds
  gfx/interface/illustrations/lifestyles_background/physical_lifestyle.dds
  gui/window_character_lifestyle.gui
  localization/english/gui/wc_magic_lifestyles_window_character_lifestyle_l_english.yml
  localization/english/wc_game_concepts_lifestyles_l_english.yml
  localization/english/wc_lifestyles_physical_l_english.yml
  localization/french/wc_lifestyles_physical_l_french.yml
  localization/german/wc_lifestyles_physical_l_german.yml
  localization/replace/english/wc_game_concepts_l_english.yml
Labels: new feature :star:, lore :books:, localisation :page_facing_up:, priority medium :grey_exclamation:, balance :balance_scale:, interface 👁‍🗨

#757 Missing trigger bugfix
  common/focuses/00_lifestyle_focuses.txt
  common/focuses/wc_magic_lifestyle_focuses.txt
  common/lifestyle_perks/00_diplomacy_1_foreign_affairs_tree_perks.txt
  common/lifestyle_perks/00_diplomacy_2_majesty_tree_perks.txt
  common/lifestyle_perks/00_diplomacy_3_family_tree_perks.txt
  common/lifestyle_perks/00_intrigue_1_skulduggery_tree_perks.txt
  common/lifestyle_perks/00_intrigue_2_temptation_tree_perks.txt
  common/lifestyle_perks/00_intrigue_3_intimidation_tree_perks.txt
  common/lifestyle_perks/00_learning_1_medicine_tree_perks.txt
  common/lifestyle_perks/00_learning_2_scholarship_tree_perks.txt
  common/lifestyle_perks/00_learning_3_theology_tree_perks.txt
  common/lifestyle_perks/00_martial_1_strategy_tree_perks.txt
  common/lifestyle_perks/00_martial_2_authority_tree_perks.txt
  common/lifestyle_perks/00_martial_3_chivalry_tree_perks.txt
  common/lifestyle_perks/00_stewardship_1_wealth_tree_perks.txt
  common/lifestyle_perks/00_stewardship_2_domain_tree_perks.txt
  common/lifestyle_perks/00_stewardship_3_duty_tree_perks.txt
  common/lifestyle_perks/wc_death_magic_perks.txt
  common/lifestyle_perks/wc_disorder_magic_perks.txt
  common/lifestyle_perks/wc_elemental_air_magic_perks.txt
  common/lifestyle_perks/wc_elemental_earth_magic_perks.txt
  common/lifestyle_perks/wc_elemental_fire_magic_perks.txt
  common/lifestyle_perks/wc_elemental_water_magic_perks.txt
  common/lifestyle_perks/wc_life_magic_perks.txt
  common/lifestyle_perks/wc_light_magic_perks.txt
  common/lifestyle_perks/wc_order_magic_perks.txt
  common/lifestyle_perks/wc_shadow_magic_perks.txt
  common/scripted_triggers/00_lifestyle_triggers.txt
  common/scripted_triggers/wc_lifestyles_magic_triggers.txt
Labels: bug fix :hammer:, priority critical :exclamation:

#745 Long Lived XP
  common/game_concepts/wc_lifestyle_game_concepts.txt
  common/game_concepts/wc_racial_game_concepts.txt
  common/game_rules/000_wc_game_rules.txt
  common/lifestyle_perks/00_diplomacy_1_foreign_affairs_tree_perks.txt
  common/lifestyle_perks/00_diplomacy_2_majesty_tree_perks.txt
  common/lifestyle_perks/00_diplomacy_3_family_tree_perks.txt
  common/lifestyle_perks/00_intrigue_1_skulduggery_tree_perks.txt
  common/lifestyle_perks/00_intrigue_2_temptation_tree_perks.txt
  common/lifestyle_perks/00_intrigue_3_intimidation_tree_perks.txt
  common/lifestyle_perks/00_learning_1_medicine_tree_perks.txt
  common/lifestyle_perks/00_learning_2_scholarship_tree_perks.txt
  common/lifestyle_perks/00_learning_3_theology_tree_perks.txt
  common/lifestyle_perks/00_martial_1_strategy_tree_perks.txt
  common/lifestyle_perks/00_martial_2_authority_tree_perks.txt
  common/lifestyle_perks/00_martial_3_chivalry_tree_perks.txt
  common/lifestyle_perks/00_stewardship_1_wealth_tree_perks.txt
  common/lifestyle_perks/00_stewardship_2_domain_tree_perks.txt
  common/lifestyle_perks/00_stewardship_3_duty_tree_perks.txt
  common/modifiers/wc_lifestyle_modifiers.txt
  common/on_action/lifestyles/wc_lifestyle_on_actions.txt
  common/on_action/title_on_actions.txt
  common/on_action/yearly_on_actions.txt
  common/script_values/wc_lifestyle_values.txt
  common/scripted_effects/wc_lifestyle_effects.txt
  events/lifestyles/wc_lifestyle_events.txt
  events/wc_events/wc_race_events.txt
  localization/english/modifiers/wc_modifiers_l_english.yml
  localization/english/wc_game_concepts_l_english.yml
  localization/english/wc_game_rules_l_english.yml
  localization/replace/english/wc_game_concepts_l_english.yml
Labels: vanilla modification :icecream:, priority high :exclamation:, balance :balance_scale:

#748 Physical lifestyle traits
  common/customizable_localization/wc_lifestyles_custom_loc.txt
  common/lifestyle_perks/wc_physical_perks.txt
  common/on_action/lifestyles/general_lifestyle_on_actions.txt
  common/script_values/wc_lifestyles_physical_values.txt
  common/scripted_effects/wc_lifestyle_traits_effects.txt
  common/traits/wc_lifestyle_magic_user_traits.txt
  common/traits/wc_lifestyle_physical_traits.txt
  gfx/interface/icons/traits/physical_lifestyle_dexterity_1.dds
  gfx/interface/icons/traits/physical_lifestyle_dexterity_2.dds
  gfx/interface/icons/traits/physical_lifestyle_dexterity_3.dds
  gfx/interface/icons/traits/physical_lifestyle_dexterity_4.dds
  gfx/interface/icons/traits/physical_lifestyle_dexterity_5.dds
  gfx/interface/icons/traits/physical_lifestyle_endurance_1.dds
  gfx/interface/icons/traits/physical_lifestyle_endurance_2.dds
  gfx/interface/icons/traits/physical_lifestyle_endurance_3.dds
  gfx/interface/icons/traits/physical_lifestyle_endurance_4.dds
  gfx/interface/icons/traits/physical_lifestyle_endurance_5.dds
  gfx/interface/icons/traits/physical_lifestyle_strength_1.dds
  gfx/interface/icons/traits/physical_lifestyle_strength_2.dds
  gfx/interface/icons/traits/physical_lifestyle_strength_3.dds
  gfx/interface/icons/traits/physical_lifestyle_strength_4.dds
  gfx/interface/icons/traits/physical_lifestyle_strength_5.dds
  gui/window_character_lifestyle.gui
  localization/english/gui/wc_magic_lifestyles_window_character_lifestyle_l_english.yml
  localization/english/wc_lifestyles_magic_l_english.yml
  localization/english/wc_traits_lifestyles_l_english.yml
Labels: new feature :star:, priority medium :grey_exclamation:, interface 👁‍🗨

#763 Update error_suppression_events.txt
  events/error_suppression_events.txt
Labels: bug fix :hammer:, priority high :exclamation:

#711 Dark Government Flavorization
  common/coat_of_arms/template_lists/coa_templates.txt
  common/coat_of_arms/template_lists/color_lists.txt
  common/event_backgrounds/01_event_backgrounds.txt
  common/flavorization/wc_title_holders.txt
  common/named_colors/default_colors.txt
  common/named_colors/wc_colors.txt
  common/scripted_triggers/wc_coa_triggers.txt
  localization/english/culture/wc_culture_titles_l_english.yml
  localization/german/culture/wc_culture_titles_l_german.yml
Labels: priority critical :exclamation:, 2D graphics :paintbrush:

#365 Storm Hammer Innovation
  common/culture/innovations/00_early_medieval_innovations.txt
  common/culture/innovations/00_high_medieval_innovations.txt
  common/culture/innovations/00_late_medieval_innovations.txt
  common/culture/innovations/wc_cultural_innovations.txt
  gfx/interface/icons/culture_innovations/innovation_storm_hammers.dds
  localization/english/culture/wc_cultural_innovations_l_english.yml
  localization/german/culture/wc_cultural_innovations_l_german.yml
Labels: new feature :star:, priority low :grey_exclamation:, balance :balance_scale:

#754 New lifestyles - small improvements
  common/decisions/test_decision.txt
  common/focuses/wc_lifestyle_focuses.txt
  common/focuses/wc_physical_lifestyle_focuses.txt
  common/lifestyle_perks/00_diplomacy_1_foreign_affairs_tree_perks.txt
  common/lifestyle_perks/00_diplomacy_2_majesty_tree_perks.txt
  common/lifestyle_perks/00_diplomacy_3_family_tree_perks.txt
  common/lifestyle_perks/00_intrigue_1_skulduggery_tree_perks.txt
  common/lifestyle_perks/00_intrigue_2_temptation_tree_perks.txt
  common/lifestyle_perks/00_intrigue_3_intimidation_tree_perks.txt
  common/lifestyle_perks/00_learning_1_medicine_tree_perks.txt
  common/lifestyle_perks/00_learning_2_scholarship_tree_perks.txt
  common/lifestyle_perks/00_learning_3_theology_tree_perks.txt
  common/lifestyle_perks/00_martial_1_strategy_tree_perks.txt
  common/lifestyle_perks/00_martial_2_authority_tree_perks.txt
  common/lifestyle_perks/00_martial_3_chivalry_tree_perks.txt
  common/lifestyle_perks/00_stewardship_1_wealth_tree_perks.txt
  common/lifestyle_perks/00_stewardship_2_domain_tree_perks.txt
  common/lifestyle_perks/00_stewardship_3_duty_tree_perks.txt
  common/lifestyle_perks/wc_death_magic_perks.txt
  common/lifestyle_perks/wc_disorder_magic_perks.txt
  common/lifestyle_perks/wc_elemental_air_magic_perks.txt
  common/lifestyle_perks/wc_elemental_earth_magic_perks.txt
  common/lifestyle_perks/wc_elemental_fire_magic_perks.txt
  common/lifestyle_perks/wc_elemental_water_magic_perks.txt
  common/lifestyle_perks/wc_life_magic_perks.txt
  common/lifestyle_perks/wc_light_magic_perks.txt
  common/lifestyle_perks/wc_order_magic_perks.txt
  common/lifestyle_perks/wc_physical_perks.txt
  common/lifestyle_perks/wc_shadow_magic_perks.txt
  common/script_values/01_dynamic_values.txt
  common/script_values/wc_lifestyles_physical_values.txt
  common/script_values/wc_lifestyles_values.txt
  common/scripted_triggers/00_lifestyle_triggers.txt
  common/scripted_triggers/wc_lifestyles_magic_triggers.txt
  common/scripted_triggers/wc_lifestyles_physical_triggers.txt
  common/scripted_triggers/wc_lifestyles_triggers.txt
  common/traits/wc_lifestyle_physical_traits.txt
  common/traits/wc_lifestyle_traits.txt
Labels: maintenance :wrench:, priority medium :grey_exclamation:

#669 AI Focus One Tree Before Moving to Another
  common/decisions/test_decision.txt
  common/focuses/wc_lifestyle_focuses.txt
  common/focuses/wc_physical_lifestyle_focuses.txt
  common/lifestyle_perks/00_diplomacy_1_foreign_affairs_tree_perks.txt
  common/lifestyle_perks/00_diplomacy_2_majesty_tree_perks.txt
  common/lifestyle_perks/00_diplomacy_3_family_tree_perks.txt
  common/lifestyle_perks/00_intrigue_1_skulduggery_tree_perks.txt
  common/lifestyle_perks/00_intrigue_2_temptation_tree_perks.txt
  common/lifestyle_perks/00_intrigue_3_intimidation_tree_perks.txt
  common/lifestyle_perks/00_learning_1_medicine_tree_perks.txt
  common/lifestyle_perks/00_learning_2_scholarship_tree_perks.txt
  common/lifestyle_perks/00_learning_3_theology_tree_perks.txt
  common/lifestyle_perks/00_martial_1_strategy_tree_perks.txt
  common/lifestyle_perks/00_martial_2_authority_tree_perks.txt
  common/lifestyle_perks/00_martial_3_chivalry_tree_perks.txt
  common/lifestyle_perks/00_stewardship_1_wealth_tree_perks.txt
  common/lifestyle_perks/00_stewardship_2_domain_tree_perks.txt
  common/lifestyle_perks/00_stewardship_3_duty_tree_perks.txt
  common/lifestyle_perks/wc_death_magic_perks.txt
  common/lifestyle_perks/wc_disorder_magic_perks.txt
  common/lifestyle_perks/wc_elemental_air_magic_perks.txt
  common/lifestyle_perks/wc_elemental_earth_magic_perks.txt
  common/lifestyle_perks/wc_elemental_fire_magic_perks.txt
  common/lifestyle_perks/wc_elemental_water_magic_perks.txt
  common/lifestyle_perks/wc_life_magic_perks.txt
  common/lifestyle_perks/wc_light_magic_perks.txt
  common/lifestyle_perks/wc_order_magic_perks.txt
  common/lifestyle_perks/wc_physical_perks.txt
  common/lifestyle_perks/wc_shadow_magic_perks.txt
  common/script_values/01_dynamic_values.txt
  common/script_values/wc_lifestyles_physical_values.txt
  common/script_values/wc_lifestyles_values.txt
  common/scripted_triggers/00_lifestyle_triggers.txt
  common/scripted_triggers/wc_lifestyles_magic_triggers.txt
  common/scripted_triggers/wc_lifestyles_physical_triggers.txt
  common/scripted_triggers/wc_lifestyles_triggers.txt
  common/traits/wc_lifestyle_physical_traits.txt
  common/traits/wc_lifestyle_traits.txt
Labels: vanilla modification :icecream:, priority critical :exclamation:, balance :balance_scale:

#762 11th Bug Crusade
  common/buildings/00_castle_buildings.txt
  common/buildings/00_city_buildings.txt
  common/buildings/00_common_buildings.txt
  common/buildings/00_duchy_capital_buildings.txt
  common/buildings/00_special_buildings.txt
  common/buildings/00_temple_buildings.txt
  common/buildings/00_terrain_specific_buildings.txt
  common/character_interactions/wc_debug_interactions.txt
  common/culture/cultures/demonic.txt
  common/customizable_localization/00_FR_custom_loc.txt
  common/decisions/wc_pol_faction_decisions.txt
  common/scripted_character_templates/wc_historical_draenor_templates.txt
  common/scripted_effects/wc_history_effects.txt
  common/scripted_triggers/00_building_requirement_triggers.txt
  common/scripted_triggers/00_religious_triggers.txt
  common/scripted_triggers/wc_clothing_triggers.txt
  common/scripted_triggers/wc_health_triggers.txt
  common/scripted_triggers/wc_pol_faction_triggers.txt
  common/scripted_triggers/wc_race_triggers.txt
  common/trigger_localization/wc_character_triggers.txt
  events/error_suppression_events.txt
  events/wc_events/wc_being_events.txt
  gfx/portraits/portrait_modifiers/50_beards_scripted_characters.txt
  gfx/portraits/portrait_modifiers/wc_facial_markings.txt
  history/characters/10000_orc.txt
  history/characters/29000_gnoll.txt
  history/provinces/00_k_alterac.txt
  history/provinces/00_k_barrens.txt
  history/provinces/00_k_black_morass.txt
  history/provinces/00_k_blackrock.txt
  history/provinces/00_k_dead_morass.txt
  history/provinces/00_k_dustwallow.txt
  history/provinces/00_k_feralas.txt
  history/provinces/00_k_gilneas.txt
  history/provinces/00_k_gurubashi.txt
  history/provinces/00_k_ironforge.txt
  history/provinces/00_k_kyparqov.txt
  history/provinces/00_k_plunder_isle.txt
  history/provinces/00_k_stormwind.txt
  history/provinces/00_k_stromgarde.txt
  history/provinces/00_k_wildhammer.txt
  localization/english/religion/wc_religion_l_english.yml
  localization/english/triggers/wc_character_triggers_l_english.yml
  localization/english/wc_debug_l_english.yml
  localization/english/wc_tooltip_l_english.yml
  tests/TIT-2432_trait_flags.txt
Labels: bug fix :hammer:, priority critical :exclamation:

#735 Scourge Dreadlords
  common/character_interactions/00_courtier_and_guest_interactions.txt
  common/character_interactions/00_poetry_interactions.txt
  common/character_interactions/00_prison_interactions.txt
  common/coat_of_arms/coat_of_arms/wc_dynasties.txt
  common/dynasty_houses/wc_dynasty_houses.txt
  common/effect_localization/wc_scourge_invasion_effects.txt
  common/game_concepts/wc_crisis_game_concepts.txt
  common/game_concepts/wc_scourge_invasion_game_concepts.txt
  common/on_action/death.txt
  common/religion/doctrines/wc_doctrines_religions.txt
  common/religion/doctrines/wc_doctrines_special.txt
  common/schemes/murder_scheme.txt
  common/scripted_character_templates/wc_historical_demonic_templates.txt
  common/scripted_effects/00_murder_effects.txt
  common/scripted_effects/00_murder_scheme_effects.txt
  common/scripted_effects/wc_being_effects.txt
  common/scripted_effects/wc_scourge_invasion_effects.txt
  common/scripted_effects/wc_vanilla_effects.txt
  common/scripted_effects/wc_war_effects.txt
  common/scripted_modifiers/00_hostile_scheme_scripted_modifiers.txt
  common/scripted_modifiers/00_religion_scripted_modifiers.txt
  common/scripted_relations/00_scripted_relations.txt
  common/scripted_triggers/00_courtier_guest_management_triggers.txt
  common/scripted_triggers/00_interaction_triggers.txt
  common/scripted_triggers/00_war_and_peace_triggers.txt
  common/scripted_triggers/wc_crisis_triggers.txt
  common/scripted_triggers/wc_scourge_invasion_triggers.txt
  common/scripted_triggers/wc_vanilla_triggers.txt
  common/secret_types/00_secret_types.txt
  common/story_cycles/wc_story_cycle_scourge_invasion.txt
  common/trigger_localization/wc_relation_triggers.txt
  events/scheme_events/hostile_scheme_discovery_events.txt
  events/story_cycles/wc_story_cycle_scourge_invasion_events.txt
  events/trait_specific_events/trait_specific_events.txt
  events/wc_events/wc_war_events.txt
  gfx/interface/icons/faith_doctrines/special_doctrine_legions_puppet.dds
  history/characters/10000_orc.txt
  history/characters/430000_nathrezim.txt
  localization/english/event_localization/wc_scourge_invasion_l_english.yml
  localization/english/religion/wc_core_tenets_l_english.yml
  localization/english/triggers/wc_character_triggers_l_english.yml
  localization/english/wc_character_interactions_l_english.yml
  localization/english/wc_effects_l_english.yml
  localization/english/wc_game_concepts_l_english.yml
  localization/english/wc_relations_l_english.yml
  localization/english/wc_traits_l_english.yml
  localization/german/event_localization/wc_scourge_invasion_l_german.yml
  localization/german/religion/wc_core_tenets_l_german.yml
  localization/german/wc_character_interactions_l_german.yml
  localization/german/wc_effects_l_german.yml
  localization/german/wc_game_concepts_l_german.yml
  localization/german/wc_relations_l_german.yml
  localization/german/wc_traits_l_german.yml
  localization/replace/english/wc_replacements_l_english.yml
  localization/replace/german/wc_replacements_l_german.yml
Labels: new feature :star:, localisation :page_facing_up:, localisation - german :page_facing_up:, vanilla modification :icecream:, priority critical :exclamation:

#766 Spawn Cultural Units
  common/men_at_arms_types/wc_cultural_maa_types.txt
  common/scripted_effects/wc_horde_invasion_effects.txt
  common/scripted_effects/wc_scourge_invasion_effects.txt
  events/story_cycles/wc_story_cycle_horde_invasion_events.txt
Labels: new feature :star:, priority medium :grey_exclamation:, balance :balance_scale:

#770 Rebalanced Base Caster
  common/men_at_arms_types/00_maa_types.txt
  gfx/interface/icons/regimenttypes/steamwarrior.dds
Labels: priority medium :grey_exclamation:, balance :balance_scale:

#741 5th Small Improvments
  common/game_concepts/wc_racial_game_concepts.txt
  common/genes/wc_genes_morph.txt
  common/on_action/child_birth_on_actions.txt
  common/script_values/wc_age_values.txt
  common/scripted_character_templates/00_pool_repopulation_character_templates.txt
  common/scripted_effects/00_romance_effects.txt
  common/scripted_effects/00_stress_effects.txt
  common/scripted_effects/20_health_effects.txt
  common/scripted_effects/wc_being_effects.txt
  common/scripted_effects/wc_health_effects.txt
  common/scripted_effects/wc_race_effects.txt
  common/scripted_modifiers/wc_health_modifiers.txt
  common/scripted_modifiers/wc_race_modifiers.txt
  common/scripted_triggers/20_health_triggers.txt
  common/scripted_triggers/wc_health_triggers.txt
  common/scripted_triggers/wc_portrait_triggers.txt
  common/scripted_triggers/wc_race_triggers.txt
  common/scripted_triggers/wc_vanilla_triggers.txt
  common/traits/wc_genetic_traits.txt
  common/traits/wc_infusion_traits.txt
  common/traits/wc_race_traits.txt
  events/health_events.txt
  events/trait_specific_events/trait_specific_events.txt
  events/wc_events/wc_health_events.txt
  gfx/portraits/trait_portrait_modifiers/00_trait_modifiers.txt
  gfx/portraits/trait_portrait_modifiers/wc_undead_modifier.txt
  localization/english/wc_racial_game_concepts_l_english.yml
  localization/english/wc_traits_l_english.yml
  localization/replace/english/wc_game_concepts_l_english.yml
Labels: new feature :star:, vanilla modification :icecream:, priority medium :grey_exclamation:, character designing 😶

#753 Uncommented physical traits
  history/characters/100000_vrykul.txt
  history/characters/10000_orc.txt
  history/characters/11000_dark_iron.txt
  history/characters/120000_nraqi.txt
  history/characters/140000_satyr.txt
  history/characters/150000_naga.txt
  history/characters/15000_gurubashi.txt
  history/characters/160000_quilboar.txt
  history/characters/17000_28000_bronzebeard.txt
  history/characters/180000_magnataur.txt
  history/characters/190000_taunka.txt
  history/characters/1_azerothian.txt
  history/characters/200000_farraki.txt
  history/characters/210000_tauren.txt
  history/characters/22000_wildhammer.txt
  history/characters/240000_qiraji.txt
  history/characters/270000_tolvir.txt
  history/characters/29000_gnoll.txt
  history/characters/310000_patron_characters.txt
  history/characters/320000_centaur.txt
  history/characters/330000_highborne.txt
  history/characters/340000_night_elf.txt
  history/characters/34000_murloc.txt
  history/characters/360000_eredruin.txt
  history/characters/38000_arathorian.txt
  history/characters/381000_vulpera.txt
  history/characters/390000_sethrak.txt
  history/characters/410000_dryad.txt
  history/characters/42000_high_elf.txt
  history/characters/440000_storm_giant.txt
  history/characters/44000_baradin.txt
  history/characters/46000_gilnean.txt
  history/characters/48000_tirassian.txt
  history/characters/500000_pandaren.txt
  history/characters/50000_kobold.txt
  history/characters/520000_mogu.txt
  history/characters/52000_ogre.txt
  history/characters/530000_saurok.txt
  history/characters/53000_hillsbrad.txt
  history/characters/540000_mantid.txt
  history/characters/54000_witherbark.txt
  history/characters/550000_yaungol.txt
  history/characters/57000_amani.txt
  history/characters/58000_alteraci.txt
  history/characters/59000_dalaranian.txt
  history/characters/60000_63000_lordaeronian.txt
  history/characters/6000_gurubashi.txt
  history/characters/64000_goblin.txt
  history/characters/66000_zandalari.txt
  history/characters/68000_darkspear.txt
  history/characters/75000_old_dwarven.txt
  history/characters/76000_nerubian.txt
  history/characters/80000_drakkari.txt
  history/characters/90000_pirate.txt
Labels: maintenance :wrench:, history 👑

#731 Adding perks for historical characters
  common/decisions/test_decision.txt
  common/script_values/01_dynamic_values.txt
  common/scripted_effects/wc_history_effects.txt
  events/wc_events/wc_race_events.txt
Labels: maintenance :wrench:, priority medium :grey_exclamation:, history 👑

#633 Auto selection weight fix
  common/decisions/test_decision.txt
  common/focuses/wc_lifestyle_focuses.txt
  common/focuses/wc_physical_lifestyle_focuses.txt
  common/lifestyle_perks/00_diplomacy_1_foreign_affairs_tree_perks.txt
  common/lifestyle_perks/00_diplomacy_2_majesty_tree_perks.txt
  common/lifestyle_perks/00_diplomacy_3_family_tree_perks.txt
  common/lifestyle_perks/00_intrigue_1_skulduggery_tree_perks.txt
  common/lifestyle_perks/00_intrigue_2_temptation_tree_perks.txt
  common/lifestyle_perks/00_intrigue_3_intimidation_tree_perks.txt
  common/lifestyle_perks/00_learning_1_medicine_tree_perks.txt
  common/lifestyle_perks/00_learning_2_scholarship_tree_perks.txt
  common/lifestyle_perks/00_learning_3_theology_tree_perks.txt
  common/lifestyle_perks/00_martial_1_strategy_tree_perks.txt
  common/lifestyle_perks/00_martial_2_authority_tree_perks.txt
  common/lifestyle_perks/00_martial_3_chivalry_tree_perks.txt
  common/lifestyle_perks/00_stewardship_1_wealth_tree_perks.txt
  common/lifestyle_perks/00_stewardship_2_domain_tree_perks.txt
  common/lifestyle_perks/00_stewardship_3_duty_tree_perks.txt
  common/lifestyle_perks/wc_death_magic_perks.txt
  common/lifestyle_perks/wc_disorder_magic_perks.txt
  common/lifestyle_perks/wc_elemental_air_magic_perks.txt
  common/lifestyle_perks/wc_elemental_earth_magic_perks.txt
  common/lifestyle_perks/wc_elemental_fire_magic_perks.txt
  common/lifestyle_perks/wc_elemental_water_magic_perks.txt
  common/lifestyle_perks/wc_life_magic_perks.txt
  common/lifestyle_perks/wc_light_magic_perks.txt
  common/lifestyle_perks/wc_order_magic_perks.txt
  common/lifestyle_perks/wc_physical_perks.txt
  common/lifestyle_perks/wc_shadow_magic_perks.txt
  common/script_values/01_dynamic_values.txt
  common/script_values/wc_lifestyles_physical_values.txt
  common/script_values/wc_lifestyles_values.txt
  common/scripted_triggers/00_lifestyle_triggers.txt
  common/scripted_triggers/wc_lifestyles_magic_triggers.txt
  common/scripted_triggers/wc_lifestyles_physical_triggers.txt
  common/scripted_triggers/wc_lifestyles_triggers.txt
  common/traits/wc_lifestyle_physical_traits.txt
  common/traits/wc_lifestyle_traits.txt
Labels: bug fix :hammer:, priority medium :grey_exclamation:

#760 Knowledge overflow adaptation for mod lifestyles
  common/lifestyle_perks/wc_death_magic_perks.txt
  common/lifestyle_perks/wc_disorder_magic_perks.txt
  common/lifestyle_perks/wc_elemental_air_magic_perks.txt
  common/lifestyle_perks/wc_elemental_earth_magic_perks.txt
  common/lifestyle_perks/wc_elemental_fire_magic_perks.txt
  common/lifestyle_perks/wc_elemental_water_magic_perks.txt
  common/lifestyle_perks/wc_life_magic_perks.txt
  common/lifestyle_perks/wc_light_magic_perks.txt
  common/lifestyle_perks/wc_order_magic_perks.txt
  common/lifestyle_perks/wc_shadow_magic_perks.txt
  common/on_action/lifestyles/wc_lifestyle_on_actions.txt
Labels: maintenance :wrench:, priority high :exclamation:

#772 Rework Sizes
  common/culture/innovations/wc_cultural_innovations.txt
Labels: priority medium :grey_exclamation:, balance :balance_scale:
