Repository Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2, pull requests merged in 2021-01, with the labels that each got.

#85 Cultural MaA and Factors
  common/men_at_arms_types/00_maa_types.txt
  common/script_values/00_men_at_arms_values.txt
  common/script_values/wc_men_at_arms_values.txt
  common/scripted_triggers/wc_maa_triggers.txt
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority high

#86 Blending Orcs
  common/culture/cultures/ogre.txt
  common/culture/cultures/orc.txt
  common/ethnicities/00_ethnicities_templates.txt
  common/ethnicities/wc_ethnicities_dwarven.txt
  common/ethnicities/wc_ethnicities_elven.txt
  common/ethnicities/wc_ethnicities_orcish.txt
  common/genes/01_genes_morph.txt
  common/genes/02_genes_accessories_hairstyles.txt
  common/genes/03_genes_accessories_beards.txt
  common/genes/wc_static_tusks.txt
  common/scripted_modifiers/wc_portrait_modifiers.txt
  common/scripted_triggers/00_clothing_triggers.txt
  common/scripted_triggers/wc_clothing_triggers.txt
  gfx/models/portraits/attachments/female_hair/northern/female_hair_northern_02/female_hair_northern_02.asset
  gfx/models/portraits/attachments/female_hair/steppe/female_hair_steppe_01/female_hair_steppe_01.asset
  gfx/models/portraits/attachments/female_hair/steppe/female_hair_steppe_02/female_hair_steppe_02.asset
  gfx/models/portraits/attachments/female_tusks/female_orcish_tusks_0.asset
  gfx/models/portraits/attachments/female_tusks/female_orcish_tusks_0.mesh
  gfx/models/portraits/attachments/male_beards/indian/male_beard_indian_03/male_beard_indian_03.asset
  gfx/models/portraits/attachments/male_beards/indian/male_beard_indian_03/male_beard_indian_03_no_moustaches.mesh
  gfx/models/portraits/attachments/male_beards/indian/male_beard_indian_03/male_beard_indian_03_no_moustaches_bs_fat.mesh
  gfx/models/portraits/attachments/male_beards/northern/male_beard_northern_01/male_beard_northern_01.asset
  gfx/models/portraits/attachments/male_beards/northern/male_beard_northern_01/male_beard_northern_01_no_moustaches.mesh
  gfx/models/portraits/attachments/male_beards/northern/male_beard_northern_01/male_beard_northern_01_no_moustaches_bs_fat.mesh
  gfx/models/portraits/attachments/male_beards/northern/male_beard_northern_02/male_beard_northern_02.asset
  gfx/models/portraits/attachments/male_beards/northern/male_beard_northern_02/male_beard_northern_02_no_moustaches.mesh
  gfx/models/portraits/attachments/male_beards/northern/male_beard_northern_03/male_beard_northern_03.asset
  gfx/models/portraits/attachments/male_beards/northern/male_beard_northern_03/male_beard_northern_03_no_moustaches.mesh
  gfx/models/portraits/attachments/male_beards/northern/male_beard_northern_03/male_beard_northern_03_no_moustaches_bs_fat.mesh
  gfx/models/portraits/attachments/male_hair/indian/male_hair_indian_01/male_hair_indian_01.asset
  gfx/models/portraits/attachments/male_hair/indian/male_hair_indian_02/male_hair_indian_02.asset
  gfx/models/portraits/attachments/male_hair/indian/male_hair_indian_03/male_hair_indian_03.asset
  gfx/models/portraits/attachments/male_hair/mena/male_hair_mena_01/male_hair_mena_01.asset
  gfx/models/portraits/attachments/male_hair/northern/male_hair_northern_02/male_hair_northern_02.asset
  gfx/models/portraits/attachments/male_hair/western/male_hair_western_09/male_hair_western_09.asset
  gfx/models/portraits/attachments/male_hair/western/male_hair_western_09/male_hair_western_09_ears.mesh
  gfx/models/portraits/attachments/male_tusks/male_orcish_tusks_0/male_orcish_tusks_0.asset
  gfx/models/portraits/attachments/male_tusks/male_orcish_tusks_0/male_orcish_tusks_0.mesh
  gfx/models/portraits/attachments/male_tusks/male_orcish_tusks_0/orcmalefaceupper00_00_hd.dds
  gfx/models/portraits/attachments/male_tusks/male_orcish_tusks_1/male_orcish_tusks_1.asset
  gfx/models/portraits/attachments/male_tusks/male_orcish_tusks_1/male_orcish_tusks_1.mesh
  gfx/models/portraits/female_head/blendshapes/female_bs_ear_tip_max.mesh
  gfx/models/portraits/female_head/blendshapes/female_bs_floppy_ear_length.mesh
  gfx/models/portraits/female_head/blendshapes/female_bs_mouth_tusks_max.mesh
  gfx/models/portraits/female_head/blendshapes/female_bs_nose_nostril_height_max.mesh
  gfx/models/portraits/female_head/female_head.asset
  gfx/models/portraits/male_head/blendshapes/male_bs_ear_tip_max.mesh
  gfx/models/portraits/male_head/blendshapes/male_bs_floppy_ear_length.mesh
  gfx/models/portraits/male_head/blendshapes/male_bs_mouth_tusks_max.mesh
  gfx/models/portraits/male_head/blendshapes/male_bs_nose_nostril_height_max.mesh
  gfx/models/portraits/male_head/male_head.asset
  gfx/portraits/accessories/beards.txt
  gfx/portraits/accessories/wc_tusks.txt
  gfx/portraits/portrait_modifiers/01_cloaks.txt
  gfx/portraits/portrait_modifiers/01_clothes.txt
  localization/english/wc_portraits_l_english.yml
Labels: :art: graphics :paintbrush:, :grey_exclamation: priority medium

#91 Basic + Capital Development
  history/titles/00_wc_other_titles.txt
  history/titles/k_ashenvale.txt
  history/titles/k_azshara.txt
  history/titles/k_azuremyst.txt
  history/titles/k_barrens.txt
  history/titles/k_black_morass.txt
  history/titles/k_booty_bay.txt
  history/titles/k_borean_tundra.txt
  history/titles/k_crystalsong_forest.txt
  history/titles/k_darkshore.txt
  history/titles/k_desolace.txt
  history/titles/k_dragonblight.txt
  history/titles/k_draktharon.txt
  history/titles/k_dun_niffelem.txt
  history/titles/k_dustwallow.txt
  history/titles/k_feralas.txt
  history/titles/k_grizzly_hills.txt
  history/titles/k_gurubashi.txt
  history/titles/k_halfhill.txt
  history/titles/k_hillsbrad.txt
  history/titles/k_hinterlands.txt
  history/titles/k_howling_fjord.txt
  history/titles/k_icecrown.txt
  history/titles/k_isle_of_conquest.txt
  history/titles/k_kezan.txt
  history/titles/k_krasarang.txt
  history/titles/k_kun_lai.txt
  history/titles/k_kyparqov.txt
  history/titles/k_lei_dao.txt
  history/titles/k_moonglade.txt
  history/titles/k_morlosaran.txt
  history/titles/k_neferset.txt
  history/titles/k_orsis.txt
  history/titles/k_plunder_isle.txt
  history/titles/k_ramkahen.txt
  history/titles/k_sheilun.txt
  history/titles/k_sholazar_basin.txt
  history/titles/k_silithus.txt
  history/titles/k_south_islands.txt
  history/titles/k_stonetalon.txt
  history/titles/k_storm_peaks.txt
  history/titles/k_stormwind.txt
  history/titles/k_stratholme.txt
  history/titles/k_tanaris.txt
  history/titles/k_tel_abim.txt
  history/titles/k_thousand_needles.txt
  history/titles/k_townlong.txt
  history/titles/k_ulduar.txt
  history/titles/k_vermillion.txt
  history/titles/k_wetlands.txt
  history/titles/k_winterspring.txt
  history/titles/k_yulin.txt
  history/titles/k_zouchin.txt
  history/titles/wc_development_history.txt
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority critical

#95 1st Bug Crusade
  common/bookmark_portraits/bookmark_test_character.txt
  common/bookmark_portraits/historical_export_easteregg_nikolaos_kaltsogiannis.txt
  common/bookmark_portraits/historical_export_easteregg_pontus_olofsson.txt
  common/culture/cultures/000_test_culture.txt
  common/dynasties/test_dynasties.txt
  common/ethnicities/wc_ethnicities_dwarven.txt
  common/ethnicities/wc_ethnicities_elven.txt
  common/flavorization/wc_title_holders.txt
  common/landed_titles/wc_religious_titles.txt
  common/men_at_arms_types/00_holy_order_maa_types.txt
  common/religion/holy_sites/wc_holy_sites.txt
  common/schemes/convert_to_witchcraft_scheme.txt
  common/scripted_modifiers/wc_portrait_modifiers.txt
  common/scripted_triggers/wc_motto_triggers.txt
  events/wc_events/wc_race_events.txt
  history/characters/000_test_characters.txt
  history/characters/10000_orc.txt
  history/characters/11000_dark_iron.txt
  history/characters/150000_naga.txt
  history/characters/16000_gnome.txt
  history/characters/1_azerothian.txt
  history/characters/200000_farraki.txt
  history/characters/210000_tauren.txt
  history/characters/29000_gnoll.txt
  history/characters/310000_patron_characters.txt
  history/characters/330000_highborne.txt
  history/characters/340000_night_elf.txt
  history/characters/34000_murloc.txt
  history/characters/360000_eredruin.txt
  history/characters/38000_arathorian.txt
  history/characters/42000_high_elf.txt
  history/characters/430000_nathrezim.txt
  history/characters/46000_gilnean.txt
  history/characters/48000_tirassian.txt
  history/characters/500000_pandaren.txt
  history/characters/52000_ogre.txt
  history/characters/57000_amani.txt
  history/characters/58000_alteraci.txt
  history/characters/59000_dalaranian.txt
  history/characters/60000_63000_lordaeronian.txt
  history/characters/62000_dragon.txt
  history/characters/64000_goblin.txt
  history/characters/66000_zandalari.txt
  history/characters/68000_darkspear.txt
  history/characters/80000_drakkari.txt
  history/titles/wc_development_history.txt
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#107 Added vanilla gui files
  gui/frontend_main.gui
  gui/hud.gui
  gui/window_character.gui
Labels: :grey_exclamation: priority medium, :hammer: maintenance :wrench:

#108 Debug GFX & #94
  gfx/interface/_debug/errorhoof.dds
  gfx/interface/frontend/ck3_coop_logo.dds
  gui/frontend_main.gui
  localization/replace/english/wc_replacements_l_english.yml
Labels: :art: 2D graphics :paintbrush:, :grey_exclamation: priority low

#98 Sorcerer trait adaptation
  common/courtier_guest_management/guest_management.txt
  common/customizable_localization/00_ruler_transition_loc.txt
  common/decisions/80_major_decisions.txt
  common/dynasty_perks/00_dynasty_perks.txt
  common/on_action/child_birth_on_actions.txt
  common/script_values/01_dynamic_values.txt
  common/scripted_character_templates/00_peasants_template.txt
  common/scripted_character_templates/00_pool_repopulation_character_templates.txt
  common/scripted_character_templates/00_soldier_character_templates.txt
  common/scripted_effects/00_courtier_guest_management_effects.txt
  common/scripted_modifiers/00_elective_successions_scripted_modifiers.txt
  common/scripted_triggers/00_religious_triggers.txt
  common/scripted_triggers/wc_elective_triggers.txt
  common/traits/wc_genetic_traits.txt
  events/birth_events.txt
  events/courtier_guest_management_events/courtier_guest_management_events.txt
  events/education_and_childhood/child_personality_events.txt
  events/lifestyles/governance_lifestyle/stewardship_general_events.txt
  events/scheme_events/court_scheme/court_scheme_ongoing_events.txt
  gfx/interface/icons/traits/magic_bad_1.dds
  gfx/interface/icons/traits/magic_bad_2.dds
  gfx/interface/icons/traits/magic_bad_3.dds
  gfx/interface/icons/traits/magic_bad_noninheritable.dds
  gfx/interface/icons/traits/magic_good_1.dds
  gfx/interface/icons/traits/magic_good_2.dds
  gfx/interface/icons/traits/magic_good_3.dds
  gfx/interface/icons/traits/magic_good_noninheritable.dds
  history/characters/10000_orc.txt
  history/characters/11000_dark_iron.txt
  history/characters/15000_gurubashi.txt
  history/characters/1_azerothian.txt
  history/characters/29000_gnoll.txt
  history/characters/310000_patron_characters.txt
  history/characters/340000_night_elf.txt
  history/characters/38000_arathorian.txt
  history/characters/42000_high_elf.txt
  history/characters/48000_tirassian.txt
  history/characters/52000_ogre.txt
  history/characters/59000_dalaranian.txt
  history/characters/60000_63000_lordaeronian.txt
  history/characters/68000_darkspear.txt
  localization/english/wc_general_l_english.yml
  localization/english/wc_traits_l_english.yml
Labels: :grey_exclamation: priority low, :star: new feature :new:
