Repository Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2, pull requests merged in 2021-07, with the labels that each got.

#411 Dark Portal Raiders
  common/on_action/wc_draenor_on_actions.txt
  common/script_values/01_dlc_fp1_script_values.txt
  common/script_values/wc_war_values.txt
  common/scripted_character_templates/wc_draenor_templates.txt
  common/scripted_effects/wc_fp1_effects.txt
  common/scripted_triggers/wc_fp1_triggers.txt
  events/dlc/fp1/fp1_scandinavian_adventurer_events.txt
  events/dlc/fp1/fp1_trade_events.txt
  events/wc_events/wc_draenor_events.txt
  localization/english/event_localization/wc_draenor_events_l_english.yml
  localization/english/wc_wars_l_english.yml
  localization/replace/english/wc_dlc_fp1_l_english.yml
  localization/replace/english/wc_replacements_l_english.yml
  map_data/geographical_region.txt
Labels: :grey_exclamation: priority medium, :ice_cream: vanilla modification :icecream:, :page_facing_up: localisation :pen:, :star:new feature:new:

#503 Satyr, Dryad Immortality
  common/traits/wc_race_traits.txt
Labels: bug fix :hammer:, character designing 😶, priority critical :exclamation:

#514 Orgrim now has appropriate claims & Bronzebeard brothers are no longer half brothers
  history/characters/100000_vrykul.txt
  history/characters/10000_orc.txt
  history/characters/11000_dark_iron.txt
  history/characters/16000_gnome.txt
  history/characters/17000_28000_bronzebeard.txt
  history/characters/1_azerothian.txt
  history/characters/22000_wildhammer.txt
  history/characters/29000_gnoll.txt
  history/characters/42000_high_elf.txt
  history/characters/57000_amani.txt
  history/characters/58000_alteraci.txt
  history/characters/60000_63000_lordaeronian.txt
Labels: bug fix :hammer:, priority critical :exclamation:

#513 Menopause and Andropause
  common/on_action/game_start.txt
  common/on_action/health_on_actions.txt
  common/script_values/wc_age_values.txt
  common/scripted_effects/wc_race_effects.txt
  common/scripted_modifiers/00_marriage_scripted_modifiers.txt
  common/scripted_triggers/wc_health_triggers.txt
  common/traits/00_traits.txt
  common/traits/wc_race_traits.txt
  events/wc_events/wc_health_events.txt
  history/characters/62000_dragon.txt
  localization/english/wc_traits_l_english.yml
  localization/french/wc_traits_l_french.yml
  localization/german/wc_traits_l_german.yml
  localization/spanish/wc_traits_l_spanish.yml
Labels: balance :balance_scale:, priority critical :exclamation:

#501 Limited Draenor Levies
  common/scripted_effects/wc_fp1_effects.txt
Labels: balance :balance_scale:, priority high :exclamation:

#517 Mac Shading
  gfx/FX/jomini/portrait.shader
Labels: bug fix :hammer:, maintenance :wrench:, priority critical :exclamation:

#162 Mana
  common/game_concepts/wc_magic_concepts.txt
  common/lifestyle_perks/wc_death_magic_perks.txt
  common/lifestyle_perks/wc_disorder_magic_perks.txt
  common/lifestyle_perks/wc_elemental_air_magic_perks.txt
  common/lifestyle_perks/wc_elemental_earth_magic_perks.txt
  common/lifestyle_perks/wc_elemental_fire_magic_perks.txt
  common/lifestyle_perks/wc_elemental_water_magic_perks.txt
  common/lifestyle_perks/wc_life_magic_perks.txt
  common/lifestyle_perks/wc_light_magic_perks.txt
  common/lifestyle_perks/wc_order_magic_perks.txt
  common/lifestyle_perks/wc_shadow_magic_perks.txt
  common/modifiers/wc_mana_modifiers.txt
  common/on_action/child_birth_on_actions.txt
  common/on_action/wc_mana_on_actions.txt
  common/script_values/wc_mana_values.txt
  common/scripted_effects/00_courtier_guest_management_effects.txt
  common/scripted_effects/wc_mana_effects.txt
  common/scripted_effects/wc_race_effects.txt
  common/scripted_guis/wc_mana_guis.txt
  common/scripted_triggers/wc_year_triggers.txt
  common/traits/wc_genetic_traits.txt
  events/birth_events.txt
  events/education_and_childhood/child_personality_events.txt
  gfx/interface/icons/currencies/icon_empty_mana_crystal.dds
  gfx/interface/icons/currencies/icon_full_mana_crystal.dds
  gfx/interface/icons/currencies/icon_half_mana_crystal.dds
  gfx/interface/icons/currencies/icon_stat_mana_crystal.dds
  gui/hud.gui
  gui/warcraft/wc_shared.gui
  gui/wc_texticons.gui
  gui/window_character.gui
  gui/window_character_lifestyle.gui
  localization/english/gui/wc_mana_l_english.yml
  localization/english/modifiers/wc_modifiers_mana_l_english.yml
  localization/english/wc_game_concepts_magic_l_english.yml
  localization/english/wc_general_l_english.yml
  localization/english/wc_traits_l_english.yml
Labels: interface 👁‍🗨, new feature :star:, priority medium :grey_exclamation:

#519 scourge Coa
  common/coat_of_arms/coat_of_arms/00_wc_landed_titles.txt
  common/coat_of_arms/coat_of_arms/wc_random_templates.txt
  common/coat_of_arms/template_lists/coa_templates.txt
  common/coat_of_arms/template_lists/colored_emblem_lists.txt
  common/coat_of_arms/template_lists/wc_colored_emblem_lists.txt
  gfx/coat_of_arms/colored_emblems/ce_scourge.dds
Labels: 2D graphics :paintbrush:, priority medium :grey_exclamation:

#520 History Names
  common/culture/cultures/human.txt
  history/characters/200000_farraki.txt
  history/characters/29000_gnoll.txt
  history/characters/310000_patron_characters.txt
  history/characters/32000_frostmane.txt
  history/characters/400000_titan.txt
  history/characters/80000_drakkari.txt
  localization/english/names/wc_character_names_l_english.yml
  localization/german/names/wc_character_names_l_german.yml
Labels: bug fix :hammer:, localisation :page_facing_up:, priority critical :exclamation:

#515 Fixed immortal_age
  history/characters/100000_vrykul.txt
  history/characters/11000_dark_iron.txt
  history/characters/140000_satyr.txt
  history/characters/150000_naga.txt
  history/characters/16000_gnome.txt
  history/characters/17000_28000_bronzebeard.txt
  history/characters/22000_wildhammer.txt
  history/characters/290000_frozen_giant.txt
  history/characters/300000_frostborn.txt
  history/characters/310000_patron_characters.txt
  history/characters/330000_highborne.txt
  history/characters/340000_night_elf.txt
  history/characters/380000_frostnymph.txt
  history/characters/410000_dryad.txt
  history/characters/42000_high_elf.txt
  history/characters/430000_nathrezim.txt
  history/characters/440000_storm_giant.txt
  history/characters/450000_sayaadi.txt
  history/characters/460000_drust.txt
  history/characters/60000_63000_lordaeronian.txt
Labels: bug fix :hammer:, history 👑, priority critical :exclamation:

#433 Elmariuso-flags-1
  common/coat_of_arms/coat_of_arms/00_wc_landed_titles.txt
  common/coat_of_arms/coat_of_arms/wc_dynasties.txt
  common/coat_of_arms/coat_of_arms/wc_religious_titles.txt
  common/named_colors/wc_colors.txt
  gfx/coat_of_arms/colored_emblems/ce_blacktoothgrin.dds
  gfx/coat_of_arms/colored_emblems/ce_blood_hakkar.dds
  gfx/coat_of_arms/colored_emblems/ce_holy_light.dds
  gfx/coat_of_arms/colored_emblems/ce_laughing_skull.dds
  gfx/coat_of_arms/colored_emblems/ce_shadowmoon.dds
  gfx/coat_of_arms/colored_emblems/ce_shattered_hand.dds
  gfx/coat_of_arms/colored_emblems/ce_warsong.dds
Labels: 2D graphics :paintbrush:, lore :books:, priority medium :grey_exclamation:

#524 Sylvanas DNA Fix
  common/dna_data/wc_elf_dna.txt
Labels: character designing 😶, suggestion :question:

#528 Make Stormwind vassal feudal
  common/dynasties/6000_murloc.txt
  history/characters/34000_murloc.txt
  history/titles/00_k_stormwind.txt
Labels: bug :beetle:, history 👑, priority critical :exclamation:

#531 laughting_skull Typo
  common/culture/cultures/orc.txt
  common/dynasties/2000_orc.txt
  common/scripted_character_templates/wc_draenor_templates.txt
  localization/english/culture/wc_cultures_l_english.yml
  localization/french/culture/wc_cultures_l_french.yml
  localization/german/culture/wc_cultures_l_german.yml
Labels: maintenance :wrench:, priority critical :exclamation:

#526 try_to_set_race_effect Memory Leak
  common/casus_belli_types/00_religious_war.txt
  common/on_action/child_birth_on_actions.txt
  common/on_action/court_maintenance_on_actions.txt
  common/on_action/courtier_guest_management_on_actions.txt
  common/on_action/game_start.txt
  common/on_action/title_on_actions.txt
  common/scripted_character_templates/00_foundling_templates.txt
  common/scripted_character_templates/00_holy_order_character_templates.txt
  common/scripted_character_templates/00_lifestyle_friend_templates.txt
  common/scripted_character_templates/00_mystic_templates.txt
  common/scripted_character_templates/00_officials_templates.txt
  common/scripted_character_templates/00_peasant_faction_leader_template.txt
  common/scripted_character_templates/00_peasant_leader_templates.txt
  common/scripted_character_templates/00_peasants_template.txt
  common/scripted_character_templates/00_pool_repopulation_character_templates.txt
  common/scripted_character_templates/00_priest_character_template.txt
  common/scripted_character_templates/00_saharan_nomad_template.txt
  common/scripted_character_templates/00_scholar_template.txt
  common/scripted_character_templates/00_soldier_character_templates.txt
  common/scripted_character_templates/01_fp1_character_templates.txt
  common/scripted_character_templates/wc_draenor_templates.txt
  common/scripted_effects/00_councillor_effects.txt
  common/scripted_effects/00_faction_effects.txt
  common/scripted_effects/00_game_rule_effects.txt
  common/scripted_effects/00_stewardship_lifestyle_effects.txt
  common/scripted_effects/wc_race_effects.txt
  events/activities/hunt_activity/hunt_events.txt
  events/activities/pilgrimage_activity/pilgrimage_events.txt
  events/dlc/fp1/fp1_other_decision_events.txt
  events/government_events/clan_events.txt
  events/health_events.txt
  events/lifestyles/governance_lifestyle/stewardship_general_events.txt
  events/lifestyles/governance_lifestyle/stewardship_wealth_events.txt
  events/lifestyles/intrigue_lifestyle/intrigue_scheming_events.txt
  events/lifestyles/scholarship_lifestyle/learning_medicine_events.txt
  events/lifestyles/warfare_lifestyle/martial_authority_events.txt
  events/lifestyles/warfare_lifestyle/martial_chivalry_events.txt
  events/lifestyles/warfare_lifestyle/martial_strategy_events.txt
  events/religion_events/faith_creation_events.txt
  events/story_cycles/peasant_affair/story_cycle_peasant_affair_events.txt
  events/stress_events/stress_threshold_prison_events.txt
  events/stress_events/stress_threshold_special_events.txt
  events/wc_events/wc_race_events.txt
Labels: maintenance :wrench:, priority critical :exclamation:

#507 87 mercenary names
  common/culture/cultures/ancient.txt
  common/culture/cultures/aqir.txt
  common/culture/cultures/arakkoa.txt
  common/culture/cultures/centaur.txt
  common/culture/cultures/demonic.txt
  common/culture/cultures/draenei.txt
  common/culture/cultures/dragon.txt
  common/culture/cultures/dryad.txt
  common/culture/cultures/dwarf.txt
  common/culture/cultures/elemental.txt
  common/culture/cultures/elf.txt
  common/culture/cultures/furbolg.txt
  common/culture/cultures/gnoll.txt
  common/culture/cultures/gnome.txt
  common/culture/cultures/goblin.txt
  common/culture/cultures/harpy.txt
  common/culture/cultures/hozen.txt
  common/culture/cultures/human.txt
  common/culture/cultures/jinyu.txt
  common/culture/cultures/kobold.txt
  common/culture/cultures/magnataur.txt
  common/culture/cultures/mogu.txt
  common/culture/cultures/murloc.txt
  common/culture/cultures/ogre.txt
  common/culture/cultures/orc.txt
  common/culture/cultures/pandaren.txt
  common/culture/cultures/pygmy.txt
  common/culture/cultures/quilboar.txt
  common/culture/cultures/sethrak.txt
  common/culture/cultures/shathyar.txt
  common/culture/cultures/tauren.txt
  common/culture/cultures/titanforged.txt
  common/culture/cultures/tortollan.txt
  common/culture/cultures/trogg.txt
  common/culture/cultures/troll.txt
  common/culture/cultures/tuskarr.txt
  common/culture/cultures/undead.txt
  common/culture/cultures/vrykul.txt
  common/culture/cultures/vulpera.txt
  localization/english/wc_mercenaries_l_english.yml
Labels: localisation :page_facing_up:, lore :books:, priority high :exclamation:

#529 Magic Infusion Refactoring
  common/script_values/wc_gui_infusion_values.txt
  common/script_values/wc_infusion_values.txt
  common/script_values/wc_magic_infusion_values.txt
  common/scripted_effects/wc_magic_effects.txt
  common/scripted_guis/wc_infusion_scripted_gui.txt
  gfx/interface/colors/green.dds
  gfx/interface/hud/hud_infusion_glow_gold.dds
  gfx/interface/hud/hud_infusion_glow_green.dds
  gfx/interface/hud/hud_infusion_glow_purple.dds
  gfx/interface/icons/infusion/icon_arcane_fel_level.dds
  gfx/interface/icons/infusion/icon_light_void_level.dds
  gfx/interface/skinned/hud_infusion_bg.dds
  gfx/interface/skinned/hud_infusion_single_bg.dds
  gui/hud.gui
Labels: interface 👁‍🗨, maintenance :wrench:, priority critical :exclamation:

#400 Character Design by NovelConcept
  common/dna_data/wc_dwarf_dna.txt
  common/dna_data/wc_human_dna.txt
  common/dna_data/wc_orc_dna.txt
  common/scripted_triggers/wc_his_character_triggers.txt
  gfx/portraits/portrait_modifiers/50_beards_scripted_characters.txt
  gfx/portraits/portrait_modifiers/50_hairstyles_scripted_characters.txt
  gfx/portraits/portrait_modifiers/wc_scripted_appearances.txt
  history/characters/10000_orc.txt
  history/characters/11000_dark_iron.txt
  history/characters/17000_28000_bronzebeard.txt
  history/characters/1_azerothian.txt
  history/characters/22000_wildhammer.txt
  history/characters/60000_63000_lordaeronian.txt
Labels: character designing 😶, priority high :exclamation:

#525 Draenei Clothing
  common/culture/cultures/demonic.txt
  common/culture/cultures/draenei.txt
  common/genes/05_genes_special_accessories_clothes.txt
  common/scripted_triggers/wc_clothing_triggers.txt
  gfx/portraits/portrait_modifiers/01_clothes.txt
  gfx/portraits/portrait_modifiers/01_headgear.txt
  gfx/portraits/portrait_modifiers/01_legwear.txt
Labels: character designing 😶, lore :books:, priority critical :exclamation:

#535 Holy Order Debug
  common/decisions/00_holy_order_decisions.txt
  common/decisions/wc_debug_decision.txt
  localization/english/wc_debug_l_english.yml
Labels: maintenance :wrench:, new feature :star:, priority critical :exclamation:

#537 Being Traits
  common/customizable_localization/00_insult_custom_loc.txt
  common/opinion_modifiers/wc_doctrinal_crime_opinions.txt
  common/religion/doctrines/wc_doctrines_magic.txt
  common/script_values/wc_age_values.txt
  common/scripted_effects/wc_being_effects.txt
  common/scripted_effects/wc_race_effects.txt
  common/scripted_triggers/00_religious_triggers.txt
  common/scripted_triggers/wc_being_triggers.txt
  common/scripted_triggers/wc_his_character_triggers.txt
  common/traits/wc_infusion_traits.txt
  common/traits/wc_race_traits.txt
  common/traits/wc_undead_trait.txt
  gfx/interface/icons/traits/being_demon.dds
  gfx/interface/icons/traits/being_life.dds
  gfx/interface/icons/traits/being_light.dds
  gfx/interface/icons/traits/being_order.dds
  gfx/interface/icons/traits/being_void.dds
  history/characters/380000_frostnymph.txt
  history/characters/400000_titan.txt
  history/characters/410000_dryad.txt
  history/characters/420000_ancients.txt
  localization/english/custom_localization/wc_insult_custom_loc_l_english.yml
  localization/english/wc_traits_l_english.yml
Labels: localisation :page_facing_up:, lore :books:, new feature :star:, priority critical :exclamation:

#545 Baldness Gene
  common/dna_data/wc_dwarf_dna.txt
  common/dna_data/wc_orc_dna.txt
  common/ethnicities/00_ethnicities_templates.txt
  common/ethnicities/wc_ethnicities_draenei.txt
  common/genes/01_genes_morph.txt
  common/genes/03_genes_special_accessories_hairstyles.txt
  common/genes/wc_genes_horns.txt
  gfx/models/portraits/attachments/male_hair/indian/male_hair_indian_01/male_hair_indian_01.asset
  gfx/models/portraits/attachments/male_hair/indian/male_hair_indian_01/male_hair_indian_01_balding.mesh
  gfx/models/portraits/attachments/male_hair/indian/male_hair_indian_01/male_hair_indian_01_cap.mesh
  gfx/models/portraits/attachments/male_hair/indian/male_hair_indian_01/male_hair_indian_01_crown.mesh
  gfx/models/portraits/attachments/male_hair/indian/male_hair_indian_01_wc/male_hair_indian_01_wc.asset
  gfx/models/portraits/attachments/male_hair/indian/male_hair_indian_01_wc/male_hair_indian_01_wc.mesh
  gfx/models/portraits/attachments/male_hair/indian/male_hair_indian_03/male_hair_indian_03.asset
  gfx/models/portraits/attachments/male_hair/indian/male_hair_indian_03/male_hair_indian_03_balding.mesh
  gfx/models/portraits/attachments/male_hair/indian/male_hair_indian_03/male_hair_indian_03_cap.mesh
  gfx/models/portraits/attachments/male_hair/indian/male_hair_indian_03/male_hair_indian_03_crown.mesh
  gfx/models/portraits/attachments/male_hair/indian/male_hair_indian_03_wc/male_hair_indian_03_wc.asset
  gfx/models/portraits/attachments/male_hair/indian/male_hair_indian_03_wc/male_hair_indian_03_wc.mesh
  gfx/models/portraits/male_head/male_head.asset
  gfx/portraits/accessories/hairstyles.txt
  gfx/portraits/accessories/wc_hairstyles.txt
  gfx/portraits/portrait_modifiers/50_hairstyles_scripted_characters.txt
  gfx/portraits/portrait_modifiers/wc_baldness.txt
  localization/english/wc_portraits_l_english.yml
  localization/replace/english/wc_replacements_l_english.yml
Labels: 3D graphics :triangular_ruler:, character designing 😶, priority critical :exclamation:

#532 88 holy order names
  common/decisions/00_holy_order_decisions.txt
  common/decisions/wc_debug_decision.txt
  common/religion/religions/air_group.txt
  common/religion/religions/ape_group.txt
  common/religion/religions/arcane_group.txt
  common/religion/religions/avian_group.txt
  common/religion/religions/daradorism.txt
  common/religion/religions/deathbringer.txt
  common/religion/religions/doombringer.txt
  common/religion/religions/druidism_group.txt
  common/religion/religions/earth_group.txt
  common/religion/religions/fel_group.txt
  common/religion/religions/fire_group.txt
  common/religion/religions/grond_group.txt
  common/religion/religions/light_group.txt
  common/religion/religions/lizard_group.txt
  common/religion/religions/loa_group.txt
  common/religion/religions/naarism.txt
  common/religion/religions/necromancy_group.txt
  common/religion/religions/nerub_group.txt
  common/religion/religions/pandaren_religion_group.txt
  common/religion/religions/secular_group.txt
  common/religion/religions/shamanism_group.txt
  common/religion/religions/shathgral_group.txt
  common/religion/religions/titanic_group.txt
  common/religion/religions/void_group.txt
  common/religion/religions/water_group.txt
  localization/english/wc_debug_l_english.yml
  localization/english/wc_holy_orders_l_english.yml
  localization/replace/english/wc_holy_orders_l_english.yml
Labels: localisation :page_facing_up:, lore :books:

#544 Blood Troll Flavorization
  common/flavorization/wc_title_holders.txt
  localization/english/culture/wc_culture_titles_l_english.yml
Labels: localisation :page_facing_up:, lore :books:, new feature :star:, priority low :grey_exclamation:, suggestion :question:

#548 Horns Clipping with Hairs
  common/ethnicities/wc_ethnicities_draenei.txt
  common/genes/01_genes_morph.txt
  gfx/portraits/portrait_modifiers/wc_baldness.txt
Labels: 3D graphics :triangular_ruler:, bug fix :hammer:, priority critical :exclamation:

#538 Vanity/Easter Egg Characters
  common/coat_of_arms/coat_of_arms/wc_easter_egg_dynasties.txt
  common/dna_data/wc_easter_egg_dna.txt
  common/dna_data/wc_easteregg_dna.txt
  common/dynasties/wc_easter_egg_dynasties.txt
  common/scripted_triggers/wc_his_character_triggers.txt
  gfx/portraits/portrait_modifiers/50_beards_scripted_characters.txt
  gfx/portraits/portrait_modifiers/50_hairstyles_scripted_characters.txt
  history/characters/wc_easteregg_characters.txt
  localization/english/dynasties/wc_dynasty_names_l_english.yml
  localization/english/names/wc_character_names_l_english.yml
Labels: character designing 😶, history 👑, priority low :grey_exclamation:

#553 Baldness Crash
  gfx/models/portraits/female_head/female_head.asset
Labels: bug fix :hammer:, character designing 😶, priority critical :exclamation:

#555 decal_apply_order is Back
  common/genes/wc_gene_facial_markings.txt
  gfx/models/portraits/decals/bloodtroll_tattoos/decal_bloodtroll_bodypaint_01.dds
  gfx/models/portraits/decals/bloodtroll_tattoos/decal_bloodtroll_tattoo_01.dds
  gfx/models/portraits/decals/bloodtroll_tattoos/decal_bloodtroll_tattoo_02.dds
  gfx/models/portraits/decals/bloodtroll_tattoos/decal_bloodtroll_tattoo_03.dds
  gfx/models/portraits/decals/bloodtroll_tattoos/decal_bloodtroll_tattoo_04.dds
  gfx/models/portraits/decals/bloodtroll_tattoos/decal_bloodtroll_tattoo_05.dds
  gfx/models/portraits/decals/bloodtroll_tattoos/decal_bloodtroll_tattoo_06.dds
  gfx/models/portraits/decals/bloodtroll_tattoos/decal_bloodtroll_tattoo_07.dds
  gfx/models/portraits/decals/bloodtroll_tattoos/decal_bloodtroll_tattoo_08.dds
  gfx/models/portraits/decals/bloodtroll_tattoos/decal_bloodtroll_tattoo_09.dds
  gfx/models/portraits/decals/bloodtroll_tattoos/decal_bloodtroll_tattoo_10.dds
  gfx/models/portraits/decals/bloodtroll_tattoos/decal_bloodtroll_tattoo_11.dds
  gfx/models/portraits/decals/bloodtroll_tattoos/decal_bloodtroll_tattoo_12.dds
Labels: 2D graphics :paintbrush:, character designing 😶, maintenance :wrench:, priority critical :exclamation:

#534 8th Bug Crusade
  common/culture/cultures/human.txt
  common/dna_data/wc_dwarf_dna.txt
  common/dna_data/wc_easter_egg_dna.txt
  common/dna_data/wc_elf_dna.txt
  common/dna_data/wc_human_dna.txt
  common/dna_data/wc_nightelf_dna.txt
  common/ethnicities/00_ethnicities_templates.txt
  common/ethnicities/wc_ethnicities_ogre.txt
  common/genes/01_genes_morph.txt
  common/on_action/title_on_actions.txt
  common/religion/doctrines/wc_doctrines_magic.txt
  common/script_values/wc_age_values.txt
  common/scripted_triggers/wc_his_character_triggers.txt
  gfx/FX/jomini/portrait.shader
  history/characters/320000_centaur.txt
  history/characters/76000_nerubian.txt
  history/characters/90000_pirate.txt
  history/titles/000_wc_religious_head_titles.txt
  history/titles/00_k_wintergarde.txt
  localization/english/names/wc_character_names_l_english.yml
  localization/english/religion/wc_gods_and_titles_l_english.yml
  localization/english/wc_traits_l_english.yml
  localization/german/names/wc_character_names_l_german.yml
Labels: bug fix :hammer:, priority critical :exclamation:

#562 Skin Shader Without Decals
  gfx/FX/jomini/portrait.shader
  gfx/models/portraits/attachments/female_hooves/female_hooves_draenei_0/female_hooves_draenei_0.asset
  gfx/models/portraits/attachments/female_horns/female_draenei_horns_0/female_draenei_horns_0.asset
  gfx/models/portraits/attachments/female_horns/female_draenei_horns_1/female_draenei_horns_1.asset
  gfx/models/portraits/attachments/female_horns/female_draenei_horns_10/wc_female_draenei_horns_10.asset
  gfx/models/portraits/attachments/female_horns/female_draenei_horns_11/wc_female_draenei_horns_11.asset
  gfx/models/portraits/attachments/female_horns/female_draenei_horns_2/female_draenei_horns_2.asset
  gfx/models/portraits/attachments/female_horns/female_draenei_horns_3/wc_female_draenei_horns_3.asset
  gfx/models/portraits/attachments/female_horns/female_draenei_horns_4/wc_female_draenei_horns_4.asset
  gfx/models/portraits/attachments/female_horns/female_draenei_horns_5/wc_female_draenei_horns_5.asset
  gfx/models/portraits/attachments/female_horns/female_draenei_horns_6/wc_female_draenei_horns_6.asset
  gfx/models/portraits/attachments/female_horns/female_draenei_horns_7/wc_female_draenei_horns_7.asset
  gfx/models/portraits/attachments/female_horns/female_draenei_horns_8/wc_female_draenei_horns_8.asset
  gfx/models/portraits/attachments/female_horns/female_draenei_horns_9/wc_female_draenei_horns_9.asset
  gfx/models/portraits/attachments/female_tail/female_tail_draenei_0/female_tail_draenei_0.asset
  gfx/models/portraits/attachments/female_tendrils/female_tendrils_draenei_0/female_tendrils_draenei_0.asset
  gfx/models/portraits/attachments/male_hooves/male_hooves_draenei_0/male_hooves_draenei_0.asset
  gfx/models/portraits/attachments/male_horns/male_horns_draenei_0/male_horns_draenei_0.asset
  gfx/models/portraits/attachments/male_horns/male_horns_draenei_1/male_horns_draenei_1.asset
  gfx/models/portraits/attachments/male_horns/male_horns_draenei_10/wc_male_horns_draenei_10.asset
  gfx/models/portraits/attachments/male_horns/male_horns_draenei_11/wc_male_horns_draenei_11.asset
  gfx/models/portraits/attachments/male_horns/male_horns_draenei_12/wc_male_horns_draenei_12.asset
  gfx/models/portraits/attachments/male_horns/male_horns_draenei_13/wc_male_horns_draenei_13.asset
  gfx/models/portraits/attachments/male_horns/male_horns_draenei_14/wc_male_horns_draenei_14.asset
  gfx/models/portraits/attachments/male_horns/male_horns_draenei_15/wc_male_horns_draenei_15.asset
  gfx/models/portraits/attachments/male_horns/male_horns_draenei_16/wc_male_horns_draenei_16.asset
  gfx/models/portraits/attachments/male_horns/male_horns_draenei_17/wc_male_horns_draenei_17.asset
  gfx/models/portraits/attachments/male_horns/male_horns_draenei_19/wc_male_horns_draenei_19.asset
  gfx/models/portraits/attachments/male_horns/male_horns_draenei_2/male_horns_draenei_2.asset
  gfx/models/portraits/attachments/male_horns/male_horns_draenei_20/wc_male_horns_draenei_20.asset
  gfx/models/portraits/attachments/male_horns/male_horns_draenei_21/wc_male_horns_draenei_21.asset
  gfx/models/portraits/attachments/male_horns/male_horns_draenei_3/wc_male_horns_draenei_3.asset
  gfx/models/portraits/attachments/male_horns/male_horns_draenei_4/wc_male_horns_draenei_4.asset
  gfx/models/portraits/attachments/male_horns/male_horns_draenei_5/wc_male_horns_draenei_5.asset
  gfx/models/portraits/attachments/male_horns/male_horns_draenei_7/wc_male_horns_draenei_7.asset
  gfx/models/portraits/attachments/male_horns/male_horns_draenei_8/wc_male_horns_draenei_8.asset
  gfx/models/portraits/attachments/male_horns/male_horns_draenei_9/wc_male_horns_draenei_9.asset
  gfx/models/portraits/attachments/male_tail/male_tail_draenei_0/male_tail_draenei_0.asset
  gfx/models/portraits/attachments/male_tendrils/male_tendrils_draenei_0/male_tendrils_draenei_0.asset
  gfx/portraits/portrait_modifiers/wc_custom_eyebrows.txt
  gfx/portraits/portrait_modifiers/wc_custom_horns.txt
  gui/window_ruler_designer.gui
Labels: 3D graphics :triangular_ruler:, maintenance :wrench:, priority critical :exclamation:
