Repository Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2, pull requests merged in 2021-06, with the labels that each got.

#404 6th Bug Crusade
  common/culture/cultures/tauren.txt
  common/ethnicities/01_ethnicities_caucasian.txt
  common/ethnicities/wc_ethnicities_elven.txt
  common/religion/religion_families/00_abrahamic.txt
  common/religion/religion_families/00_eastern.txt
  common/religion/religion_families/00_pagan.txt
  common/scripted_triggers/wc_region_triggers.txt
  history/characters/190000_taunka.txt
  history/characters/210000_tauren.txt
  localization/english/names/wc_character_names_l_english.yml
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#415 Bald Bun Hairstyle
  common/genes/03_genes_special_accessories_hairstyles.txt
  gfx/models/portraits/attachments/male_hair/indian/male_hair_indian_03_wc/male_hair_indian_03_wc.asset
  gfx/models/portraits/attachments/male_hair/indian/male_hair_indian_03_wc/male_hair_indian_03_wc.mesh
  gfx/portraits/accessories/hairstyles.txt
  gfx/portraits/portrait_modifiers/00_hairstyles_scripted_characters.txt
  localization/english/wc_portraits_l_english.yml
Labels: :art: 3D graphics :triangular_ruler:, :exclamation: priority high

#417 Changed A Few Moira Genes
  common/dna_data/wc_dwarf_dna.txt
Labels: :art:character designing😶, :exclamation: priority critical

#394 More Human Ethnicties
  common/culture/cultures/human.txt
  common/ethnicities/01_ethnicities_african.txt
  common/ethnicities/01_ethnicities_arab.txt
  localization/replace/english/wc_replacements_l_english.yml
Labels: :art:character designing😶, :exclamation: priority high, :ice_cream: vanilla modification :icecream:

#420 White-haired Dal'rend
  common/genes/01_genes_morph.txt
  common/genes/08_genes_special_visual_traits.txt
  gfx/portraits/portrait_modifiers/wc_scripted_appearances.txt
Labels: :art:character designing😶, :exclamation: priority high

#418 Green Light of Dark Portal
  common/event_backgrounds/wc_event_backgrounds.txt
  gfx/portraits/environments/wc_portrait_environments.txt
Labels: :art:interface👁‍🗨, :exclamation: priority high

#390 Blackrock dna
  common/dna_data/wc_orc_dna.txt
  common/genes/01_genes_morph.txt
  common/genes/08_genes_special_visual_traits.txt
  common/scripted_triggers/wc_his_character_triggers.txt
  gfx/portraits/portrait_modifiers/00_beards_scripted_characters.txt
  gfx/portraits/portrait_modifiers/00_hairstyles_scripted_characters.txt
  gfx/portraits/portrait_modifiers/wc_scripted_appearances.txt
  history/characters/10000_orc.txt
Labels: :art:character designing😶, :grey_exclamation: priority medium, :question: suggestion :question:

#434 Relative Old
  common/on_action/birthday.txt
  common/on_action/yearly_on_actions.txt
  events/nickname_events/wc_nickname_events.txt
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority high

#203 Historical nicknames
  common/customizable_localization/00_DE_custom_loc.txt
  common/nicknames/wc_nicknames.txt
  common/on_action/yearly_on_actions.txt
  common/scripted_effects/wc_nicknames_effects.txt
  events/lifestyles/warfare_lifestyle/martial_strategy_events.txt
  events/nickname_events/nickname_events.txt
  events/nickname_events/wc_nickname_events.txt
  localization/english/event_localization/nickname/wc_nickname_events_l_english.yml
  localization/english/wc_nicknames_l_english.yml
  localization/french/event_localization/nickname/wc_nickname_events_l_french.yml
  localization/french/wc_nicknames_l_french.yml
  localization/german/custom_localization/wc_custom_loc_l_german.yml
  localization/german/event_localization/nickname/wc_nickname_events_l_german.yml
  localization/german/wc_nicknames_l_german.yml
Labels: :books:lore:books:, :grey_exclamation: priority medium, :ice_cream: vanilla modification :icecream:, :page_facing_up: localisation - german :pen:, :page_facing_up: localisation :pen:, :star:new feature:new:

#438 1.4.0 CB Hotfixes
  common/casus_belli_types/00_event_war.txt
  common/casus_belli_types/00_religious_war.txt
  common/casus_belli_types/01_fp1_wars.txt
  common/casus_belli_types/wc_special_wars.txt
  gui/frontend_main.gui
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#439 1.4.0 Scripted Hotfix
  common/genes/03_genes_special_accessories_hairstyles.txt
  gfx/portraits/portrait_modifiers/99_beards_scripted_characters.txt
  gfx/portraits/portrait_modifiers/99_hairstyles_scripted_characters.txt
Labels: :art:character designing😶, :exclamation: priority critical, :wrench: bug fix :hammer:

#431 Definite titular titles
  common/landed_titles/wc_holy_orders.txt
  common/landed_titles/wc_religious_titles.txt
  common/landed_titles/wc_titular_titles.txt
  localization/english/wc_holy_orders_l_english.yml
  localization/english/wc_other_titles_l_english.yml
  localization/english/wc_religious_titles_l_english.yml
  localization/french/wc_holy_orders_l_french.yml
  localization/french/wc_other_titles_l_french.yml
  localization/french/wc_religious_titles_l_french.yml
Labels: :grey_exclamation: priority low, :page_facing_up: localisation :pen:

#442 Loa Blessing
  common/dna_data/wc_troll_dna.txt
  common/modifiers/wc_event_modifiers.txt
  history/characters/10000_orc.txt
  history/characters/66000_zandalari.txt
  localization/english/modifiers/wc_modifiers_l_english.yml
Labels: :art:character designing😶, :exclamation: priority high

#452 Update wc_title_replacements_l_english.yml
  localization/replace/english/wc_title_replacements_l_english.yml
Labels: :grey_exclamation: priority medium, :page_facing_up: localisation :pen:, 🔰good first testing🧪

#441 Rastakhan dynasty dna
  common/dna_data/wc_troll_dna.txt
  common/genes/02_genes_accessories_misc.txt
  common/genes/08_genes_special_visual_traits.txt
  common/genes/wc_genes_special_eyes.txt
  common/modifiers/wc_event_modifiers.txt
  common/scripted_triggers/wc_his_character_triggers.txt
  common/traits/wc_lore_trait.txt
  gfx/portraits/accessories/bodyparts.txt
  gfx/portraits/accessories/wc_eyes.txt
  gfx/portraits/trait_portrait_modifiers/00_trait_modifiers.txt
  history/characters/10000_orc.txt
  history/characters/66000_zandalari.txt
  localization/english/modifiers/wc_modifiers_l_english.yml
Labels: :art:character designing😶, :grey_exclamation: priority medium

#458 Murloc and Gorlocs mate #428
  common/scripted_modifiers/wc_race_modifiers.txt
  common/scripted_triggers/wc_race_triggers.txt
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority high, good first issue

#430 Flags 2
  common/coat_of_arms/coat_of_arms/00_wc_landed_titles.txt
  common/coat_of_arms/coat_of_arms/wc_dynasties.txt
  common/coat_of_arms/template_lists/colored_emblem_lists.txt
  common/culture/cultures/dwarf.txt
  common/culture/cultures/elf.txt
  common/culture/cultures/gnome.txt
  gfx/coat_of_arms/colored_emblems/ce_anvilrage.dds
  gfx/coat_of_arms/colored_emblems/ce_darkiron_golem.dds
  gfx/coat_of_arms/colored_emblems/ce_dwarf_golem_2.dds
  gfx/coat_of_arms/colored_emblems/ce_dwarf_golem_crown.dds
  gfx/coat_of_arms/colored_emblems/ce_dwarf_knot_1.dds
  gfx/coat_of_arms/colored_emblems/ce_dwarf_rune_1.dds
  gfx/coat_of_arms/colored_emblems/ce_dwarf_rune_2.dds
  gfx/coat_of_arms/colored_emblems/ce_dwarf_rune_3.dds
  gfx/coat_of_arms/colored_emblems/ce_dwarf_wildhammer_1.dds
  gfx/coat_of_arms/colored_emblems/ce_dwarf_wildhammer_2.dds
  gfx/coat_of_arms/colored_emblems/ce_dwarf_wildhammer_3.dds
  gfx/coat_of_arms/colored_emblems/ce_felomelorn.dds
  gfx/coat_of_arms/colored_emblems/ce_felomelorn2.dds
  gfx/coat_of_arms/colored_emblems/ce_gilneas_moon.dds
  gfx/coat_of_arms/colored_emblems/ce_gnome_arcforged.dds
  gfx/coat_of_arms/colored_emblems/ce_gnome_eagle.dds
  gfx/coat_of_arms/colored_emblems/ce_gnome_rustbolt.dds
  gfx/coat_of_arms/colored_emblems/ce_gnomeregan.dds
  gfx/coat_of_arms/colored_emblems/ce_grim_batol.dds
  gfx/coat_of_arms/colored_emblems/ce_hammer_and_anvil.dds
  gfx/coat_of_arms/colored_emblems/ce_ironforge.dds
  gfx/coat_of_arms/colored_emblems/ce_khaz_modan.dds
  gfx/coat_of_arms/colored_emblems/ce_mechagon.dds
  gfx/coat_of_arms/colored_emblems/ce_quelthalas.dds
  gfx/coat_of_arms/colored_emblems/ce_shadowforge.dds
  gfx/coat_of_arms/colored_emblems/ce_silvermoon_wings_1.dds
  gfx/coat_of_arms/colored_emblems/ce_stonewrought.dds
  gfx/coat_of_arms/colored_emblems/ce_stormpike.dds
  gfx/coat_of_arms/colored_emblems/ce_tranquillien_wings.dds
  gfx/coat_of_arms/colored_emblems/ce_troll_eagle_loa.dds
  gfx/coat_of_arms/colored_emblems/ce_troll_mask_zuljin.dds
Labels: :art: 2D graphics :paintbrush:, :books:lore:books:, :grey_exclamation: priority medium

#447 Bald Bun and Hood Clipping
  gfx/portraits/accessories/hairstyles.txt
Labels: :art: 3D graphics :triangular_ruler:, :exclamation: priority critical, :wrench: bug fix :hammer:

#401 Arakkoa Faiths and Names
  .artist_resources/icons/faiths/wczu_anzuism.png
  .artist_resources/icons/faiths/wczu_anzuism.psd
  .artist_resources/icons/faiths/wczu_setheism.png
  .artist_resources/icons/faiths/wczu_setheism.psd
  common/culture/cultures/arakkoa.txt
  common/religion/religions/avian_group.txt
  gfx/interface/icons/faith/wczu_anzuism.dds
  gfx/interface/icons/faith/wczu_rukhmarism.dds
  gfx/interface/icons/faith/wczu_setheism.dds
  localization/english/names/wc_character_names_l_english.yml
  localization/english/religion/wc_gods_and_titles_l_english.yml
  localization/english/religion/wc_religion_l_english.yml
  localization/english/wc_traits_l_english.yml
Labels: :books:lore:books:, :exclamation: priority critical, :star:new feature:new:, 🔰good first testing🧪

#412 2nd Static Models
  common/genes/wc_genes_static_models.txt
  common/scripted_triggers/wc_portrait_triggers.txt
  gfx/models/portraits/arakkoaoutland/arakkoaoutland.asset
  gfx/models/portraits/arakkoaoutland/arakkoaoutland.mesh
  gfx/models/portraits/arakkoaoutland/arakkoaoutland_fel_base_1.dds
  gfx/models/portraits/arakkoaoutland/arakkoaoutland_gray_base_1.dds
  gfx/models/portraits/arakkoaoutland/arakkoaoutland_orange_base_1.dds
  gfx/models/portraits/arakkoaoutland/arakkoaoutland_teal_base_1.dds
  gfx/models/portraits/mantid/mantid.asset
  gfx/models/portraits/mantid/mantid.mesh
  gfx/models/portraits/mantid/mantid_black.dds
  gfx/models/portraits/mantid/mantid_green.dds
  gfx/models/portraits/mantid/mantid_purple.dds
  gfx/models/portraits/mantid/mantid_red.dds
  gfx/models/portraits/mantid/mantid_yellow.dds
  gfx/models/portraits/mantidempress/mantidempress.asset
  gfx/models/portraits/mantidempress/mantidempress.dds
  gfx/models/portraits/mantidempress/mantidempress.mesh
  gfx/models/portraits/mantidempress/mantidempress_green.dds
  gfx/models/portraits/mantidempress/mantidempress_yellow.dds
  gfx/models/portraits/tolvir/tolvir.asset
  gfx/models/portraits/tolvir/tolvir.mesh
  gfx/models/portraits/tolvir/tolvir1desert.dds
  gfx/models/portraits/tolvir/tolvir1jaguar.dds
  gfx/models/portraits/tolvir/tolvir1panther.dds
  gfx/models/portraits/tolvir/tolvir1puma.dds
  gfx/models/portraits/tolvir/tolvir1tiger.dds
  gfx/portraits/accessories/wc_races.txt
  gfx/portraits/portrait_modifiers/wc_race_portrait_modifiers.txt
  gui/shared/portraits.gui
Labels: :art: 3D graphics :triangular_ruler:, :exclamation: priority critical

#468 Anglo-Saxon Mention fix
  localization/replace/english/wc_major_decisions_l_english.yml
Labels: :exclamation: priority high, :page_facing_up: localisation :pen:, :wrench: bug fix :hammer:

#469 Troll colored emblems + co a
  common/coat_of_arms/coat_of_arms/00_wc_landed_titles.txt
  common/coat_of_arms/coat_of_arms/wc_dynasties.txt
  common/coat_of_arms/template_lists/colored_emblem_lists.txt
  gfx/coat_of_arms/colored_emblems/ce_amaniduke.dds
  gfx/coat_of_arms/colored_emblems/ce_amaniempire.dds
  gfx/coat_of_arms/colored_emblems/ce_amaniking.dds
  gfx/coat_of_arms/colored_emblems/ce_bloodscalp.dds
  gfx/coat_of_arms/colored_emblems/ce_darkspear.dds
  gfx/coat_of_arms/colored_emblems/ce_drakkariduke.dds
  gfx/coat_of_arms/colored_emblems/ce_drakkariempire.dds
  gfx/coat_of_arms/colored_emblems/ce_drakkariking.dds
  gfx/coat_of_arms/colored_emblems/ce_draktharon.dds
  gfx/coat_of_arms/colored_emblems/ce_farrakiduke.dds
  gfx/coat_of_arms/colored_emblems/ce_farrakiempire.dds
  gfx/coat_of_arms/colored_emblems/ce_farrakiking.dds
  gfx/coat_of_arms/colored_emblems/ce_frostmane.dds
  gfx/coat_of_arms/colored_emblems/ce_gurubashiduke.dds
  gfx/coat_of_arms/colored_emblems/ce_gurubashiempire.dds
  gfx/coat_of_arms/colored_emblems/ce_gurubashiking.dds
  gfx/coat_of_arms/colored_emblems/ce_malakk.dds
  gfx/coat_of_arms/colored_emblems/ce_mossflayer.dds
  gfx/coat_of_arms/colored_emblems/ce_rastakhan.dds
  gfx/coat_of_arms/colored_emblems/ce_sandscalp.dds
  gfx/coat_of_arms/colored_emblems/ce_senjin.dds
  gfx/coat_of_arms/colored_emblems/ce_shadowtooth.dds
  gfx/coat_of_arms/colored_emblems/ce_shatterspear.dds
  gfx/coat_of_arms/colored_emblems/ce_skullsplitter.dds
  gfx/coat_of_arms/colored_emblems/ce_smoulderthorn.dds
  gfx/coat_of_arms/colored_emblems/ce_troll1.dds
  gfx/coat_of_arms/colored_emblems/ce_troll10.dds
  gfx/coat_of_arms/colored_emblems/ce_troll11.dds
  gfx/coat_of_arms/colored_emblems/ce_troll12.dds
  gfx/coat_of_arms/colored_emblems/ce_troll13.dds
  gfx/coat_of_arms/colored_emblems/ce_troll2.dds
  gfx/coat_of_arms/colored_emblems/ce_troll3.dds
  gfx/coat_of_arms/colored_emblems/ce_troll4.dds
  gfx/coat_of_arms/colored_emblems/ce_troll5.dds
  gfx/coat_of_arms/colored_emblems/ce_troll6.dds
  gfx/coat_of_arms/colored_emblems/ce_troll7.dds
  gfx/coat_of_arms/colored_emblems/ce_troll8.dds
  gfx/coat_of_arms/colored_emblems/ce_troll9.dds
  gfx/coat_of_arms/colored_emblems/ce_trollhinterlands.dds
  gfx/coat_of_arms/colored_emblems/ce_trollsouthisles.dds
  gfx/coat_of_arms/colored_emblems/ce_vilebranch.dds
  gfx/coat_of_arms/colored_emblems/ce_witherbark.dds
  gfx/coat_of_arms/colored_emblems/ce_zandalariduke.dds
  gfx/coat_of_arms/colored_emblems/ce_zandalariempire.dds
  gfx/coat_of_arms/colored_emblems/ce_zandalariking.dds
  localization/replace/english/wc_title_replacements_l_english.yml
Labels: :art: 2D graphics :paintbrush:, :exclamation: priority high

#470 10x generic ogre emblems
  common/coat_of_arms/coat_of_arms/00_wc_landed_titles.txt
  common/coat_of_arms/template_lists/colored_emblem_lists.txt
  common/culture/cultures/ogre.txt
  gfx/coat_of_arms/colored_emblems/ce_ogre1.dds
  gfx/coat_of_arms/colored_emblems/ce_ogre10.dds
  gfx/coat_of_arms/colored_emblems/ce_ogre11.dds
  gfx/coat_of_arms/colored_emblems/ce_ogre12.dds
  gfx/coat_of_arms/colored_emblems/ce_ogre2.dds
  gfx/coat_of_arms/colored_emblems/ce_ogre3.dds
  gfx/coat_of_arms/colored_emblems/ce_ogre4.dds
  gfx/coat_of_arms/colored_emblems/ce_ogre5.dds
  gfx/coat_of_arms/colored_emblems/ce_ogre6.dds
  gfx/coat_of_arms/colored_emblems/ce_ogre7.dds
  gfx/coat_of_arms/colored_emblems/ce_ogre8.dds
  gfx/coat_of_arms/colored_emblems/ce_ogre9.dds
  gfx/coat_of_arms/colored_emblems/ce_ogreempire.dds
Labels: :art: 2D graphics :paintbrush:, :grey_exclamation: priority low

#488 Junkwatt Flag
  common/coat_of_arms/coat_of_arms/00_wc_landed_titles.txt
Labels: :art: 2D graphics :paintbrush:, :exclamation: priority critical

#388 Portrait Modifier Tweaks
  common/culture/cultures/elf.txt
  common/culture/cultures/orc.txt
  common/culture/cultures/troll.txt
  common/script_values/wc_portrait_values.txt
  common/scripted_modifiers/00_portrait_modifiers.txt
  common/scripted_modifiers/wc_portrait_modifiers.txt
  common/scripted_triggers/wc_clothing_triggers.txt
  gfx/portraits/portrait_modifiers/01_beards.txt
  gfx/portraits/portrait_modifiers/01_custom_beards.txt
  gfx/portraits/portrait_modifiers/01_hairstyles.txt
  gfx/portraits/portrait_modifiers/90_event_hair.txt
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority critical, :hammer: maintenance :wrench:

#166 Ogre Ethnicity
  common/culture/cultures/ogre.txt
  common/defines/graphic/00_graphics.txt
  common/ethnicities/wc_ethnicities_ogre.txt
  common/genes/05_genes_special_accessories_clothes.txt
  common/genes/wc_genes_horns.txt
  common/scripted_modifiers/00_portrait_modifiers.txt
  common/scripted_modifiers/wc_portrait_modifiers.txt
  common/scripted_triggers/wc_clothing_triggers.txt
  common/scripted_triggers/wc_portrait_triggers.txt
  common/scripted_triggers/wc_race_triggers.txt
  gfx/models/portraits/attachments/female_horns/female_ogre_horns_0/female_ogre_horns_0.asset
  gfx/models/portraits/attachments/female_horns/female_ogre_horns_0/female_ogre_horns_0.mesh
  gfx/models/portraits/attachments/female_horns/female_ogre_horns_1/female_ogre_horns_1.asset
  gfx/models/portraits/attachments/female_horns/female_ogre_horns_1/female_ogre_horns_1.mesh
  gfx/models/portraits/attachments/female_horns/female_ogre_horns_2/female_ogre_horns_2.asset
  gfx/models/portraits/attachments/female_horns/female_ogre_horns_2/female_ogre_horns_2.mesh
  gfx/models/portraits/attachments/male_horns/male_ogre_horns_0/male_ogre_horns_0.asset
  gfx/models/portraits/attachments/male_horns/male_ogre_horns_0/male_ogre_horns_0.mesh
  gfx/models/portraits/attachments/male_horns/male_ogre_horns_0/ogre_draenor_grey.dds
  gfx/models/portraits/attachments/male_horns/male_ogre_horns_1/male_ogre_horns_1.asset
  gfx/models/portraits/attachments/male_horns/male_ogre_horns_1/male_ogre_horns_1.mesh
  gfx/models/portraits/attachments/male_horns/male_ogre_horns_2/male_ogre_horns_2.asset
  gfx/models/portraits/attachments/male_horns/male_ogre_horns_2/male_ogre_horns_2.mesh
  gfx/portraits/accessories/headgear.txt
  gfx/portraits/accessories/wc_horns.txt
  gfx/portraits/environments/portrait_environments.txt
  gfx/portraits/portrait_modifiers/01_clothes.txt
  gfx/portraits/portrait_modifiers/01_hairstyles.txt
  gfx/portraits/portrait_modifiers/01_headgear.txt
  gfx/portraits/portrait_modifiers/01_legwear.txt
  gfx/portraits/portrait_modifiers/wc_custom_horns.txt
  gui/window_ruler_designer.gui
  history/characters/52000_ogre.txt
  localization/english/wc_portraits_l_english.yml
Labels: :art: 3D graphics :triangular_ruler:, :art:character designing😶, :exclamation: priority high, :star:new feature:new:, 🔰good first testing🧪

#490 innovation_prestige_value
  common/casus_belli_types/00_civil_war.txt
  common/casus_belli_types/00_claim.txt
  common/casus_belli_types/00_conquest.txt
  common/casus_belli_types/00_dejure_war.txt
  common/casus_belli_types/00_invasion_war.txt
  common/casus_belli_types/00_vassalization.txt
  common/decisions/test_decision.txt
  common/script_values/00_war_values.txt
  common/script_values/wc_war_values.txt
  common/scripted_modifiers/wc_war_modifiers.txt
  common/scripted_triggers/wc_war_triggers.txt
Labels: :exclamation: priority critical, :hammer: maintenance :wrench:

#491 7th Bug Crusade
  common/ethnicities/01_ethnicities_caucasian.txt
  common/landed_titles/wc_titular_titles.txt
  common/scripted_triggers/wc_clothing_triggers.txt
  gfx/portraits/portrait_modifiers/01_beards.txt
  gfx/portraits/portrait_modifiers/01_custom_beards.txt
  gfx/portraits/portrait_modifiers/01_custom_hair.txt
  gfx/portraits/portrait_modifiers/01_hairstyles.txt
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#494 Update 000_wc_other_titles.txt
  history/titles/000_wc_other_titles.txt
Labels: :books:lore:books:, :exclamation: priority high, 👑history📚

#496 Hellscream dna
  common/dna_data/wc_orc_dna.txt
  common/genes/03_genes_special_accessories_hairstyles.txt
  common/scripted_triggers/wc_his_character_triggers.txt
  gfx/models/portraits/attachments/male_hair/orcish/male_hair_long_with_ponytail/wc_male_hair_long_with_ponytail.asset
  gfx/models/portraits/attachments/male_hair/orcish/male_hair_long_with_ponytail/wc_male_hair_long_with_ponytail.mesh
  gfx/portraits/accessories/wc_hairstyles.txt
  gfx/portraits/portrait_modifiers/50_hairstyles_scripted_characters.txt
  history/characters/10000_orc.txt
  localization/english/wc_portraits_l_english.yml
Labels: :art:character designing😶, :books:lore:books:, :exclamation: priority critical

#495 Defias Faith Water Magic Acceptance
  common/religion/religions/light_group.txt
Labels: :books:lore:books:, :star:new feature:new:
