Repository Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2, pull requests merged in 2021-09, with the labels that each got.

#651 Virtue and Sin Rows
  gui/window_faith.gui
Labels: bug fix :hammer:, priority high :exclamation:, interface 👁‍🗨

#648 3rd Small Improvements
  common/flavorization/wc_title_holders.txt
  common/religion/doctrines/00_core_tenets.txt
  common/religion/religions/air_group.txt
  common/religion/religions/daradorism.txt
  common/religion/religions/doombringer.txt
  common/religion/religions/druidism_group.txt
  common/religion/religions/earth_group.txt
  common/religion/religions/fire_group.txt
  common/religion/religions/grond_group.txt
  common/religion/religions/loa_group.txt
  common/religion/religions/secular_group.txt
  common/religion/religions/shathgral_group.txt
  common/religion/religions/water_group.txt
  common/scripted_triggers/wc_religious_triggers.txt
  common/story_cycles/wc_story_cycle_horde_invasion.txt
  common/trigger_localization/wc_religion_triggers.txt
  localization/english/culture/wc_culture_titles_l_english.yml
  localization/english/religion/wc_core_tenets_l_english.yml
  localization/english/religion/wc_gods_and_titles_l_english.yml
Labels: new feature :star:, lore :books:, localisation :page_facing_up:, priority medium :grey_exclamation:, balance :balance_scale:

#599 Eye Changes for Ethnicities
  common/dna_data/wc_elf_dna.txt
  common/dna_data/wc_nightelf_dna.txt
  common/dna_data/wc_orc_dna.txt
  common/dna_data/wc_troll_dna.txt
  common/ethnicities/wc_ethnicities_draenei.txt
  common/ethnicities/wc_ethnicities_dwarven.txt
  common/ethnicities/wc_ethnicities_elven.txt
  common/ethnicities/wc_ethnicities_goblin.txt
  common/ethnicities/wc_ethnicities_troll.txt
  common/ethnicities/wc_ethnicities_vrykul.txt
  gfx/portraits/trait_portrait_modifiers/wc_fel_orc_modifier.txt
  gfx/portraits/trait_portrait_modifiers/wc_undead_modifier.txt
Labels: new feature :star:, suggestion :question:, priority medium :grey_exclamation:, character designing 😶

#653 Demon Horns and Wings
  .artist_resources/portraits/bloodelf_dh_wings.xcf
  common/genes/wc_genes_horns.txt
  common/genes/wc_genes_wings.txt
  gfx/models/portraits/attachments/female_horns/female_horns_dh_0/nightelf_female_dh_horns.dds
  gfx/models/portraits/attachments/female_horns/female_horns_dh_0/wc_female_horns_dh_0.asset
  gfx/models/portraits/attachments/female_horns/female_horns_dh_0/wc_female_horns_dh_0.mesh
  gfx/models/portraits/attachments/female_horns/female_horns_dh_1/wc_female_horns_dh_1.asset
  gfx/models/portraits/attachments/female_horns/female_horns_dh_1/wc_female_horns_dh_1.mesh
  gfx/models/portraits/attachments/female_horns/female_horns_dh_2/wc_female_horns_dh_2.asset
  gfx/models/portraits/attachments/female_horns/female_horns_dh_2/wc_female_horns_dh_2.mesh
  gfx/models/portraits/attachments/female_horns/female_horns_dh_3/wc_female_horns_dh_3.asset
  gfx/models/portraits/attachments/female_horns/female_horns_dh_3/wc_female_horns_dh_3.mesh
  gfx/models/portraits/attachments/female_horns/female_horns_dh_4/wc_female_horns_dh_4.asset
  gfx/models/portraits/attachments/female_horns/female_horns_dh_4/wc_female_horns_dh_4.mesh
  gfx/models/portraits/attachments/female_horns/female_horns_dh_5/wc_female_horns_dh_5.asset
  gfx/models/portraits/attachments/female_horns/female_horns_dh_5/wc_female_horns_dh_5.mesh
  gfx/models/portraits/attachments/female_wings/female_wings_dh_0/bloodelf_dh_wings.dds
  gfx/models/portraits/attachments/female_wings/female_wings_dh_0/wc_female_wings_dh_0.asset
  gfx/models/portraits/attachments/female_wings/female_wings_dh_0/wc_female_wings_dh_0.mesh
  gfx/models/portraits/attachments/female_wings/female_wings_succubus_0/succubus2.dds
  gfx/models/portraits/attachments/female_wings/female_wings_succubus_0/wc_female_wings_succubus_0.asset
  gfx/models/portraits/attachments/female_wings/female_wings_succubus_0/wc_female_wings_succubus_0.mesh
  gfx/models/portraits/attachments/male_horns/male_horns_dh_0/nightelfmale_dh_horns.dds
  gfx/models/portraits/attachments/male_horns/male_horns_dh_0/wc_male_horns_dh_0.asset
  gfx/models/portraits/attachments/male_horns/male_horns_dh_0/wc_male_horns_dh_0.mesh
  gfx/models/portraits/attachments/male_horns/male_horns_dh_1/wc_male_horns_dh_1.asset
  gfx/models/portraits/attachments/male_horns/male_horns_dh_1/wc_male_horns_dh_1.mesh
  gfx/models/portraits/attachments/male_horns/male_horns_dh_2/wc_male_horns_dh_2.asset
  gfx/models/portraits/attachments/male_horns/male_horns_dh_2/wc_male_horns_dh_2.mesh
  gfx/models/portraits/attachments/male_horns/male_horns_dh_3/wc_male_horns_dh_3.asset
  gfx/models/portraits/attachments/male_horns/male_horns_dh_3/wc_male_horns_dh_3.mesh
  gfx/models/portraits/attachments/male_horns/male_horns_dh_4/wc_male_horns_dh_4.asset
  gfx/models/portraits/attachments/male_horns/male_horns_dh_4/wc_male_horns_dh_4.mesh
  gfx/models/portraits/attachments/male_horns/male_horns_dh_5/wc_male_horns_dh_5.asset
  gfx/models/portraits/attachments/male_horns/male_horns_dh_5/wc_male_horns_dh_5.mesh
  gfx/models/portraits/attachments/male_wings/male_wings_dh_0/wc_male_wings_dh_0.asset
  gfx/models/portraits/attachments/male_wings/male_wings_dh_0/wc_male_wings_dh_0.mesh
  gfx/portraits/accessories/wc_horns.txt
  gfx/portraits/accessories/wc_wings.txt
  gfx/portraits/portrait_modifiers/wc_custom_horns.txt
  localization/english/wc_portraits_l_english.yml
Labels: priority critical :exclamation:, 3D graphics :triangular_ruler:, character designing 😶

#658 Alex Horns
  common/genes/wc_genes_horns.txt
  gfx/models/portraits/attachments/female_horns/female_alex_horns_0/ladyalexstrasaskin2.dds
  gfx/models/portraits/attachments/female_horns/female_alex_horns_0/wc_female_alex_horns_0.asset
  gfx/models/portraits/attachments/female_horns/female_alex_horns_0/wc_female_alex_horns_0.mesh
  gfx/portraits/accessories/wc_horns.txt
  gfx/portraits/portrait_modifiers/wc_custom_horns.txt
  localization/english/wc_portraits_l_english.yml
Labels: priority critical :exclamation:, 3D graphics :triangular_ruler:

#630 Nathrezim Ethnicity
  common/culture/cultures/demonic.txt
  common/ethnicities/wc_ethnicities_demonic.txt
  common/genes/01_genes_morph.txt
  common/genes/wc_gene_facial_markings.txt
  common/genes/wc_genes_claws.txt
  common/genes/wc_genes_horns.txt
  common/genes/wc_genes_sexual_dimorphism.txt
  gfx/models/portraits/attachments/female_claws/female_claws_nathrezim_0/wc_female_claws_nathrezim_0.asset
  gfx/models/portraits/attachments/female_claws/female_claws_nathrezim_0/wc_female_claws_nathrezim_0.mesh
  gfx/models/portraits/attachments/male_claws/male_claws_nathrezim_1/dreadlordshadowlands_body_4.dds
  gfx/models/portraits/attachments/male_claws/male_claws_nathrezim_1/wc_male_claws_nathrezim_1.asset
  gfx/models/portraits/attachments/male_claws/male_claws_nathrezim_1/wc_male_claws_nathrezim_1.mesh
  gfx/models/portraits/decals/makeup/decal_nathrezim_female_01.dds
  gfx/models/portraits/decals/makeup/decal_nathrezim_female_02.dds
  gfx/models/portraits/decals/makeup/decal_nathrezim_female_03.dds
  gfx/models/portraits/decals/makeup/decal_nathrezim_lipstick.dds
  gfx/models/portraits/decals/makeup/decal_nathrezim_male_01.dds
  gfx/models/portraits/decals/makeup/decal_nathrezim_male_02.dds
  gfx/models/portraits/decals/makeup/decal_nathrezim_male_03.dds
  gfx/models/portraits/decals/makeup/decal_nathrezim_male_04.dds
  gfx/portraits/accessories/wc_claws.txt
  localization/english/wc_portraits_l_english.yml
Labels: new feature :star:, priority critical :exclamation:, 3D graphics :triangular_ruler:, character designing 😶

#656 Perk countdown in magic trait tooltip
  common/customizable_localization/wc_magical_lifestyles_custom_loc.txt
  common/script_values/wc_magic_lifestyles_values.txt
  common/script_values/wc_mana_values.txt
  localization/english/gui/wc_magic_lifestyles_window_character_lifestyle_l_english.yml
Labels: priority low :grey_exclamation:, interface 👁‍🗨

#668 1st History Corrections
  history/characters/10000_orc.txt
Labels: lore :books:, priority critical :exclamation:, history 👑

#637 New Troll Characters
  common/nicknames/wc_nicknames.txt
  history/characters/15000_gurubashi.txt
  history/characters/200000_farraki.txt
  history/characters/57000_amani.txt
  history/characters/6000_gurubashi.txt
  history/characters/66000_zandalari.txt
  history/characters/80000_drakkari.txt
  history/titles/000_wc_other_titles.txt
  history/titles/000_wc_religious_head_titles.txt
  history/titles/00_k_dead_morass.txt
  history/titles/00_k_gurubashi.txt
  history/titles/00_k_quelthalas.txt
  history/titles/00_k_zandalar.txt
  history/titles/00_k_zulaman.txt
  localization/english/names/wc_character_names_l_english.yml
  localization/english/wc_nicknames_l_english.yml
Labels: suggestion :question:, lore :books:, history 👑

#672 Goblin Body Type Fix
  common/ethnicities/wc_ethnicities_goblin.txt
Labels: bug fix :hammer:, character designing 😶

#674 Gene Refactoring
  common/dna_data/wc_human_dna.txt
  common/dna_data/wc_orc_dna.txt
  common/ethnicities/wc_ethnicities_demonic.txt
  common/genes/01_genes_morph.txt
  common/genes/08_genes_special_visual_traits.txt
  common/genes/wc_gene_facial_markings.txt
  common/genes/wc_genes_morph.txt
  gfx/portraits/portrait_modifiers/wc_scripted_appearances.txt
Labels: maintenance :wrench:, vanilla modification :icecream:, priority critical :exclamation:

#673 Undead Elf Modifier
  gfx/portraits/trait_portrait_modifiers/wc_undead_modifier.txt
Labels: suggestion :question:, lore :books:, good first issue, character designing 😶

#678 Erwin's Crusade 1
  common/flavorization/wc_title_holders.txt
  common/landed_titles/wc_religious_titles.txt
  common/landed_titles/wc_titular_titles.txt
  common/religion/doctrines/wc_doctrines_magic.txt
  common/religion/religions/nerub_group.txt
  history/provinces/00_k_thalanaar.txt
  history/titles/000_wc_religious_head_titles.txt
  localization/english/culture/wc_culture_titles_l_english.yml
  localization/english/religion/wc_magic_doctrines_l_english.yml
Labels: bug fix :hammer:, localisation :page_facing_up:, priority high :exclamation:, balance :balance_scale:, history 👑

#676 New loading screens
  gfx/interface/illustrations/loading_screens/baghdad.dds
  gfx/interface/illustrations/loading_screens/load_13.dds
  gfx/interface/illustrations/loading_screens/load_14.dds
  gfx/interface/illustrations/loading_screens/runestone.dds
Labels: priority low :grey_exclamation:, 2D graphics :paintbrush:

#679 Night Elf Markings Rework + 1 New Marking
  common/genes/wc_gene_facial_markings.txt
  gfx/models/portraits/decals/nightelf_markings/decal_nightelf_marking_01.dds
  gfx/models/portraits/decals/nightelf_markings/decal_nightelf_marking_02.dds
  gfx/models/portraits/decals/nightelf_markings/decal_nightelf_marking_03.dds
  gfx/models/portraits/decals/nightelf_markings/decal_nightelf_marking_04.dds
  gfx/models/portraits/decals/nightelf_markings/decal_nightelf_marking_05.dds
  gfx/models/portraits/decals/nightelf_markings/decal_nightelf_marking_06.dds
  gfx/models/portraits/decals/nightelf_markings/decal_nightelf_marking_07.dds
  gfx/models/portraits/decals/nightelf_markings/decal_nightelf_marking_08.dds
  gfx/models/portraits/decals/nightelf_markings/decal_nightelf_marking_09.dds
  gfx/portraits/portrait_modifiers/wc_facial_markings.txt
  localization/english/wc_portraits_l_english.yml
Labels: suggestion :question:, priority high :exclamation:, 2D graphics :paintbrush:

#661 Demonic Clothes
  common/culture/cultures/demonic.txt
  common/culture/cultures/elf.txt
  common/genes/05_genes_special_accessories_clothes.txt
  common/scripted_triggers/wc_clothing_triggers.txt
  gfx/models/portraits/attachments/female_clothes/secular/demonic/nobility_01/female_clothing_secular_demonic_nobility_01.asset
  gfx/models/portraits/attachments/female_clothes/secular/demonic/nobility_02/female_clothes_secular_demonic_nobility_02.asset
  gfx/models/portraits/attachments/female_clothes/secular/demonic/war_nobility_01/female_clothing_secular_demonic_war_nobility_01.asset
  gfx/models/portraits/attachments/male_clothes/secular/demonic/nobility_01/male_clothing_secular_demonic_nobility_01.asset
  gfx/models/portraits/attachments/male_clothes/secular/demonic/nobility_02/male_clothes_secular_demonic_nobility_02.asset
  gfx/models/portraits/attachments/male_clothes/secular/demonic/war_nobility_01/male_clothing_secular_demonic_war_nobility_01.asset
  gfx/portraits/accessories/wc_clothes.txt
  gfx/portraits/accessory_variations/indian.txt
  gfx/portraits/accessory_variations/textures/color_palette_demonic_common.dds
  gfx/portraits/portrait_modifiers/01_clothes.txt
  gfx/portraits/portrait_modifiers/01_custom_clothes.txt
Labels: priority critical :exclamation:, 3D graphics :triangular_ruler:, character designing 😶

#698 Placeholder Bookmark Graphics
  common/bookmark_portraits/arthas_menethil_character.txt
  common/bookmark_portraits/llane_wrynn_character.txt
  common/bookmark_portraits/othmar_garithos_character.txt
  gfx/interface/bookmarks/bm_the_frozen_throne.dds
  gfx/interface/bookmarks/bm_the_invasion_from_draenor.dds
  gfx/interface/bookmarks/bm_the_reign_of_chaos.dds
Labels: suggestion :question:, 2D graphics :paintbrush:, interface 👁‍🗨

#691 Wildhammer Facial Tattoos
  common/culture/cultures/dwarf.txt
  common/ethnicities/wc_ethnicities_dwarven.txt
  common/genes/wc_gene_facial_markings.txt
  common/scripted_modifiers/wc_portrait_modifiers.txt
  common/scripted_triggers/wc_clothing_triggers.txt
  gfx/models/portraits/decals/wildhammer_tattoos/decal_wildhammer_tattoo_01.dds
  gfx/models/portraits/decals/wildhammer_tattoos/decal_wildhammer_tattoo_02.dds
  gfx/models/portraits/decals/wildhammer_tattoos/decal_wildhammer_tattoo_03.dds
  gfx/models/portraits/decals/wildhammer_tattoos/decal_wildhammer_tattoo_04.dds
  gfx/models/portraits/decals/wildhammer_tattoos/decal_wildhammer_tattoo_05.dds
  gfx/models/portraits/decals/wildhammer_tattoos/decal_wildhammer_tattoo_05_f.dds
  gfx/models/portraits/decals/wildhammer_tattoos/decal_wildhammer_tattoo_06.dds
  gfx/models/portraits/decals/wildhammer_tattoos/decal_wildhammer_tattoo_06_f.dds
  gfx/portraits/portrait_modifiers/wc_facial_markings.txt
  localization/english/wc_portraits_l_english.yml
Labels: priority high :exclamation:, 2D graphics :paintbrush:, character designing 😶, good first testing 🧪

#690 Moving Race Triggers
  common/scripted_triggers/wc_portrait_triggers.txt
  common/scripted_triggers/wc_race_triggers.txt
Labels: maintenance :wrench:, priority critical :exclamation:

#705 Windrunner Sisters Height Fix
  common/dna_data/wc_elf_dna.txt
Labels: bug fix :hammer:, priority critical :exclamation:, character designing 😶

#708 Dark Barons Issue
  common/on_action/game_start.txt
  common/scripted_effects/wc_being_effects.txt
  common/scripted_effects/wc_government_effects.txt
  common/scripted_triggers/wc_government_triggers.txt
Labels: bug fix :hammer:, priority critical :exclamation:

#556 Death flags
  common/coat_of_arms/coat_of_arms/00_wc_landed_titles.txt
  common/coat_of_arms/template_lists/color_lists.txt
  common/coat_of_arms/template_lists/colored_emblem_lists.txt
  common/named_colors/default_colors.txt
  common/named_colors/wc_colors.txt
  common/scripted_triggers/wc_coa_triggers.txt
  gfx/coat_of_arms/colored_emblems/ce_abomination.dds
  gfx/coat_of_arms/colored_emblems/ce_dk_helmet.dds
  gfx/coat_of_arms/colored_emblems/ce_necropolis.dds
  gfx/coat_of_arms/colored_emblems/ce_ram_skull.dds
  gfx/coat_of_arms/colored_emblems/ce_scream.dds
  gfx/coat_of_arms/colored_emblems/ce_skull1.dds
  gfx/coat_of_arms/colored_emblems/ce_skull1_fire.dds
  gfx/coat_of_arms/colored_emblems/ce_skull2.dds
  gfx/coat_of_arms/colored_emblems/ce_skull3.dds
  gfx/coat_of_arms/colored_emblems/ce_skull3_jaw.dds
  gfx/coat_of_arms/colored_emblems/ce_spider.dds
Labels: priority high :exclamation:, 2D graphics :paintbrush:

#602 Health Goes Down With Age
  common/defines/00_defines.txt
  common/modifiers/wc_age_modifiers.txt
  common/pool_character_selectors/00_auto_barons.txt
  common/pool_character_selectors/00_city.txt
  common/pool_character_selectors/00_clergy.txt
  common/pool_character_selectors/00_holy_order.txt
  common/pool_character_selectors/00_mercenary.txt
  common/script_values/wc_age_values.txt
  common/scripted_character_templates/00_foundling_templates.txt
  common/scripted_character_templates/00_holy_order_character_templates.txt
  common/scripted_character_templates/00_lifestyle_friend_templates.txt
  common/scripted_character_templates/00_mystic_templates.txt
  common/scripted_character_templates/00_officials_templates.txt
  common/scripted_character_templates/00_peasant_faction_leader_template.txt
  common/scripted_character_templates/00_peasant_leader_templates.txt
  common/scripted_character_templates/00_peasants_template.txt
  common/scripted_character_templates/00_pool_repopulation_character_templates.txt
  common/scripted_character_templates/00_priest_character_template.txt
  common/scripted_character_templates/00_saharan_nomad_template.txt
  common/scripted_character_templates/00_scholar_template.txt
  common/scripted_character_templates/00_soldier_character_templates.txt
  common/scripted_character_templates/01_fp1_character_templates.txt
  common/scripted_character_templates/wc_draenor_templates.txt
  common/scripted_effects/00_game_rule_effects.txt
  common/scripted_effects/00_stewardship_lifestyle_effects.txt
  common/scripted_effects/wc_age_effects.txt
  common/scripted_effects/wc_race_effects.txt
  common/scripted_triggers/wc_race_triggers.txt
  common/traits/wc_infusion_traits.txt
  events/activities/hunt_activity/hunt_events.txt
  events/government_events/clan_events.txt
  events/health_events.txt
  events/lifestyles/governance_lifestyle/stewardship_general_events.txt
  events/lifestyles/governance_lifestyle/stewardship_wealth_events.txt
  events/lifestyles/intrigue_lifestyle/intrigue_scheming_events.txt
  events/lifestyles/scholarship_lifestyle/learning_medicine_events.txt
  events/lifestyles/warfare_lifestyle/martial_authority_events.txt
  events/lifestyles/warfare_lifestyle/martial_strategy_events.txt
  events/religion_events/faith_creation_events.txt
  events/stress_events/stress_threshold_special_events.txt
  events/wc_events/wc_race_events.txt
  history/characters/1_azerothian.txt
  history/characters/60000_63000_lordaeronian.txt
  localization/english/modifiers/wc_modifiers_l_english.yml
Labels: vanilla modification :icecream:, priority critical :exclamation:, balance :balance_scale:

#702 4th Small Improvements
  common/culture/cultures/dragon.txt
  common/religion/religions/loa_group.txt
  common/scripted_character_templates/wc_historical_draenor_templates.txt
  common/traits/wc_race_traits.txt
  history/characters/10000_orc.txt
  localization/english/triggers/wc_character_triggers_l_english.yml
  localization/german/triggers/wc_character_triggers_l_german.yml
Labels: priority medium :grey_exclamation:, balance :balance_scale:, good first testing 🧪
