Repository Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2, pull requests merged in 2021-04, with the labels that each got.

#233 Custom Unions
  common/character_interactions/wc_pol_faction_interactions.txt
  common/customizable_localization/wc_general_custom_loc.txt
  common/decisions/wc_pol_faction_decisions.txt
  common/game_concepts/wc_other_game_concepts.txt
  common/game_concepts/wc_union_game_concepts.txt
  common/on_action/title_on_actions.txt
  common/scripted_effects/wc_cooldown_effects.txt
  common/scripted_effects/wc_gui_effects.txt
  common/scripted_effects/wc_pol_faction_effects.txt
  common/scripted_guis/wc_pol_faction.txt
  common/scripted_modifiers/wc_pol_faction_modifiers.txt
  common/scripted_triggers/wc_pol_faction_triggers.txt
  events/wc_events/wc_pol_faction_events.txt
  gui/hud.gui
  localization/english/wc_game_concepts_l_english.yml
  localization/english/wc_gui_l_english.yml
  localization/english/wc_pol_faction_l_english.yml
  localization/german/wc_game_concepts_l_german.yml
  localization/german/wc_gui_l_german.yml
  localization/german/wc_pol_faction_l_german.yml
Labels: :exclamation: priority high, :page_facing_up: localisation :pen:, :star: new feature :new:, interface

#274 Draconic religion is now gender equal
  common/religion/religions/titanic_group.txt
Labels: :balance_scale: balance :balance_scale:, :books: lore :books:, :exclamation: priority critical

#270 Dalaran Light Religion
  .artist_resources/icons/wcmw_shendralar_religion.xcf
  common/coat_of_arms/coat_of_arms/00_wc_landed_titles.txt
  common/landed_titles/wc_religious_titles.txt
  common/religion/religions/arcane_group.txt
  common/religion/religions/light_group.txt
  gfx/interface/icons/religion/wczu_shendralar_religion.dds
  history/characters/1_azerothian.txt
  history/characters/310000_patron_characters.txt
  history/characters/38000_arathorian.txt
  history/characters/46000_gilnean.txt
  history/characters/59000_dalaranian.txt
  history/characters/60000_63000_lordaeronian.txt
  history/provinces/00_k_black_morass.txt
  history/provinces/00_k_dalaran.txt
  history/provinces/00_k_gilneas.txt
  history/titles/00_wc_religious_head_titles.txt
  localization/english/religion/wc_gods_and_titles_l_english.yml
  localization/english/religion/wc_religion_l_english.yml
  localization/english/wc_other_titles_l_english.yml
Labels: :grey_exclamation: priority medium, :page_facing_up: localisation :pen:, :star: new feature :new:

#276 #212 Duchy of the Cult of
  common/landed_titles/wc_religious_titles.txt
Labels: :books: lore :books:, :grey_exclamation: priority medium, :page_facing_up: localisation :pen:, :wrench: bug fix :hammer:

#96 New basic unit innovations
  common/culture/innovations/wc_cultural_innovations.txt
  gfx/interface/icons/culture_innovations/innovation_arkonite.dds
  gfx/interface/icons/culture_innovations/innovation_watersmithing.dds
  history/cultures/ankoan.txt
  history/cultures/draenei.txt
  history/cultures/forsaken.txt
  history/cultures/goblin.txt
  history/cultures/jinyu.txt
  history/cultures/scourge.txt
  history/cultures/wastewander.txt
  localization/english/culture/wc_cultural_innovations_l_english.yml
  localization/german/culture/wc_cultural_innovations_l_german.yml
Labels: :grey_exclamation: priority medium

#286 252 pat_grm_name_chance Twice
  common/culture/cultures/aqir.txt
  common/culture/cultures/arakkoa.txt
  common/culture/cultures/centaur.txt
  common/culture/cultures/demonic.txt
  common/culture/cultures/draenei.txt
  common/culture/cultures/dragon.txt
  common/culture/cultures/dryad.txt
  common/culture/cultures/dwarf.txt
  common/culture/cultures/elemental.txt
  common/culture/cultures/elf.txt
  common/culture/cultures/furbolg.txt
  common/culture/cultures/gnoll.txt
  common/culture/cultures/gnome.txt
  common/culture/cultures/goblin.txt
  common/culture/cultures/harpy.txt
  common/culture/cultures/hozen.txt
  common/culture/cultures/human.txt
  common/culture/cultures/jinyu.txt
  common/culture/cultures/kobold.txt
  common/culture/cultures/magnataur.txt
  common/culture/cultures/mogu.txt
  common/culture/cultures/murloc.txt
  common/culture/cultures/ogre.txt
  common/culture/cultures/orc.txt
  common/culture/cultures/pandaren.txt
  common/culture/cultures/pygmy.txt
  common/culture/cultures/quilboar.txt
  common/culture/cultures/sethrak.txt
  common/culture/cultures/shathyar.txt
  common/culture/cultures/tauren.txt
  common/culture/cultures/titanforged.txt
  common/culture/cultures/tortollan.txt
  common/culture/cultures/trogg.txt
  common/culture/cultures/troll.txt
  common/culture/cultures/tuskarr.txt
  common/culture/cultures/undead.txt
  common/culture/cultures/vrykul.txt
  common/culture/cultures/vulpera.txt
Labels: :beetle: bug :beetle:, :exclamation: priority critical

#289 176 Albino Shouldn't Override Undead
  gfx/portraits/trait_portrait_modifiers/00_trait_modifiers.txt
Labels: :art: 3D graphics :triangular_ruler:, :beetle: bug :beetle:, :grey_exclamation: priority medium

#287 206 Lordaeron Cathedral Flavor Text Mentions Christians Instead of Holy Light
  localization/replace/english/wc_buildings_l_english.yml
Labels: :beetle: bug :beetle:, :grey_exclamation: priority low, :page_facing_up: localisation :pen:

#269 Shatter Realm
  common/casus_belli_types/00_invasion_war.txt
  common/casus_belli_types/wc_special_wars.txt
  common/decisions/test_decision.txt
  common/effect_localization/wc_general_effects.txt
  common/modifiers/wc_event_modifiers.txt
  common/script_values/wc_realm_values.txt
  common/script_values/wc_war_values.txt
  common/scripted_effects/wc_horde_invasion_effects.txt
  common/scripted_effects/wc_war_effects.txt
  common/scripted_triggers/wc_pol_faction_triggers.txt
  common/scripted_triggers/wc_war_triggers.txt
  common/story_cycles/wc_story_cycle_horde_invasion.txt
  events/story_cycles/wc_story_cycle_horde_invasion_events.txt
  localization/english/wc_general_l_english.yml
  localization/english/wc_messages_l_english.yml
  localization/english/wc_modifiers_l_english.yml
  localization/english/wc_tooltip_l_english.yml
  localization/english/wc_wars_l_english.yml
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority high, :star: new feature :new:

#290 #171 Interracial Game Rules
  common/game_rules/000_wc_game_rules.txt
  common/scripted_modifiers/wc_race_modifiers.txt
  common/scripted_triggers/wc_race_triggers.txt
  localization/english/wc_game_rules_l_english.yml
  localization/french/wc_game_rules_l_french.yml
  localization/german/wc_game_rules_l_german.yml
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority high, :star: new feature :new:

#293 #175 Characters born year 20 or earlier displays age "???"
  gui/multiplayer_lobby.gui
  gui/shared/lists.gui
  gui/window_character.gui
  localization/english/wc_tooltip_l_english.yml
  localization/french/wc_tooltip_l_french.yml
  localization/german/wc_tooltip_l_german.yml
Labels: :books: lore :books:, :grey_exclamation: priority medium, :page_facing_up: localisation :pen:, :star: new feature :new:, good first testing, interface

#291 Nightborne Race Trait
  common/culture/cultures/elf.txt
  common/flavorization/wc_title_holders.txt
  common/religion/religions/arcane_group.txt
  common/scripted_effects/wc_race_effects.txt
  common/scripted_triggers/wc_portrait_triggers.txt
  common/scripted_triggers/wc_race_triggers.txt
  common/traits/wc_race_traits.txt
  events/wc_events/wc_race_events.txt
  gfx/interface/icons/traits/creature_nightborne.dds
  localization/english/culture/wc_culture_titles_l_english.yml
  localization/english/wc_traits_l_english.yml
  localization/french/culture/wc_culture_titles_l_french.yml
  localization/french/wc_traits_l_french.yml
  localization/german/wc_traits_l_german.yml
Labels: :books: lore :books:, :grey_exclamation: priority low, :star: new feature :new:, good first testing

#100 1st localisation crusade
  localization/english/modifiers/wc_modifiers_l_english.yml
  localization/english/religion/wc_religion_l_english.yml
  localization/english/wc_general_l_english.yml
  localization/english/wc_modifiers_l_english.yml
  localization/english/wc_traits_l_english.yml
  localization/german/culture/wc_cultural_innovations_l_german.yml
  localization/german/modifiers/wc_modifiers_l_german.yml
  localization/german/religion/wc_core_tenets_l_german.yml
  localization/german/religion/wc_magic_doctrines_l_german.yml
  localization/german/religion/wc_religion_l_german.yml
  localization/german/wc_custom_titles_l_german.yml
  localization/german/wc_game_concepts_l_german.yml
  localization/german/wc_general_l_german.yml
  localization/german/wc_gui_l_german.yml
  localization/german/wc_messages_l_german.yml
  localization/german/wc_other_titles_l_german.yml
  localization/german/wc_pol_faction_l_german.yml
  localization/german/wc_tooltip_l_german.yml
  localization/german/wc_traits_l_german.yml
  localization/german/wc_wars_l_german.yml
  localization/replace/english/wc_cultural_innovations_l_english.yml
  localization/replace/english/wc_game_concepts_l_english.yml
  localization/replace/english/wc_game_rules_l_english.yml
  localization/replace/english/wc_legacies_l_english.yml
  localization/replace/english/wc_perks_l_english.yml
  localization/replace/english/wc_replacements_l_english.yml
  localization/replace/german/wc_buildings_l_german.yml
  localization/replace/german/wc_cultural_innovations_l_german.yml
  localization/replace/german/wc_game_concepts_l_german.yml
  localization/replace/german/wc_game_rules_l_german.yml
  localization/replace/german/wc_legacies_l_german.yml
  localization/replace/german/wc_perks_l_german.yml
  localization/replace/german/wc_religions_l_german.yml
  localization/replace/german/wc_title_replacements_l_german.yml
Labels: :page_facing_up: localisation :pen:

#319 kirin torism moved and translated
  localization/english/religion/wc_religion_l_english.yml
  localization/german/religion/wc_religion_l_german.yml
Labels: :page_facing_up: localisation :pen:

#306 Highmountain Tauren race trait
  common/culture/cultures/tauren.txt
  common/scripted_effects/wc_race_effects.txt
  common/scripted_triggers/wc_portrait_triggers.txt
  common/scripted_triggers/wc_race_triggers.txt
  common/traits/wc_race_traits.txt
  events/wc_events/wc_race_events.txt
  gfx/interface/icons/traits/creature_highmountain_tauren.dds
  localization/english/wc_traits_l_english.yml
  localization/french/wc_traits_l_french.yml
  localization/german/wc_traits_l_german.yml
Labels: :art: 2D graphics :paintbrush:, :books: lore :books:, :grey_exclamation: priority low, :page_facing_up: localisation :pen:, :star: new feature :new:, 🔰good first testing🧪

#324 Fixed younger races spawning very old
  common/script_values/wc_age_values.txt
Labels: :beetle: bug :beetle:, :exclamation: priority high, :wrench: bug fix :hammer:

#284 5th Bug Crusade
  common/defines/graphic/00_graphics.txt
  common/men_at_arms_types/00_regional_maa_types.txt
  common/script_values/00_war_values.txt
  common/scripted_character_templates/00_pool_repopulation_character_templates.txt
  common/scripted_character_templates/00_soldier_character_templates.txt
  common/scripted_effects/00_game_rule_effects.txt
  common/scripted_effects/wc_gui_effects.txt
  common/scripted_effects/wc_health_effects.txt
  common/scripted_effects/wc_race_effects.txt
  common/scripted_guis/wc_pol_faction.txt
  common/scripted_triggers/wc_clothing_triggers.txt
  common/scripted_triggers/wc_year_triggers.txt
  events/story_cycles/wc_story_cycle_horde_invasion_events.txt
  events/wc_events/wc_pol_faction_events.txt
  gfx/portraits/accessories/bodyparts.txt
  gui/hud_notification_templates.gui
  gui/window_decisions.gui
  history/characters/10000_orc.txt
  history/characters/17000_28000_bronzebeard.txt
  history/characters/1_azerothian.txt
  history/characters/210000_tauren.txt
  history/characters/22000_wildhammer.txt
  history/characters/310000_patron_characters.txt
  history/characters/340000_night_elf.txt
  history/characters/420000_ancients.txt
  history/characters/46000_gilnean.txt
  history/characters/48000_tirassian.txt
  history/characters/56000_mossflayer.txt
  history/characters/57000_amani.txt
  history/characters/59000_dalaranian.txt
  history/characters/60000_63000_lordaeronian.txt
  history/characters/90000_pirate.txt
  localization/english/wc_pol_faction_l_english.yml
  localization/german/wc_pol_faction_l_german.yml
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:, 🔰good first testing🧪

#209 Custom DNA - Batch 1
  common/dna_data/wc_dwarf_dna.txt
  common/dna_data/wc_elf_dna.txt
  common/dna_data/wc_human_dna.txt
  common/dna_data/wc_nightelf_dna.txt
  common/dna_data/wc_orc_dna.txt
  common/dna_data/wc_troll_dna.txt
  common/ethnicities/00_ethnicities_templates.txt
  common/genes/01_genes_morph.txt
  common/genes/03_genes_special_accessories_hairstyles.txt
  common/genes/04_genes_special_accessories_beards.txt
  common/genes/wc_scripted_makeup.txt
  common/modifiers/wc_event_modifiers.txt
  common/scripted_effects/wc_health_effects.txt
  common/scripted_effects/wc_portrait_effects.txt
  common/scripted_modifiers/00_portrait_modifiers.txt
  common/scripted_modifiers/wc_portrait_modifiers.txt
  common/scripted_triggers/wc_his_character_triggers.txt
  common/scripted_triggers/wc_portrait_triggers.txt
  gfx/models/portraits/attachments/male_beards/western/male_beard_western_09/male_beard_western_09.asset
  gfx/models/portraits/attachments/male_beards/western/male_beard_western_09/male_beard_western_09_normal_wc.dds
  gfx/models/portraits/attachments/male_hair/western/male_hair_western_07/male_hair_western_07.asset
  gfx/models/portraits/attachments/male_hair/western/male_hair_western_07/male_hair_western_07_normal_wc.dds
  gfx/models/portraits/decals/scripted_makeup/decal_nightelf_marking_azshara_eyelids.dds
  gfx/models/portraits/decals/scripted_makeup/decal_nightelf_marking_azshara_noeyelids.dds
  gfx/models/portraits/decals/scripted_makeup/decal_nightelf_marking_eyelids.dds
  gfx/models/portraits/decals/scripted_makeup/decal_nightelf_marking_noeyelids.dds
  gfx/models/portraits/decals/scripted_makeup/decal_sylvanas_makeup.dds
  gfx/models/portraits/decals/scripted_makeup/decal_voljin_warpaint.dds
  gfx/portraits/accessories/beards.txt
  gfx/portraits/accessories/hairstyles.txt
  gfx/portraits/portrait_modifiers/00_beards_scripted_characters.txt
  gfx/portraits/portrait_modifiers/00_hairstyles_scripted_characters.txt
  gfx/portraits/portrait_modifiers/01_beards.txt
  gfx/portraits/portrait_modifiers/01_hairstyles.txt
  gfx/portraits/portrait_modifiers/wc_scripted_appearances.txt
  gfx/portraits/trait_portrait_modifiers/wc_undead_modifier.txt
  history/characters/10000_orc.txt
  history/characters/17000_28000_bronzebeard.txt
  history/characters/1_azerothian.txt
  history/characters/340000_night_elf.txt
  history/characters/38000_arathorian.txt
  history/characters/42000_high_elf.txt
  history/characters/46000_gilnean.txt
  history/characters/48000_tirassian.txt
  history/characters/58000_alteraci.txt
  history/characters/59000_dalaranian.txt
  history/characters/60000_63000_lordaeronian.txt
  history/characters/68000_darkspear.txt
  localization/english/modifiers/wc_modifiers_l_english.yml
  localization/german/modifiers/wc_modifiers_l_german.yml
Labels: :art: character designing 😶, :books: lore :books:, :grey_exclamation: priority medium, :star: new feature :new:, good first issue

#329 Trogg race trait
  common/culture/cultures/trogg.txt
  common/scripted_effects/wc_race_effects.txt
  common/scripted_triggers/wc_portrait_triggers.txt
  common/scripted_triggers/wc_race_triggers.txt
  common/traits/wc_race_traits.txt
  events/wc_events/wc_race_events.txt
  gfx/interface/icons/traits/creature_trogg.dds
  localization/english/wc_traits_l_english.yml
  localization/french/wc_traits_l_french.yml
  localization/german/wc_traits_l_german.yml
Labels: :art: 2D graphics :paintbrush:, :balance_scale: balance :balance_scale:, :books: lore :books:, :grey_exclamation: priority medium, :page_facing_up: localisation :pen:, :wrench: bug fix :hammer:, 🔰good first testing🧪
