Repository Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2, pull requests merged in 2021-02, with the labels that each got.

#20 Horde Invasion
  common/casus_belli_types/00_invasion_war.txt
  common/coat_of_arms/coat_of_arms/wc_dynasties.txt
  common/decisions/wc_horde_decisions.txt
  common/dynasty_houses/wc_dynasty_houses.txt
  common/event_backgrounds/wc_event_backgrounds.txt
  common/flavorization/wc_title_holders.txt
  common/landed_titles/wc_titular_titles.txt
  common/laws/01_title_succession_laws.txt
  common/modifiers/wc_event_modifiers.txt
  common/nicknames/wc_nicknames.txt
  common/on_action/game_start.txt
  common/on_action/yearly_on_actions.txt
  common/script_values/wc_realm_values.txt
  common/script_values/wc_war_values.txt
  common/scripted_character_templates/wc_horde_templates.txt
  common/scripted_effects/wc_history_effects.txt
  common/scripted_effects/wc_horde_invasion_effects.txt
  common/scripted_effects/wc_war_effects.txt
  common/scripted_triggers/00_succession_triggers.txt
  common/scripted_triggers/wc_horde_invasion_triggers.txt
  common/scripted_triggers/wc_war_triggers.txt
  common/story_cycles/wc_story_cycle_horde_invasion.txt
  common/succession_election/01_princely_elective.txt
  common/succession_election/04_saxon_elective.txt
  common/trigger_localization/00_character_triggers.txt
  events/story_cycles/wc_story_cycle_horde_invasion_events.txt
  gfx/interface/illustrations/decisions/orcish_horde_army.dds
  gfx/interface/illustrations/event_scenes/wc_dark_portal.dds
  gfx/interface/illustrations/event_scenes/wc_stranglethorn.dds
  history/characters/10000_orc.txt
  history/titles/00_wc_other_titles.txt
  localization/english/culture/wc_culture_titles_l_english.yml
  localization/english/dynasties/wc_dynasty_names_l_english.yml
  localization/english/names/wc_character_names_l_english.yml
  localization/english/triggers/wc_character_triggers_l_english.yml
  localization/english/wc_general_l_english.yml
  localization/english/wc_horde_invasion_l_english.yml
  localization/english/wc_nicknames_l_english.yml
  localization/english/wc_other_titles_l_english.yml
  localization/german/culture/wc_culture_titles_l_german.yml
  localization/german/wc_nicknames_l_german.yml
  localization/german/wc_other_titles_l_german.yml
  localization/replace/english/wc_replacements_l_english.yml
Labels: :art: 2D graphics :paintbrush:, :books: lore :books:, :exclamation: priority critical, :page_facing_up: localisation :pen:, :star: new feature :new:

#122 Orcish Elective Prefer Martial and Prowess
  common/religion/religions/fel_group.txt
  common/scripted_modifiers/00_elective_successions_scripted_modifiers.txt
  localization/english/wc_general_l_english.yml
Labels: :balance_scale: balance :balance_scale:, :books: lore :books:, :exclamation: priority high

#126 Made Dwarves A Bit Taller
  common/ethnicities/wc_ethnicities_dwarven.txt
  common/ethnicities/wc_ethnicities_orcish.txt
Labels: :art: 3D graphics :triangular_ruler:, :exclamation: priority critical

#130 Troll Hairs
  common/ethnicities/wc_ethnicities_troll.txt
  common/genes/02_genes_accessories_hairstyles.txt
Labels: :art: 3D graphics :triangular_ruler:, :exclamation: priority high

#128 Brow Clipping Fixes
  gfx/models/portraits/attachments/female_eyebrows/female_elven_eyebrows_0.asset
  gfx/models/portraits/attachments/female_eyebrows/female_elven_eyebrows_0.mesh
  gfx/models/portraits/attachments/female_eyebrows/female_elven_eyebrows_0_forward.mesh
  gfx/models/portraits/attachments/female_eyebrows/female_high_elven_eyebrows_0.mesh
  gfx/models/portraits/attachments/female_eyebrows/female_high_elven_eyebrows_0_forward.mesh
  gfx/models/portraits/attachments/male_eyebrows/male_dwarven_eyebrows_0.mesh
  gfx/models/portraits/attachments/male_eyebrows/male_dwarven_eyebrows_0_forward.mesh
  gfx/models/portraits/attachments/male_eyebrows/male_elven_eyebrows_0.asset
  gfx/models/portraits/attachments/male_eyebrows/male_elven_eyebrows_0.mesh
  gfx/models/portraits/attachments/male_eyebrows/male_elven_eyebrows_0_forward.mesh
  gfx/models/portraits/attachments/male_eyebrows/male_high_elven_eyebrows_0.mesh
  gfx/models/portraits/attachments/male_eyebrows/male_high_elven_eyebrows_0_forward.mesh
Labels: :art: 3D graphics :triangular_ruler:, :exclamation: priority critical, :wrench: bug fix :hammer:

#131 Troll Ears
  common/ethnicities/wc_ethnicities_troll.txt
  common/genes/01_genes_morph.txt
  gfx/models/portraits/female_head/blendshapes/female_bs_back_ear_lenght.mesh
  gfx/models/portraits/female_head/female_head.asset
  gfx/models/portraits/male_head/blendshapes/male_bs_back_ear_lenght.mesh
  gfx/models/portraits/male_head/male_head.asset
  localization/english/wc_portraits_l_english.yml
Labels: :art: 3D graphics :triangular_ruler:, :exclamation: priority high

#127 KINDA Vanilla Hairs
  common/ethnicities/wc_ethnicities_dwarven.txt
  common/genes/02_genes_accessories_hairstyles.txt
  common/genes/03_genes_accessories_beards.txt
  gfx/models/portraits/attachments/male_beards/steppe/male_beard_steppe_01_wc/male_beard_steppe_01_wc.asset
  gfx/models/portraits/attachments/male_beards/steppe/male_beard_steppe_01_wc/male_beard_steppe_01_wc.mesh
  gfx/models/portraits/attachments/male_hair/indian/male_hair_indian_01_wc/male_hair_indian_01_wc.asset
  gfx/models/portraits/attachments/male_hair/indian/male_hair_indian_01_wc/male_hair_indian_01_wc.mesh
  gfx/portraits/accessories/beards.txt
  gfx/portraits/accessories/hairstyles.txt
  localization/english/wc_portraits_l_english.yml
Labels: :art: 3D graphics :triangular_ruler:, :exclamation: priority high

#132 Incompatible Magic Trigger
  common/religion/doctrines/wc_doctrines_magic.txt
  common/scripted_triggers/wc_magic_triggers.txt
  common/scripted_triggers/wc_religious_triggers.txt
Labels: :exclamation: priority high, :hammer: maintenance :wrench:

#136 Troll Tusks
  common/ethnicities/wc_ethnicities_troll.txt
  common/genes/01_genes_morph.txt
  common/genes/wc_static_tusks.txt
  gfx/models/portraits/attachments/male_tusks/male_troll_tusks_0/male_troll_tusks_0.asset
  gfx/models/portraits/attachments/male_tusks/male_troll_tusks_0/male_troll_tusks_0.mesh
  gfx/models/portraits/attachments/male_tusks/male_troll_tusks_0/trollmalefaceuppper00_00_hd.dds
  gfx/models/portraits/attachments/male_tusks/male_troll_tusks_1/male_troll_tusks_1.asset
  gfx/models/portraits/attachments/male_tusks/male_troll_tusks_1/male_troll_tusks_1.mesh
  gfx/models/portraits/attachments/male_tusks/male_troll_tusks_2/male_troll_tusks_2.asset
  gfx/models/portraits/attachments/male_tusks/male_troll_tusks_2/male_troll_tusks_2.mesh
  gfx/models/portraits/female_head/blendshapes/female_bs_mouth_fangs.mesh
  gfx/models/portraits/female_head/female_head.asset
  gfx/models/portraits/male_head/blendshapes/male_bs_mouth_fangs.mesh
  gfx/models/portraits/male_head/blendshapes/male_bs_mouth_tusks.mesh
  gfx/models/portraits/male_head/male_head.asset
  gfx/portraits/accessories/wc_tusks.txt
  localization/english/wc_portraits_l_english.yml
Labels: :art: 3D graphics :triangular_ruler:, :exclamation: priority high

#140 Troll Clothes
  common/culture/cultures/troll.txt
  common/genes/05_genes_special_accessories_clothes.txt
  common/scripted_triggers/00_clothing_triggers.txt
  common/scripted_triggers/wc_clothing_triggers.txt
  gfx/portraits/portrait_modifiers/01_clothes.txt
Labels: :art: 3D graphics :triangular_ruler:, :exclamation: priority high

#135 Fixed bug with Shath'Gral faiths not being allowed Ritual Cannibalism.
  common/religion/doctrines/00_core_tenets.txt
Labels: :exclamation: priority high, :wrench: bug fix :hammer:

#134 Ruler Designer Tweaks and Humpbackness
  common/defines/graphic/00_graphics.txt
  common/genes/01_genes_morph.txt
  common/genes/wc_genes_special_eyes.txt
  common/genes/wc_static_tusks.txt
  gfx/models/portraits/attachments/female_tusks/female_orcish_tusks_0.asset
  gfx/models/portraits/attachments/female_tusks/female_orcish_tusks_0.mesh
  gfx/models/portraits/attachments/female_tusks/female_orcish_tusks_1.mesh
  gfx/models/portraits/attachments/male_tusks/male_orcish_tusks_0/male_orcish_tusks_0.mesh
  gfx/models/portraits/attachments/male_tusks/male_orcish_tusks_1/male_orcish_tusks_1.mesh
  gfx/portraits/accessories/wc_tusks.txt
  gfx/portraits/portrait_animations/animations.txt
  gfx/portraits/portrait_modifiers/wc_custom_eyes.txt
  gfx/portraits/portrait_modifiers/wc_custom_tusks.txt
  gfx/portraits/trait_portrait_modifiers/00_trait_modifiers.txt
  gui/window_ruler_designer.gui
  localization/english/wc_portraits_l_english.yml
Labels: :art: 3D graphics :triangular_ruler:, :exclamation: priority critical

#151 Troll Beauty
  common/ethnicities/00_ethnicities_templates.txt
Labels: :art: 3D graphics :triangular_ruler:, :exclamation: priority high

#152 Orcish Beauty
  common/ethnicities/00_ethnicities_templates.txt
Labels: :art: 3D graphics :triangular_ruler:, :exclamation: priority high

#150 Limited Female Jaw
  common/genes/01_genes_morph.txt
Labels: :art: 3D graphics :triangular_ruler:, :exclamation: priority high

#160 Ogre Clothes
  common/culture/cultures/ogre.txt
  common/genes/05_genes_special_accessories_clothes.txt
  common/scripted_triggers/wc_clothing_triggers.txt
  gfx/portraits/portrait_modifiers/01_clothes.txt
  gfx/portraits/portrait_modifiers/01_headgear.txt
  gfx/portraits/portrait_modifiers/01_legwear.txt
Labels: :art: 3D graphics :triangular_ruler:, :grey_exclamation: priority low

#119 Vanilla files
  gui/window_character_lifestyle.gui
  gui/window_faith.gui
  gui/window_faith_creation.gui
Labels: :grey_exclamation: priority low, :hammer: maintenance :wrench:

#120 Magic doctrines
  common/game_concepts/wc_other_game_concepts.txt
  common/game_concepts/wc_racial_game_concepts.txt
  common/religion/doctrines/00_core_tenets.txt
  common/religion/doctrines/wc_doctrines_magic.txt
  common/religion/doctrines/wc_doctrines_special.txt
  common/religion/religions/air_group.txt
  common/religion/religions/ape_group.txt
  common/religion/religions/arcane_group.txt
  common/religion/religions/daradorism.txt
  common/religion/religions/deathbringer.txt
  common/religion/religions/doombringer.txt
  common/religion/religions/druidism_group.txt
  common/religion/religions/earth_group.txt
  common/religion/religions/fel_group.txt
  common/religion/religions/fire_group.txt
  common/religion/religions/grond_group.txt
  common/religion/religions/light_group.txt
  common/religion/religions/lizard_group.txt
  common/religion/religions/loa_group.txt
  common/religion/religions/naarism.txt
  common/religion/religions/necromancy_group.txt
  common/religion/religions/nerub_group.txt
  common/religion/religions/pandaren_religion_group.txt
  common/religion/religions/secular_group.txt
  common/religion/religions/shamanism_group.txt
  common/religion/religions/shathgral_group.txt
  common/religion/religions/titanic_group.txt
  common/religion/religions/void_group.txt
  common/religion/religions/water_group.txt
  common/script_values/wc_magic_doctrines_values.txt
  common/script_values/wc_religion_tenets_values.txt
  common/scripted_triggers/wc_magic_triggers.txt
  common/scripted_triggers/wc_race_triggers.txt
  common/scripted_triggers/wc_religious_triggers.txt
  common/trigger_localization/wc_doctrine_triggers.txt
  common/trigger_localization/wc_religion_triggers.txt
  gfx/interface/icons/faith_doctrine_groups/doctrine_death_magic.dds
  gfx/interface/icons/faith_doctrine_groups/doctrine_disorder_magic.dds
  gfx/interface/icons/faith_doctrine_groups/doctrine_elemental_air_magic.dds
  gfx/interface/icons/faith_doctrine_groups/doctrine_elemental_decay_magic.dds
  gfx/interface/icons/faith_doctrine_groups/doctrine_elemental_earth_magic.dds
  gfx/interface/icons/faith_doctrine_groups/doctrine_elemental_fire_magic.dds
  gfx/interface/icons/faith_doctrine_groups/doctrine_elemental_spirit_magic.dds
  gfx/interface/icons/faith_doctrine_groups/doctrine_elemental_water_magic.dds
  gfx/interface/icons/faith_doctrine_groups/doctrine_life_magic.dds
  gfx/interface/icons/faith_doctrine_groups/doctrine_light_magic.dds
  gfx/interface/icons/faith_doctrine_groups/doctrine_order_magic.dds
  gfx/interface/icons/faith_doctrine_groups/doctrine_shadow_magic.dds
  gfx/interface/icons/faith_doctrines/special_doctrine_elunic_gender_stratification.dds
  gui/window_faith.gui
  gui/window_faith_creation.gui
  localization/english/religion/wc_magic_doctrines_l_english.yml
  localization/english/religion/wc_other_game_concepts_l_english.yml
  localization/english/religion/wc_racial_game_concepts_l_english.yml
Labels: :grey_exclamation: priority low, :star: new feature :new:

#165 Pale Genes
  common/genes/08_genes_special_visual_traits.txt
  gfx/portraits/portrait_modifiers/01_animation_expressions.txt
  gfx/portraits/trait_portrait_modifiers/00_trait_modifiers.txt
Labels: :art: 3D graphics :triangular_ruler:, :exclamation: priority high

#163 Adding stormheim culture and rename vrykuls
  common/culture/cultures/vrykul.txt
  localization/english/culture/wc_cultures_l_english.yml
Labels: :books: lore :books:, :page_facing_up: localisation :pen:, :question: suggestion :question:

#138 Troll Genes
  common/culture/cultures/troll.txt
  common/ethnicities/00_ethnicities_templates.txt
  common/ethnicities/wc_ethnicities_orcish.txt
  common/ethnicities/wc_ethnicities_troll.txt
  common/genes/01_genes_morph.txt
  common/genes/02_genes_accessories_hairstyles.txt
  common/genes/05_genes_special_accessories_clothes.txt
  common/genes/wc_static_tusks.txt
  common/scripted_modifiers/wc_portrait_modifiers.txt
  common/scripted_triggers/00_clothing_triggers.txt
  common/scripted_triggers/wc_clothing_triggers.txt
  common/scripted_triggers/wc_portrait_triggers.txt
  common/scripted_triggers/wc_race_triggers.txt
  gfx/models/portraits/attachments/male_tusks/male_troll_tusks_0/male_troll_tusks_0.asset
  gfx/models/portraits/attachments/male_tusks/male_troll_tusks_0/male_troll_tusks_0.mesh
  gfx/models/portraits/attachments/male_tusks/male_troll_tusks_0/trollmalefaceuppper00_00_hd.dds
  gfx/models/portraits/attachments/male_tusks/male_troll_tusks_1/male_troll_tusks_1.asset
  gfx/models/portraits/attachments/male_tusks/male_troll_tusks_1/male_troll_tusks_1.mesh
  gfx/models/portraits/attachments/male_tusks/male_troll_tusks_2/male_troll_tusks_2.asset
  gfx/models/portraits/attachments/male_tusks/male_troll_tusks_2/male_troll_tusks_2.mesh
  gfx/models/portraits/female_body/blendshapes/female_bs_troll_fingers.mesh
  gfx/models/portraits/female_body/female_body.asset
  gfx/models/portraits/female_body/girl_body.asset
  gfx/models/portraits/female_head/blendshapes/female_bs_back_ear_lenght.mesh
  gfx/models/portraits/female_head/blendshapes/female_bs_mouth_fangs.mesh
  gfx/models/portraits/female_head/female_head.asset
  gfx/models/portraits/male_body/blendshapes/male_bs_troll_fingers.mesh
  gfx/models/portraits/male_body/boy_body.asset
  gfx/models/portraits/male_body/male_body.asset
  gfx/models/portraits/male_head/blendshapes/male_bs_back_ear_lenght.mesh
  gfx/models/portraits/male_head/blendshapes/male_bs_mouth_fangs.mesh
  gfx/models/portraits/male_head/blendshapes/male_bs_mouth_tusks.mesh
  gfx/models/portraits/male_head/male_head.asset
  gfx/portraits/accessories/wc_tusks.txt
  gfx/portraits/portrait_modifiers/01_cloaks.txt
  gfx/portraits/portrait_modifiers/01_clothes.txt
  gfx/portraits/portrait_modifiers/01_event_hair.txt
  gfx/portraits/portrait_modifiers/01_hairstyles.txt
  gfx/portraits/portrait_modifiers/01_headgear.txt
  gfx/portraits/portrait_modifiers/01_legwear.txt
  localization/english/wc_portraits_l_english.yml
Labels: :art: 3D graphics :triangular_ruler:, :exclamation: priority critical

#156 Basic Undead Trait
  common/customizable_localization/00_insult_custom_loc.txt
  common/opinion_modifiers/wc_doctrinal_crime_opinions.txt
  common/religion/doctrines/wc_doctrines_magic.txt
  common/religion/doctrines/wc_doctrines_special.txt
  common/religion/religions/shamanism_group.txt
  common/scripted_triggers/00_religious_triggers.txt
  common/traits/wc_undead_trait.txt
  gfx/interface/icons/faith_doctrines/special_doctrine_earth_mother_mercy.dds
  gfx/interface/icons/traits/being_undead.dds
  gfx/portraits/trait_portrait_modifiers/wc_undead_modifier.txt
  gui/shared/icons.gui
  gui/shared/wc_colors.gui
  history/characters/42000_high_elf.txt
  history/characters/60000_63000_lordaeronian.txt
  localization/english/custom_localization/insult_custom_loc_l_english.yml
  localization/english/opinions/wc_general_opinions_l_english.yml
  localization/english/religion/wc_core_tenets_l_english.yml
  localization/english/religion/wc_magic_doctrines_l_english.yml
  localization/english/wc_traits_l_english.yml
Labels: :art: 3D graphics :triangular_ruler:, :books: lore :books:, :grey_exclamation: priority medium, :star: new feature :new:

#147 Less Likely Interracial AI
  common/character_interactions/00_marriage_interactions.txt
  common/character_interactions/00_scheme_interactions.txt
  common/schemes/convert_to_witchcraft_scheme.txt
  common/schemes/court_scheme.txt
  common/schemes/seduce_scheme.txt
  common/script_values/wc_race_values.txt
  common/scripted_effects/00_courtier_guest_management_effects.txt
  common/scripted_modifiers/00_marriage_scripted_modifiers.txt
  common/scripted_modifiers/00_romance_and_seduction_scripted_modifiers.txt
  common/scripted_modifiers/wc_race_modifiers.txt
  common/scripted_triggers/00_childhood_triggers.txt
  common/scripted_triggers/00_marriage_triggers.txt
  common/scripted_triggers/00_relation_triggers.txt
  common/scripted_triggers/00_romance_and_seduction_triggers.txt
  common/scripted_triggers/wc_race_triggers.txt
  common/trigger_localization/wc_tooltip_triggers.txt
  events/activities/feast_activity/main_events/feast_default_events.txt
  events/activities/pilgrimage_activity/pilgrimage_events.txt
  events/education_and_childhood/childhood_events.txt
  events/lifestyles/intrigue_lifestyle/intrigue_temptation_events.txt
  events/lifestyles/intrigue_lifestyle/intrigue_temptation_events_2.txt
  events/lifestyles/statecraft_lifestyle/diplomacy_foreign_events.txt
  events/lifestyles/warfare_lifestyle/martial_authority_events.txt
  events/relations_events/vassal_events.txt
  events/scheme_events/fabricate_hook_scheme/fabricate_hook_ongoing_events.txt
  events/stress_events/stress_threshold_special_events.txt
  events/stress_events/stress_trait_ongoing_events.txt
  events/witch_events.txt
  events/yearly_events/yearly_events.txt
  events/yearly_events/yearly_events_2.txt
  events/yearly_events/yearly_events_3.txt
  events/yearly_events/yearly_events_4.txt
  events/yearly_events/yearly_events_5.txt
  localization/english/wc_tooltip_l_english.yml
Labels: :balance_scale: balance :balance_scale:, :books: lore :books:, :exclamation: priority high

#168 Uther Beard
  gfx/models/portraits/attachments/male_beards/western/male_beard_western_09/male_beard_western_09_normal_wc.dds
  gfx/models/portraits/attachments/male_beards/western/male_beard_western_09/male_beard_western_09_wc.asset
  gfx/models/portraits/attachments/male_beards/western/male_beard_western_09_wc/male_beard_western_09_bs_fat_wc.mesh
  gfx/models/portraits/attachments/male_beards/western/male_beard_western_09_wc/male_beard_western_09_bs_old_wc.mesh
  gfx/models/portraits/attachments/male_beards/western/male_beard_western_09_wc/male_beard_western_09_diffuse_wc.dds
  gfx/models/portraits/attachments/male_beards/western/male_beard_western_09_wc/male_beard_western_09_wc.mesh
  gfx/models/portraits/attachments/male_beards/western/male_beard_western_09_wc/male_beard_western_09_wc_properties.dds
Labels: :art: 3D graphics :triangular_ruler:, :exclamation: priority high, :star: new feature :new:

#173 Orcish Renames
  common/culture/cultures/ogre.txt
  common/culture/cultures/orc.txt
  common/ethnicities/wc_ethnicities_orcish.txt
  common/ethnicities/wc_ethnicities_orcish_rework.txt
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#149 Night Elf Ethnicity Rework
  common/culture/cultures/elf.txt
  common/ethnicities/wc_ethnicities_elven.txt
  common/genes/02_genes_accessories_hairstyles.txt
  localization/english/wc_portraits_l_english.yml
Labels: :art: 3D graphics :triangular_ruler:, :exclamation: priority high

#177 Uther Birth Year Fix
  history/characters/60000_63000_lordaeronian.txt
Labels: :books: lore :books:, :question: suggestion :question:

#178 Human Gray
  common/genes/01_genes_morph.txt
Labels: :art: 3D graphics :triangular_ruler:, :balance_scale: balance :balance_scale:, :exclamation: priority high

#167 Vrykul Ethnicity
  common/culture/cultures/vrykul.txt
  common/ethnicities/wc_ethnicities_vrykul.txt
  common/genes/02_genes_accessories_hairstyles.txt
  common/genes/03_genes_accessories_beards.txt
  common/modifiers/wc_event_modifiers.txt
  common/scripted_effects/wc_race_effects.txt
  common/scripted_modifiers/wc_portrait_modifiers.txt
  common/scripted_triggers/wc_race_triggers.txt
  common/traits/wc_race_traits.txt
  events/wc_events/wc_race_events.txt
  gfx/portraits/trait_portrait_modifiers/wc_undead_modifier.txt
  history/characters/100000_vrykul.txt
  localization/english/wc_general_l_english.yml
  localization/english/wc_portraits_l_english.yml
Labels: :art: 3D graphics :triangular_ruler:, :exclamation: priority high, :star: new feature :new:

#179 Custom Uther Hairstyle
  common/genes/02_genes_accessories_hairstyles.txt
  gfx/models/portraits/attachments/male_hair/western/male_hair_western_07/male_hair_western_07_normal_wc.dds
  gfx/models/portraits/attachments/male_hair/western/male_hair_western_07/male_hair_western_07_wc.asset
  gfx/portraits/accessories/hairstyles.txt
  gfx/portraits/portrait_modifiers/wc_scripted_appearances.txt
Labels: :art: 3D graphics :triangular_ruler:, :star: new feature :new:, :x: doubtful :question:

#183 Undead Trait Fix
  gfx/portraits/trait_portrait_modifiers/wc_undead_modifier.txt
Labels: :beetle: bug :beetle:, :x: doubtful :question:

#189 Important Lore Character
  common/modifiers/wc_event_modifiers.txt
  common/scripted_effects/wc_health_effects.txt
  events/game_rule_events.txt
  history/characters/10000_orc.txt
  history/characters/11000_dark_iron.txt
  history/characters/1_azerothian.txt
  history/characters/22000_wildhammer.txt
  history/characters/340000_night_elf.txt
  history/characters/360000_eredruin.txt
  history/characters/38000_arathorian.txt
  history/characters/42000_high_elf.txt
  history/characters/430000_nathrezim.txt
  history/characters/46000_gilnean.txt
  history/characters/48000_tirassian.txt
  history/characters/52000_ogre.txt
  history/characters/57000_amani.txt
  history/characters/59000_dalaranian.txt
  history/characters/60000_63000_lordaeronian.txt
  history/characters/62000_dragon.txt
  history/characters/68000_darkspear.txt
  localization/english/wc_general_l_english.yml
Labels: :balance_scale: balance :balance_scale:, :grey_exclamation: priority medium

#154 High Elf Ethnicity Rework
  common/ethnicities/wc_ethnicities_elven.txt
Labels: :art: 3D graphics :triangular_ruler:, :grey_exclamation: priority medium

#187 Generated Random Locators
  gfx/map/map_object_data/audio_emitters.txt
  gfx/map/map_object_data/building_locators.txt
  gfx/map/map_object_data/coast_foam_layer.txt
  gfx/map/map_object_data/combat_locators.txt
  gfx/map/map_object_data/env_effects.txt
  gfx/map/map_object_data/game_object_layers.txt
  gfx/map/map_object_data/layers.txt
  gfx/map/map_object_data/other_stack_locators.txt
  gfx/map/map_object_data/player_stack_locators.txt
  gfx/map/map_object_data/siege_locators.txt
  gfx/map/map_object_data/special_building_locators.txt
  gfx/map/map_object_data/test_objects.txt
  tools/mapeditor/nudger_progress.txt
  tools/mapeditor/nudger_settings.json
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#129 CoA Fixes
  common/coat_of_arms/template_lists/coa_templates.txt
  common/coat_of_arms/template_lists/color_lists.txt
  common/coat_of_arms/template_lists/colored_emblem_lists.txt
  common/culture/cultures/hozen.txt
  common/culture/cultures/human.txt
  common/culture/cultures/jinyu.txt
  common/culture/cultures/mogu.txt
  common/culture/cultures/pandaren.txt
  common/culture/cultures/tauren.txt
  common/culture/cultures/trogg.txt
  common/scripted_triggers/00_coa_triggers.txt
  common/scripted_triggers/wc_coa_triggers.txt
  common/scripted_triggers/wc_religious_triggers.txt
Labels: :grey_exclamation: priority medium, :wrench: bug fix :hammer:

#191 Updated the ages for Magni, Muradin, and Brann to more lore-friendly …
  history/characters/17000_28000_bronzebeard.txt
Labels: :books: lore :books:, :exclamation: priority high

#195 Fel Orc Trait Modifier
  gfx/portraits/trait_portrait_modifiers/wc_fel_orc_modifier.txt
Labels: :art: 3D graphics :triangular_ruler:, :question: suggestion :question:, :star: new feature :new:

#193 Elf Clothing Sets
  common/culture/cultures/elf.txt
  common/culture/cultures/troll.txt
  common/genes/06_genes_special_accessories_headgear.txt
  common/scripted_triggers/wc_clothing_triggers.txt
  common/scripted_triggers/wc_portrait_triggers.txt
  gfx/models/portraits/attachments/female_clothes/secular/steppe/nobility_01/female_clothing_secular_steppe_nobility_01.asset
  gfx/models/portraits/attachments/female_clothes/secular/steppe/nobility_02/female_clothes_secular_steppe_nobility_02.asset
  gfx/models/portraits/attachments/male_clothes/secular/steppe/nobility_01/male_clothes_secular_steppe_nobility_01.asset
  gfx/models/portraits/attachments/male_clothes/secular/steppe/nobility_02/male_clothes_secular_steppe_nobility_02.asset
  gfx/portraits/accessory_variations/textures/color_palette_steppe_clothing_high_nobility_01.dds
  gfx/portraits/portrait_modifiers/01_cloaks.txt
  gfx/portraits/portrait_modifiers/01_clothes.txt
  gfx/portraits/portrait_modifiers/01_headgear.txt
  gfx/portraits/portrait_modifiers/01_legwear.txt
Labels: :art: 3D graphics :triangular_ruler:, :grey_exclamation: priority medium, :star: new feature :new:

#182 No Randomly Generated Families for Lore-Important Characters
  common/modifiers/wc_event_modifiers.txt
  common/scripted_effects/wc_health_effects.txt
  events/game_rule_events.txt
  history/characters/10000_orc.txt
  history/characters/11000_dark_iron.txt
  history/characters/1_azerothian.txt
  history/characters/22000_wildhammer.txt
  history/characters/340000_night_elf.txt
  history/characters/360000_eredruin.txt
  history/characters/38000_arathorian.txt
  history/characters/42000_high_elf.txt
  history/characters/430000_nathrezim.txt
  history/characters/46000_gilnean.txt
  history/characters/48000_tirassian.txt
  history/characters/52000_ogre.txt
  history/characters/57000_amani.txt
  history/characters/59000_dalaranian.txt
  history/characters/60000_63000_lordaeronian.txt
  history/characters/62000_dragon.txt
  history/characters/68000_darkspear.txt
  localization/english/wc_general_l_english.yml
Labels: :books: lore :books:, :question: suggestion :question:, :x: info needed :page_facing_up:

#146 Gnome Ethnicity
  common/culture/cultures/gnome.txt
  common/ethnicities/wc_ethnicities_gnome.txt
  common/genes/02_genes_accessories_hairstyles.txt
  common/genes/03_genes_accessories_beards.txt
  common/scripted_triggers/wc_race_triggers.txt
  common/traits/wc_race_traits.txt
Labels: :art: 3D graphics :triangular_ruler:, :exclamation: priority high, :star: new feature :new:

#196 Gnome Ethnicity Localization
  localization/english/wc_portraits_l_english.yml
Labels: :page_facing_up: localisation :pen:

#190 2nd Bug Crusade
  common/casus_belli_types/00_claim.txt
  common/casus_belli_types/00_invasion_war.txt
  common/character_interactions/00_prison_interactions.txt
  common/customizable_localization/00_DE_mottos.txt
  common/landed_titles/wc_religious_titles.txt
  common/religion/doctrines/00_core_tenets.txt
  common/religion/doctrines/00_doctrines_islam.txt
  common/religion/religions/arcane_group.txt
  common/scripted_effects/00_decisions_effects.txt
  common/scripted_modifiers/00_elective_successions_scripted_modifiers.txt
  common/scripted_triggers/00_title_triggers.txt
  common/scripted_triggers/wc_culture_triggers.txt
  common/traits/00_traits.txt
  events/activities/pilgrimage_activity/pilgrimage_events.txt
  events/global_religion_events.txt
  events/lifestyles/scholarship_lifestyle/learning_theology_events.txt
  events/lifestyles/warfare_lifestyle/warhorse_events.txt
  events/war_events/knight_events.txt
  gfx/models/portraits/attachments/male_hair/indian/male_hair_indian_01_wc/male_hair_indian_01_wc.mesh
  gfx/models/portraits/direfurbolg/direfurbolg.asset
  gfx/models/portraits/direfurbolg/direfurbolg_black.dds
  gfx/models/portraits/direfurbolg/direfurbolg_black.png
  gfx/models/portraits/direfurbolg/direfurbolg_blue.dds
  gfx/models/portraits/direfurbolg/direfurbolg_blue.png
  gfx/models/portraits/direfurbolg/direfurbolg_brown.dds
  gfx/models/portraits/direfurbolg/direfurbolg_brown.png
  gfx/models/portraits/direfurbolg/direfurbolg_red.dds
  gfx/models/portraits/direfurbolg/direfurbolg_red.png
  gfx/models/portraits/direfurbolg/direfurbolg_white.dds
  gfx/models/portraits/direfurbolg/direfurbolg_white.png
  history/characters/42000_high_elf.txt
  history/provinces/00_k_quelthalas.txt
  history/titles/00_wc_religious_head_titles.txt
  history/titles/k_quelthalas.txt
  localization/english/wc_other_titles_l_english.yml
  localization/english/wc_tooltip_l_english.yml
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#198 One Blind Eye
  common/genes/04_genes_accessories_misc.txt
  common/genes/08_genes_special_visual_traits.txt
  common/scripted_triggers/wc_clothing_triggers.txt
  gfx/models/portraits/decals/visual_traits/decal_eye_scar_diffuse.dds
  gfx/models/portraits/decals/visual_traits/decal_eye_scar_normal.dds
  gfx/models/portraits/decals/visual_traits/decal_eye_scar_properties.dds
  gfx/models/portraits/female_head/female_eyes.asset
  gfx/models/portraits/female_head/female_eyes.mesh
  gfx/models/portraits/male_head/male_eyes.asset
  gfx/models/portraits/male_head/male_eyes.mesh
  gfx/models/portraits/male_head/male_eyes_blind_diffuse.dds
  gfx/portraits/accessories/bodyparts.txt
  gfx/portraits/accessories/headgear.txt
  gfx/portraits/accessories/wc_eyebrows.txt
  gfx/portraits/trait_portrait_modifiers/00_trait_modifiers.txt
Labels: :art: 3D graphics :triangular_ruler:, :exclamation: priority high

#201 Dwarven Brow Inner Height
  gfx/models/portraits/attachments/male_eyebrows/male_dwarven_eyebrows_0.mesh
  gfx/models/portraits/attachments/male_eyebrows/male_dwarven_eyebrows_0_inner_down.mesh
  gfx/models/portraits/attachments/male_eyebrows/male_dwarven_eyebrows_0_inner_up.mesh
  gfx/models/portraits/attachments/male_eyebrows/male_dwarven_eyebrows_0_outer_down.mesh
  gfx/models/portraits/attachments/male_eyebrows/male_elven_eyebrows_0.asset
Labels: :art: 3D graphics :triangular_ruler:, :exclamation: priority high

#202 3rd Bug Crusade
  common/on_action/game_start.txt
  history/characters/10000_orc.txt
  history/characters/11000_dark_iron.txt
  history/characters/16000_gnome.txt
  history/characters/1_azerothian.txt
  history/characters/210000_tauren.txt
  history/characters/270000_tolvir.txt
  history/characters/310000_patron_characters.txt
  history/characters/330000_highborne.txt
  history/characters/340000_night_elf.txt
  history/characters/381000_vulpera.txt
  history/characters/400000_titan.txt
  history/characters/420000_ancients.txt
  history/characters/42000_high_elf.txt
  history/characters/430000_nathrezim.txt
  history/characters/46000_gilnean.txt
  history/characters/48000_tirassian.txt
  history/characters/520000_mogu.txt
  history/characters/52000_ogre.txt
  history/characters/53000_hillsbrad.txt
  history/characters/58000_alteraci.txt
  history/characters/59000_dalaranian.txt
  history/characters/60000_63000_lordaeronian.txt
  history/characters/62000_dragon.txt
  history/characters/66000_zandalari.txt
  history/characters/76000_nerubian.txt
  history/characters/90000_pirate.txt
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#207 Custom Loading Icon
  gfx/interface/frontend/ck3_logo_banner.dds
Labels: :art: 2D graphics :paintbrush:, :grey_exclamation: priority low, :question: suggestion :question:

#204 Khadgar Historical Entry
  history/characters/59000_dalaranian.txt
Labels: :construction: WIP :construction:, :question: suggestion :question:, :x: info needed :page_facing_up:

#188 Ogre Beards and Hairstyles
  common/ethnicities/wc_ethnicities_ogre.txt
  common/genes/02_genes_accessories_hairstyles.txt
  common/genes/03_genes_accessories_beards.txt
  common/scripted_modifiers/wc_portrait_modifiers.txt
Labels: :art: 3D graphics :triangular_ruler:, :construction: WIP :construction:, :grey_exclamation: priority medium, :star: new feature :new:

#200 Dwarven Ethnicity Rework
  common/ethnicities/wc_ethnicities_dwarven.txt
Labels: :art: 3D graphics :triangular_ruler:, :grey_exclamation: priority medium, :question: suggestion :question:

#213 Scripted Appearance
  common/character_interactions/00_scheme_interactions.txt
  common/courtier_guest_management/guest_management.txt
  common/customizable_localization/00_compliment_custom_loc.txt
  common/customizable_localization/00_feast_custom_loc.txt
  common/customizable_localization/00_generic_character_words.txt
  common/customizable_localization/00_insult_custom_loc.txt
  common/customizable_localization/00_ruler_transition_loc.txt
  common/decisions/80_major_decisions.txt
  common/on_action/child_birth_on_actions.txt
  common/schemes/court_scheme.txt
  common/schemes/seduce_scheme.txt
  common/script_values/01_dynamic_values.txt
  common/scripted_effects/wc_health_effects.txt
  common/scripted_effects/wc_portrait_effects.txt
  common/scripted_triggers/00_scripted_triggers.txt
  common/scripted_triggers/wc_portrait_triggers.txt
  common/traits/00_traits.txt
  common/traits/wc_lore_trait.txt
  events/activities/feast_activity/main_events/feast_main_stew_flood_events.txt
  events/activities/hunt_activity/hunt_events.txt
  events/activities/pilgrimage_activity/hajj_events.txt
  events/birth_events.txt
  events/courtier_guest_management_events/courtier_guest_management_events.txt
  events/lifestyles/intrigue_lifestyle/intrigue_temptation_events.txt
  events/lifestyles/statecraft_lifestyle/diplomacy_generic_events.txt
  events/lifestyles/statecraft_lifestyle/diplomacy_majesty_events.txt
  events/scheme_events/seduce_scheme/seduce_ongoing_events.txt
  events/witch_events.txt
  events/yearly_events/yearly_events_2.txt
  gfx/portraits/portrait_modifiers/01_weight.txt
  history/characters/42000_high_elf.txt
Labels: :art: 3D graphics :triangular_ruler:, :books: lore :books:, :grey_exclamation: priority medium
