Repository Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2, pull requests merged in 2021-12, with the labels that each got.

#781 Silver Hand Order
  common/decisions/00_holy_order_decisions.txt
  common/landed_titles/wc_holy_orders.txt
  common/on_action/game_start.txt
  common/scripted_effects/00_decisions_effects.txt
  common/scripted_effects/wc_religious_effects.txt
  events/religion_events/wc_holy_order_events.txt
  history/titles/000_wc_other_titles.txt
  history/titles/00_k_lordaeron.txt
  history/titles/00_k_stratholme.txt
Labels: lore :books:, vanilla modification :icecream:, priority critical :exclamation:, history 👑

#734 Lich King's Mind Control
  common/character_interactions/00_alliance.txt
  common/character_interactions/00_blackmail_interactions.txt
  common/character_interactions/00_character_interactions.txt
  common/character_interactions/00_courtier_and_guest_interactions.txt
  common/character_interactions/00_dynast_interactions.txt
  common/character_interactions/00_education_interactions.txt
  common/character_interactions/00_gift.txt
  common/character_interactions/00_house_head_interactions.txt
  common/character_interactions/00_invite_agent_to_scheme.txt
  common/character_interactions/00_marriage_interactions.txt
  common/character_interactions/00_perk_interactions.txt
  common/character_interactions/00_prison_interactions.txt
  common/character_interactions/00_religious_interactions.txt
  common/character_interactions/00_revoke_title_interaction.txt
  common/character_interactions/00_vassal_interactions.txt
  common/character_interactions/00_war.txt
  common/character_interactions/01_fp1_interactions.txt
  common/factions/00_factions.txt
  common/factions/00_peasant_faction_new.txt
  common/factions/00_populist_faction.txt
  common/scripted_modifiers/wc_scourge_invasion_modifiers.txt
  common/scripted_triggers/wc_being_triggers.txt
  common/traits/wc_special_traits.txt
  localization/english/wc_character_interactions_l_english.yml
  localization/english/wc_traits_l_english.yml
Labels: new feature :star:, lore :books:, priority low :grey_exclamation:

#771 Historical revisionism 3
  history/characters/10000_orc.txt
  history/characters/15000_gurubashi.txt
  history/characters/400000_titan.txt
  history/characters/410000_dryad.txt
  history/characters/6000_gurubashi.txt
  history/characters/62000_dragon.txt
  history/characters/76000_nerubian.txt
Labels: priority medium :grey_exclamation:, history 👑

#789 Update frostnymph history
  history/cultures/frostnymph.txt
Labels: bug :bug:

#791 Changed virtues and traits for element faiths
  common/religion/religions/air_group.txt
  common/religion/religions/earth_group.txt
  common/religion/religions/fire_group.txt
  common/religion/religions/water_group.txt
Labels: lore :books:, priority low :grey_exclamation:, balance :balance_scale:, good first issue

#769 Limited some Maa's mercenary presence
  common/culture/innovations/wc_cultural_innovations.txt
  common/men_at_arms_types/_men_at_arms_types.info
  common/men_at_arms_types/wc_cultural_maa_types.txt
  common/religion/doctrines/wc_doctrines_special.txt
  history/cultures/annihilan.txt
  history/cultures/aqir_group.txt
  history/cultures/demonic_group.txt
  history/cultures/eredar.txt
  history/cultures/eredruin.txt
  history/cultures/nathrezim.txt
  history/cultures/satyr.txt
  history/cultures/shivarra.txt
  history/cultures/undead_group.txt
  localization/english/culture/wc_cultural_innovations_l_english.yml
Labels: bug fix :hammer:, priority medium :grey_exclamation:, WIP :construction:, cultural :mortar_board:

#804 Barov and Sylvanas Makeup Fix
  gfx/portraits/portrait_modifiers/wc_facial_markings.txt
  gfx/portraits/trait_portrait_modifiers/wc_undead_modifier.txt
Labels: bug fix :hammer:, priority high :exclamation:, character designing 😶
