Repository Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2, pull requests merged in 2021-05, with the labels that each got.

#364 Relocation of the files gui, opinions, game concepts into respective folders
  localization/english/gui/wc_gui_l_english.yml
  localization/english/opinions/wc_opinions_l_english.yml
  localization/english/wc_other_game_concepts_l_english.yml
  localization/english/wc_racial_game_concepts_l_english.yml
  localization/german/gui/wc_gui_l_german.yml
  localization/german/opinions/wc_opinions_l_german.yml
Labels: :page_facing_up: localisation :pen:

#367 Scourge Set Names
  common/culture/cultures/undead.txt
  localization/english/names/wc_character_names_l_english.yml
Labels: :exclamation: priority critical, :page_facing_up: localisation :pen:

#369 Southshore Issue
  history/titles/000_wc_other_titles.txt
  history/titles/000_wc_religious_head_titles.txt
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#368 Scheme Opinion
  common/scripted_effects/00_murder_scheme_effects.txt
  common/scripted_effects/wc_scheme_effects.txt
  events/scheme_events/hostile_scheme_discovery_events.txt
  events/scheme_events/murder_scheme/murder_outcome_events.txt
  events/scheme_events/stasis_trap_scheme/wc_stasis_trap_outcome_events.txt
Labels: :exclamation: priority critical, :hammer: maintenance :wrench:

#371 Sorted Northern Names
  common/culture/cultures/human.txt
  history/characters/260000_northern.txt
  history/titles/00_k_grizzly_hills.txt
  history/titles/00_k_howling_fjord.txt
  history/titles/00_k_sholazar_basin.txt
Labels: :page_facing_up: localisation :pen:

#345 Less Magic Values
  common/focuses/wc_magic_lifestyle_focuses.txt
  common/lifestyle_perks/wc_death_magic_perks.txt
  common/lifestyle_perks/wc_disorder_magic_perks.txt
  common/lifestyle_perks/wc_elemental_air_magic_perks.txt
  common/lifestyle_perks/wc_elemental_earth_magic_perks.txt
  common/lifestyle_perks/wc_elemental_fire_magic_perks.txt
  common/lifestyle_perks/wc_elemental_water_magic_perks.txt
  common/lifestyle_perks/wc_life_magic_perks.txt
  common/lifestyle_perks/wc_light_magic_perks.txt
  common/lifestyle_perks/wc_order_magic_perks.txt
  common/lifestyle_perks/wc_shadow_magic_perks.txt
  common/script_values/wc_magic_lifestyles_values.txt
  common/scripted_triggers/wc_magic_lifestyles_triggers.txt
  common/scripted_triggers/wc_magic_triggers.txt
Labels: :exclamation: priority high, :hammer: maintenance :wrench:

#376 Copied Russian Dynasty Names
  common/culture/cultures/human.txt
Labels: :grey_exclamation: priority medium, :page_facing_up: localisation :pen:, :star: new feature :new:, 🔰good first testing🧪

#372 Masonry Faith
  common/religion/holy_sites/wc_holy_sites.txt
  common/religion/religions/light_group.txt
  gfx/interface/icons/faith/wccc_holy_light_orange.dds
  history/characters/1_azerothian.txt
  history/provinces/00_k_stormwind.txt
  localization/english/religion/wc_religion_l_english.yml
Labels: :art: 2D graphics :paintbrush:, :books: lore :books:, :grey_exclamation: priority low, :page_facing_up: localisation :pen:, :star: new feature :new:

#384 hostile_scheme_opinion_effect Can Accept Schemes
  common/scripted_effects/wc_scheme_effects.txt
  events/scheme_events/hostile_scheme_discovery_events.txt
Labels: :exclamation: priority critical, :hammer: maintenance :wrench:

#383 More Life Spans
  common/script_values/wc_age_values.txt
  common/scripted_triggers/wc_race_triggers.txt
  common/traits/wc_race_traits.txt
  history/characters/540000_mantid.txt
  history/titles/000_wc_other_titles.txt
  history/titles/00_k_kyparqov.txt
Labels: :balance_scale: balance :balance_scale:, :books: lore :books:, :exclamation: priority high

#385 Mantid Names
  common/culture/cultures/aqir.txt
  history/characters/540000_mantid.txt
  history/titles/000_wc_religious_head_titles.txt
  history/titles/00_k_kyparqov.txt
  history/titles/00_k_townlong.txt
  localization/english/names/wc_character_names_l_english.yml
Labels: :books: lore :books:, :exclamation: priority critical, :page_facing_up: localisation :pen:

#389 nightelf magical eyes
  common/ethnicities/wc_ethnicities_elven.txt
  gfx/portraits/trait_portrait_modifiers/00_trait_modifiers.txt
Labels: :art:character designing😶, :grey_exclamation: priority low, 🔰good first testing🧪
