Repository Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2, pull requests merged in 2022-01, with the labels that each got.

#818 Typo Fixes
  localization/english/culture/wc_cultural_maa_innovations_l_english.yml
  localization/english/culture/wc_regional_innovations_l_english.yml
  localization/english/event_localization/wc_draenor_events_l_english.yml
  localization/english/religion/wc_religion_l_english.yml
  localization/english/wc_holy_orders_l_english.yml
  localization/english/wc_pol_faction_l_english.yml
  localization/english/wc_portraits_l_english.yml
  localization/english/wc_regiment_l_english.yml
  localization/english/wc_traits_l_english.yml
Labels: localisation :page_facing_up:, priority medium :grey_exclamation:

#815 Lordaeron Throne Room
  common/event_backgrounds/01_event_backgrounds.txt
  common/event_backgrounds/wc_event_backgrounds.txt
  common/scripted_triggers/wc_illustration_triggers.txt
  gfx/interface/illustrations/character_view/wc_lordaeron_throne_room.dds
  gfx/interface/illustrations/scripted_illustrations/ingame.txt
  gfx/portraits/environments/wc_portrait_environments.txt
Labels: priority medium :grey_exclamation:, 2D graphics :paintbrush:, interface 👁‍🗨

#829 [Issue #795] Tidehunters now counter Caster
  common/men_at_arms_types/wc_cultural_maa_types.txt
Labels: bug fix :hammer:, priority critical :exclamation:

#830 [Issue #805] Stormwind name now appears
  localization/english/religion/wc_holy_sites_l_english.yml
  localization/french/religion/wc_holy_sites_l_french.yml
  localization/german/religion/wc_holy_sites_l_german.yml
Labels: bug fix :hammer:, localisation :page_facing_up:, priority high :exclamation:

#822 Naked Bugfix
  common/scripted_triggers/wc_clothing_triggers.txt
  gfx/portraits/portrait_modifiers/01_clothes.txt
  gfx/portraits/portrait_modifiers/01_headgear.txt
Labels: priority critical :exclamation:, bug :bug:, character designing 😶

#580 Succubi Ethnicity
  .artist_resources/portraits/succubus2red.xcf
  common/culture/cultures/demonic.txt
  common/ethnicities/wc_ethnicities_demonic.txt
  common/ethnicities/wc_ethnicities_elven.txt
  common/genes/03_genes_special_accessories_hairstyles.txt
  common/genes/04_genes_special_accessories_beards.txt
  common/genes/wc_gene_body_markings.txt
  common/genes/wc_gene_facial_markings.txt
  common/genes/wc_genes_legs.txt
  common/genes/wc_genes_skin.txt
  common/genes/wc_genes_tail.txt
  common/scripted_modifiers/wc_portrait_modifiers.txt
  common/scripted_triggers/wc_clothing_triggers.txt
  common/scripted_triggers/wc_portrait_triggers.txt
  gfx/models/portraits/attachments/female_legs/female_legs_succubus_0/wc_female_legs_succubus_0.asset
  gfx/models/portraits/attachments/female_legs/female_legs_succubus_0/wc_female_legs_succubus_0.mesh
  gfx/models/portraits/attachments/female_tail/female_tail_succubus_0/succubus2red.dds
  gfx/models/portraits/attachments/female_tail/female_tail_succubus_0/wc_female_tail_succubus_0.asset
  gfx/models/portraits/attachments/female_tail/female_tail_succubus_0/wc_female_tail_succubus_0.mesh
  gfx/models/portraits/attachments/male_legs/male_legs_succubus_0/wc_male_legs_succubus_0.asset
  gfx/models/portraits/attachments/male_legs/male_legs_succubus_0/wc_male_legs_succubus_0.mesh
  gfx/models/portraits/attachments/male_tail/male_tail_succubus_0/wc_male_tail_succubus_0.asset
  gfx/models/portraits/attachments/male_tail/male_tail_succubus_0/wc_male_tail_succubus_0.mesh
  gfx/models/portraits/decals/body/succubus_leg_skin.dds
  gfx/models/portraits/decals/body/succubus_leg_skin_normal.dds
  gfx/models/portraits/decals/body/succubus_leg_skin_properties.dds
  gfx/models/portraits/decals/makeup/decal_succubus_eyeliner.dds
  gfx/models/portraits/decals/succubus_markings/decal_succubus_arm.dds
  gfx/models/portraits/decals/succubus_markings/decal_succubus_marking_01.dds
  gfx/models/portraits/decals/succubus_markings/decal_succubus_marking_02.dds
  gfx/models/portraits/decals/succubus_markings/decal_succubus_marking_03.dds
  gfx/models/portraits/decals/succubus_markings/decal_succubus_marking_04.dds
  gfx/portraits/accessories/wc_legs.txt
  gfx/portraits/accessories/wc_tail.txt
  gfx/portraits/portrait_modifiers/01_beards.txt
  gfx/portraits/portrait_modifiers/01_custom_beards.txt
  gfx/portraits/portrait_modifiers/01_custom_hair.txt
  gfx/portraits/portrait_modifiers/01_hairstyles.txt
  gfx/portraits/portrait_modifiers/wc_facial_markings.txt
  localization/english/wc_portraits_l_english.yml
Labels: new feature :star:, priority high :exclamation:, 3D graphics :triangular_ruler:, character designing 😶

#835 Dalaran is now part of Alliance
  history/titles/00_k_dalaran.txt
Labels: priority medium :grey_exclamation:, history 👑

#842 Removed Orc Vassal of Kul Tiras
  history/titles/00_k_tol_barad.txt
Labels: lore :books:, priority critical :exclamation:, history 👑

#828 [Issue #807] Ner'zhul keeps Orc trait
  history/characters/10000_orc.txt
  history/characters/110000_scourge.txt
  history/characters/260000_northern.txt
  history/characters/330000_highborne.txt
  history/characters/38000_arathorian.txt
  history/characters/59000_dalaranian.txt
  history/characters/60000_63000_lordaeronian.txt
Labels: bug fix :hammer:, priority critical :exclamation:

#784 Cultist Clothes
  common/culture/cultures/undead.txt
  common/genes/05_genes_special_accessories_clothes.txt
  common/genes/06_genes_special_accessories_headgear.txt
  common/scripted_effects/wc_being_effects.txt
  common/scripted_triggers/wc_clothing_triggers.txt
  gfx/models/portraits/attachments/female_clothes/secular/scourge/nobility_01/female_clothes_secular_scourge_nobility_01.asset
  gfx/models/portraits/attachments/female_clothes/secular/scourge/nobility_02/female_clothes_secular_scourge_nobility_02.asset
  gfx/models/portraits/attachments/female_clothes/secular/scourge/nobility_03/female_clothes_secular_scourge_nobility_03.asset
  gfx/models/portraits/attachments/female_clothes/secular/scourge/stealth_01/female_clothes_situational_scourge_stealth_hood_01.asset
  gfx/models/portraits/attachments/female_clothes/secular/scourge/war_nobility_01/female_clothing_secular_scourge_war_nobility_01.asset
  gfx/models/portraits/attachments/female_clothes/secular/western/stealth_01/female_clothes_situational_western_stealth_hood_01.mesh
  gfx/models/portraits/attachments/female_headgears/secular/scourge/common_01/female_headgear_secular_scourge_common_01.asset
  gfx/models/portraits/attachments/female_headgears/secular/scourge/skull_hood_01/female_headgears_secular_scourge_skull_hood_01.asset
  gfx/models/portraits/attachments/female_headgears/secular/scourge/skull_hood_01/female_headgears_secular_scourge_skull_hood_01.mesh
  gfx/models/portraits/attachments/male_clothes/secular/scourge/nobility_01/male_clothes_secular_scourge_nobility_01.asset
  gfx/models/portraits/attachments/male_clothes/secular/scourge/nobility_02/male_clothes_secular_scourge_nobility_02.asset
  gfx/models/portraits/attachments/male_clothes/secular/scourge/nobility_03/male_clothes_secular_scourge_nobility_03.asset
  gfx/models/portraits/attachments/male_clothes/secular/scourge/stealth_01/male_clothes_situational_scourge_stealth_hood_01.asset
  gfx/models/portraits/attachments/male_clothes/secular/scourge/war_nobility_01/male_clothing_secular_scourge_war_nobility_01.asset
  gfx/models/portraits/attachments/male_headgears/secular/scourge/common_02/male_headgear_secular_scourge_common_02.asset
  gfx/models/portraits/attachments/male_headgears/secular/scourge/skull_hood_01/male_headgears_secular_scourge_skull_hood_01.asset
  gfx/models/portraits/attachments/male_headgears/secular/scourge/skull_hood_01/male_headgears_secular_scourge_skull_hood_01.mesh
  gfx/models/portraits/attachments/male_headgears/secular/scourge/skull_hood_01/undead_necromancer_main_diffuse.dds
  gfx/models/portraits/attachments/male_headgears/secular/scourge/skull_hood_01/undead_necromancer_main_normal.dds
  gfx/models/portraits/attachments/male_headgears/secular/scourge/skull_hood_01/undead_necromancer_main_orm.dds
  gfx/portraits/accessories/wc_clothes.txt
  gfx/portraits/accessories/wc_headgear.txt
  gfx/portraits/accessory_variations/textures/color_palette_scourge_common.dds
  gfx/portraits/accessory_variations/western.txt
  gfx/portraits/portrait_modifiers/01_clothes.txt
  gfx/portraits/portrait_modifiers/01_custom_clothes.txt
  gfx/portraits/portrait_modifiers/01_custom_headgear.txt
  gfx/portraits/portrait_modifiers/01_headgear.txt
  history/characters/42000_high_elf.txt
  history/characters/60000_63000_lordaeronian.txt
  localization/english/wc_portraits_l_english.yml
Labels: priority critical :exclamation:, balance :balance_scale:, 3D graphics :triangular_ruler:, character designing 😶, religious :pray:

#844 Scourge Counties
  history/provinces/00_k_dragonblight.txt
  history/provinces/00_k_icecrown.txt
  history/provinces/00_k_wintergarde.txt
Labels: bug fix :hammer:, priority critical :exclamation:, history 👑

#838 Light Aerial Counter; small rebalancing
  common/men_at_arms_types/wc_cultural_maa_types.txt
Labels: lore :books:, priority high :exclamation:, balance :balance_scale:, cultural :mortar_board:

#837 Shenism holy sites
  common/religion/holy_sites/wc_holy_sites.txt
  common/religion/religions/titanic_group.txt
  localization/english/religion/wc_holy_sites_l_english.yml
Labels: lore :books:, priority critical :exclamation:, balance :balance_scale:, religious :pray:

#836 Highlight traits with GetTrait
  localization/english/opinions/wc_general_opinions_l_english.yml
  localization/english/religion/wc_core_tenets_l_english.yml
  localization/english/religion/wc_magic_doctrines_l_english.yml
  localization/english/wc_character_interactions_l_english.yml
  localization/english/wc_game_concepts_l_english.yml
  localization/english/wc_general_l_english.yml
  localization/english/wc_government_l_english.yml
  localization/english/wc_racial_game_concepts_l_english.yml
  localization/english/wc_traits_l_english.yml
  localization/french/religion/wc_core_tenets_l_french.yml
  localization/french/wc_game_concepts_l_french.yml
  localization/french/wc_government_l_french.yml
  localization/german/opinions/wc_general_opinions_l_german.yml
  localization/german/religion/wc_core_tenets_l_german.yml
  localization/german/religion/wc_magic_doctrines_l_german.yml
  localization/german/wc_character_interactions_l_german.yml
  localization/german/wc_game_concepts_l_german.yml
  localization/german/wc_general_l_german.yml
  localization/german/wc_government_l_german.yml
  localization/german/wc_racial_game_concepts_l_german.yml
  localization/replace/english/wc_game_concepts_l_english.yml
Labels: localisation :page_facing_up:

#846 12th Bug Crusade
  common/bookmark_portraits/arthas_menethil_character.txt
  common/casus_belli_types/00_invasion_war.txt
  common/casus_belli_types/wc_event_wars.txt
  common/dna_data/wc_elf_dna.txt
  common/dna_data/wc_human_dna.txt
  common/dna_data/wc_nightelf_dna.txt
  common/scripted_effects/wc_war_effects.txt
  common/scripted_triggers/wc_clothing_triggers.txt
  common/scripted_triggers/wc_war_triggers.txt
  gfx/portraits/portrait_modifiers/01_clothes.txt
  gfx/portraits/portrait_modifiers/01_headgear.txt
  history/characters/59000_dalaranian.txt
Labels: bug fix :hammer:, priority critical :exclamation:

#826 Important lore characters
  history/characters/10000_orc.txt
  history/characters/140000_satyr.txt
  history/characters/16000_gnome.txt
  history/characters/17000_28000_bronzebeard.txt
  history/characters/1_azerothian.txt
  history/characters/200000_farraki.txt
  history/characters/210000_tauren.txt
  history/characters/22000_wildhammer.txt
  history/characters/270000_tolvir.txt
  history/characters/29000_gnoll.txt
  history/characters/330000_highborne.txt
  history/characters/340000_night_elf.txt
  history/characters/381000_vulpera.txt
  history/characters/390000_sethrak.txt
  history/characters/400000_titan.txt
  history/characters/410000_dryad.txt
  history/characters/42000_high_elf.txt
  history/characters/460000_drust.txt
  history/characters/48000_tirassian.txt
  history/characters/500000_pandaren.txt
  history/characters/52000_ogre.txt
  history/characters/530000_saurok.txt
  history/characters/53000_hillsbrad.txt
  history/characters/540000_mantid.txt
  history/characters/57000_amani.txt
  history/characters/59000_dalaranian.txt
  history/characters/60000_63000_lordaeronian.txt
  history/characters/62000_dragon.txt
  history/characters/64000_goblin.txt
  history/characters/66000_zandalari.txt
  history/characters/68000_darkspear.txt
  history/characters/76000_nerubian.txt
  history/characters/80000_drakkari.txt
Labels: lore :books:, priority medium :grey_exclamation:, balance :balance_scale:, history 👑

#765 Reworked elemental doctrines
  common/religion/doctrines/00_core_tenets.txt
  common/religion/doctrines/wc_doctrines_magic.txt
  common/religion/religions/air_group.txt
  common/religion/religions/ape_group.txt
  common/religion/religions/arcane_group.txt
  common/religion/religions/avian_group.txt
  common/religion/religions/daradorism.txt
  common/religion/religions/deathbringer.txt
  common/religion/religions/doombringer.txt
  common/religion/religions/druidism_group.txt
  common/religion/religions/earth_group.txt
  common/religion/religions/fel_group.txt
  common/religion/religions/fire_group.txt
  common/religion/religions/grond_group.txt
  common/religion/religions/light_group.txt
  common/religion/religions/lizard_group.txt
  common/religion/religions/loa_group.txt
  common/religion/religions/naarism.txt
  common/religion/religions/necromancy_group.txt
  common/religion/religions/nerub_group.txt
  common/religion/religions/pandaren_religion_group.txt
  common/religion/religions/secular_group.txt
  common/religion/religions/shamanism_group.txt
  common/religion/religions/shathgral_group.txt
  common/religion/religions/titanic_group.txt
  common/religion/religions/void_group.txt
  common/religion/religions/water_group.txt
  common/script_values/02_religion_values.txt
  common/script_values/wc_magic_doctrines_values.txt
  common/scripted_triggers/wc_religious_triggers.txt
  common/trigger_localization/wc_religion_triggers.txt
  gfx/interface/icons/faith_doctrine_groups/doctrine_elemental_decay_magic.dds
  gfx/interface/icons/faith_doctrine_groups/doctrine_elemental_spirit_magic.dds
  localization/english/religion/wc_core_tenets_l_english.yml
  localization/english/religion/wc_magic_doctrines_l_english.yml
  localization/french/religion/wc_core_tenets_l_french.yml
  localization/german/religion/wc_core_tenets_l_german.yml
  localization/german/religion/wc_magic_doctrines_l_german.yml
  localization/replace/english/gui/wc_faith_view_l_english.yml
  localization/replace/english/wc_replacements_l_english.yml
  localization/replace/german/gui/wc_faith_view_l_german.yml
  localization/replace/german/wc_replacements_l_german.yml
Labels: new feature :star:, priority high :exclamation:, history 👑

#855 Trait highlighting
  localization/english/opinions/wc_general_opinions_l_english.yml
  localization/english/wc_character_interactions_l_english.yml
  localization/english/wc_effects_l_english.yml
  localization/english/wc_game_concepts_l_english.yml
  localization/english/wc_general_l_english.yml
  localization/english/wc_government_l_english.yml
  localization/english/wc_racial_game_concepts_l_english.yml
  localization/english/wc_traits_l_english.yml
  localization/french/wc_game_concepts_l_french.yml
  localization/french/wc_government_l_french.yml
  localization/german/opinions/wc_general_opinions_l_german.yml
  localization/german/wc_character_interactions_l_german.yml
  localization/german/wc_game_concepts_l_german.yml
  localization/german/wc_general_l_german.yml
  localization/german/wc_government_l_german.yml
  localization/german/wc_racial_game_concepts_l_german.yml
  localization/replace/english/wc_game_concepts_l_english.yml
Labels: localisation :page_facing_up:, priority low :grey_exclamation:

#862 Dwarven Clothing Tweaks
  common/culture/cultures/demonic.txt
  common/culture/cultures/dwarf.txt
  common/culture/cultures/elf.txt
  common/culture/cultures/ogre.txt
  common/culture/cultures/troll.txt
  common/scripted_triggers/wc_clothing_triggers.txt
  common/scripted_triggers/wc_portrait_triggers.txt
  gfx/portraits/portrait_modifiers/01_cloaks.txt
  gfx/portraits/portrait_modifiers/01_headgear.txt
Labels: priority high :exclamation:, character designing 😶
