Repository Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2, pull requests merged in 2023-11, with the labels that each got.

#1237 Shatterstar english revisions
  localization/english/religion/wc_gods_and_titles_l_english.yml
  localization/english/wc_activity_arthas_l_english.yml
Labels: localisation :page_facing_up:

#1235 Last 2 Central Kalimdor Events
  common/artifacts/visuals/wc_historical.txt
  common/culture/innovations/wc_cultural_maa_innovations.txt
  common/decisions/wc_cen_kal_decisions.txt
  common/event_backgrounds/wc_event_backgrounds.txt
  common/men_at_arms_types/wc_cultural_maa_types.txt
  common/modifiers/wc_event_modifiers.txt
  common/modifiers/wc_historical_artifact_modifiers.txt
  common/nicknames/wc_nicknames.txt
  common/on_action/wc_central_kal_events_on_actions.txt
  common/on_action/yearly_on_actions.txt
  common/scripted_character_templates/wc_event_templates.txt
  common/traits/wc_general_traits.txt
  events/wc_events/wc_central_kalimdor_events.txt
  gfx/interface/icons/artifact/wc_tauren_totem.dds
  gfx/interface/icons/modifiers/wc_depot.dds
  gfx/interface/icons/modifiers/wc_quilboar_bloodshards.dds
  gfx/interface/icons/modifiers/wc_tauren_kodo_neg.dds
  gfx/interface/icons/modifiers/wc_tauren_kodo_piety.dds
  gfx/interface/icons/modifiers/wc_wild_kodo_companion.dds
  gfx/interface/icons/regimenttypes/dragon_turtle.dds
  gfx/interface/icons/regimenttypes/fang_druids.dds
  gfx/interface/icons/traits/wc_druid_of_the_fang.dds
  gfx/interface/illustrations/decisions/begin_totem_creation.dds
  gfx/interface/illustrations/decisions/create_totem.dds
  gfx/interface/illustrations/decisions/wc_wailing_caverns.dds
  gfx/interface/illustrations/event_scenes/red_rocks.dds
  gfx/interface/illustrations/event_scenes/tauren_cave.dds
  gfx/interface/illustrations/event_scenes/tauren_tent.dds
  gfx/interface/illustrations/event_scenes/tauren_tent_2.dds
  gfx/interface/illustrations/event_scenes/wc_spirit_world_plains.dds
  gfx/interface/illustrations/event_scenes/wc_underground_cavern.dds
  gfx/interface/illustrations/men_at_arms_big/dragon_turtle.dds
  gfx/interface/illustrations/men_at_arms_big/fang_druids.dds
  gfx/interface/illustrations/men_at_arms_small/dragon_turtle.dds
  gfx/interface/illustrations/men_at_arms_small/fang_druids.dds
  gfx/portraits/environments/wc_portrait_environments.txt
  localization/english/event_localization/wc_central_kalimdor_events_l_english.yml
  localization/english/modifiers/wc_modifiers_l_english.yml
  localization/english/wc_decisions_l_english.yml
  localization/english/wc_nicknames_l_english.yml
  localization/english/wc_regiment_l_english.yml
  localization/english/wc_traits_l_english.yml
Labels: lore :books:, localisation :page_facing_up:, history 👑

#1259 Satyr CoA Update
  common/coat_of_arms/template_lists/colored_emblem_lists.txt
  common/culture/cultures/wc_xavic.txt
  gfx/coat_of_arms/colored_emblems/69_coa_designer_emblems.txt
  gfx/coat_of_arms/colored_emblems/ce_satyr_1.dds
  gfx/coat_of_arms/colored_emblems/ce_satyr_10.dds
  gfx/coat_of_arms/colored_emblems/ce_satyr_2.dds
  gfx/coat_of_arms/colored_emblems/ce_satyr_3.dds
  gfx/coat_of_arms/colored_emblems/ce_satyr_4.dds
  gfx/coat_of_arms/colored_emblems/ce_satyr_5.dds
  gfx/coat_of_arms/colored_emblems/ce_satyr_6.dds
  gfx/coat_of_arms/colored_emblems/ce_satyr_7.dds
  gfx/coat_of_arms/colored_emblems/ce_satyr_8.dds
  gfx/coat_of_arms/colored_emblems/ce_satyr_9.dds
Labels: 2D graphics :paintbrush:
