Repository Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2, pull requests merged in 2023-06, with the labels that each got.

#1065 Pygmy Ethnicity
  common/culture/cultures/wc_pygmy.txt
  common/ethnicities/wc_ethnicities_pygmy.txt
  common/genes/03_genes_special_accessories_hairstyles.txt
  common/genes/04_genes_special_accessories_beards.txt
  common/genes/05_genes_special_accessories_clothes.txt
  common/genes/06_genes_special_accessories_headgear.txt
  common/scripted_modifiers/wc_portrait_modifiers.txt
  common/scripted_triggers/wc_clothing_triggers.txt
  gfx/models/portraits/attachments/male_beards/steppe/male_beard_steppe_01_wc/male_beard_steppe_01_wc.asset
  gfx/portraits/portrait_animations/animations.txt
  gfx/portraits/portrait_modifiers/01_beards.txt
  gfx/portraits/portrait_modifiers/01_clothes.txt
  gfx/portraits/portrait_modifiers/01_custom_beards.txt
  gfx/portraits/portrait_modifiers/01_custom_hair.txt
  gfx/portraits/portrait_modifiers/01_hairstyles.txt
  gfx/portraits/portrait_modifiers/01_headgear.txt
  gfx/portraits/portrait_modifiers/01_legwear.txt
Labels: new feature :star:, priority medium :grey_exclamation:, character designing 😶

#998 First Patreon Characters Crusade
  .gitignore
  .vs/slnx.sqlite
  common/dna_data/wc_patron_dna.txt
  common/dynasties/125000_patron_dynasties.txt
  common/scripted_triggers/wc_his_character_triggers.txt
  gfx/portraits/portrait_modifiers/50_beards_scripted_characters.txt
  gfx/portraits/portrait_modifiers/50_hairstyles_scripted_characters.txt
  history/characters/310000_patron_characters.txt
  history/provinces/00_k_ironforge.txt
  history/provinces/00_k_thalanaar.txt
  history/titles/00_k_crystalsong_forest.txt
  history/titles/00_k_gilneas.txt
  history/titles/00_k_ironforge.txt
  history/titles/00_k_kaldoran.txt
  history/titles/00_k_lordaeron.txt
  history/titles/00_k_quelthalas.txt
  history/titles/00_k_raynewood.txt
  history/titles/00_k_stratholme.txt
  history/titles/00_k_thalanaar.txt
  history/titles/00_k_tranquillien.txt
  localization/english/dynasties/wc_dynasty_names_l_english.yml
  localization/french/dynasties/wc_dynasty_names_l_french.yml
  localization/german/dynasties/wc_dynasty_names_l_german.yml
  localization/spanish/dynasties/wc_dynasty_names_l_spanish.yml
Labels: lore :books:, priority high :exclamation:, 2D graphics :paintbrush:, 3D graphics :triangular_ruler:, character designing 😶, artifact⚔️

#1136 Invisible Giant Fix
  common/scripted_triggers/wc_portrait_triggers.txt
  gfx/portraits/portrait_modifiers/01_clothes.txt
  gfx/portraits/portrait_modifiers/wc_race_portrait_modifiers.txt
Labels: bug fix :hammer:, priority medium :grey_exclamation:, good first testing 🧪
