Repository Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2, pull requests merged in 2023-04, with the labels that each got.

#1103 Inaccessible Atal'hakkar fix + Stonecairn Adjustment
  map_data/adjacencies.csv
Labels: priority critical :exclamation:, bug :bug:, cartography 🌐

#1098 Dwarves Not Fearing Dwarf Clothes, Beards and Hairs
  common/culture/cultures/wc_dwarven.txt
  gfx/portraits/portrait_modifiers/01_clothes.txt
Labels: bug fix :hammer:, priority high :exclamation:, character designing 😶

#1110 Inaccessible Dream Bough + Ingmill Mere Fix
  map_data/adjacencies.csv
  map_data/heightmap.heightmap
  map_data/heightmap.png
  map_data/indirection_heightmap.png
  map_data/packed_heightmap.png
Labels: priority critical :exclamation:, bug :bug:, good first testing 🧪, cartography 🌐

#1102 Static Lich Models + Kel'Thuzad Model
  common/genes/wc_genes_static_models.txt
  common/scripted_triggers/wc_portrait_triggers.txt
  gfx/models/portraits/static_races/lich/kelthuzad.dds
  gfx/models/portraits/static_races/lich/kelthuzad.mesh
  gfx/models/portraits/static_races/lich/kelthuzadchains.dds
  gfx/models/portraits/static_races/lich/lich.asset
  gfx/models/portraits/static_races/lich/lich1.mesh
  gfx/models/portraits/static_races/lich/lich2.mesh
  gfx/models/portraits/static_races/lich/lich3.mesh
  gfx/models/portraits/static_races/lich/lich4.mesh
  gfx/models/portraits/static_races/lich/lichbronze.dds
  gfx/models/portraits/static_races/lich/lichgold.dds
  gfx/models/portraits/static_races/lich/lichpewter.dds
  gfx/models/portraits/static_races/lich/lichsilver.dds
  gfx/portraits/accessories/wc_static_races.txt
  gfx/portraits/portrait_modifiers/50_beards_scripted_characters.txt
  gfx/portraits/portrait_modifiers/50_hairstyles_scripted_characters.txt
  gfx/portraits/portrait_modifiers/wc_race_portrait_modifiers.txt
Labels: 3D graphics :triangular_ruler:, good first testing 🧪

#1109 Baby Tauren Model
  common/genes/wc_genes_static_models.txt
  gfx/models/portraits/static_races/tauren/babytauren.asset
  gfx/models/portraits/static_races/tauren/babytauren.mesh
  gfx/models/portraits/static_races/tauren/babytauren1.dds
  gfx/portraits/accessories/wc_static_races.txt
  gfx/portraits/portrait_modifiers/wc_race_portrait_modifiers.txt
Labels: suggestion :question:, 3D graphics :triangular_ruler:, good first testing 🧪

#1107 Old Anduin Beard
  gfx/portraits/portrait_modifiers/50_beards_scripted_characters.txt
Labels: suggestion :question:, lore :books:, priority low :grey_exclamation:, character designing 😶, good first testing 🧪

#1101 Green Eyes for Blood Elves
  common/culture/cultures/wc_highborne.txt
  common/genes/05_genes_special_accessories_clothes.txt
  common/scripted_triggers/wc_clothing_triggers.txt
  gfx/models/portraits/attachments/female_clothes/secular/blood_elven/nobility_01/female_clothing_secular_blood_elven_nobility_01.asset
  gfx/models/portraits/attachments/female_clothes/secular/blood_elven/nobility_02/female_clothes_secular_blood_elven_nobility_02.asset
  gfx/models/portraits/attachments/male_clothes/secular/blood_elven/nobility_01/male_clothing_secular_blood_elven_nobility_01.asset
  gfx/models/portraits/attachments/male_clothes/secular/blood_elven/nobility_02/male_clothes_secular_blood_elven_nobility_02.asset
  gfx/portraits/accessories/wc_clothes.txt
  gfx/portraits/accessory_variations/textures/color_palette_blood_elven_common_01.dds
  gfx/portraits/accessory_variations/textures/color_palette_blood_elven_high_01.dds
  gfx/portraits/accessory_variations/textures/color_palette_blood_elven_low_01.dds
  gfx/portraits/accessory_variations/wc_blood_elven.txt
  gfx/portraits/portrait_modifiers/01_clothes.txt
  gfx/portraits/portrait_modifiers/01_custom_clothes.txt
  gfx/portraits/portrait_modifiers/wc_race_portrait_modifiers.txt
Labels: lore :books:, character designing 😶, good first testing 🧪, cultural :mortar_board:

#1064 Female Model for Male Harpies
  common/genes/wc_genes_static_models.txt
Labels: bug fix :hammer:

#1127 Orc Eyeliner
  common/dna_data/wc_orc_dna.txt
  common/ethnicities/wc_ethnicities_orcish.txt
  common/genes/wc_gene_facial_markings.txt
  gfx/models/portraits/decals/orc_makeup/decal_eyeliner_01.dds
  gfx/portraits/portrait_modifiers/wc_facial_markings.txt
  localization/english/religion/wc_core_tenets_l_english.yml
  localization/english/wc_portraits_l_english.yml
Labels: suggestion :question:, 2D graphics :paintbrush:, character designing 😶

#1118 Aging penalty fix
  common/defines/00_defines.txt
  common/modifiers/wc_age_modifiers.txt
  common/modifiers/wc_age_penalty_modifiers.txt
  common/on_action/wc_aging_penalties.txt
  common/scripted_effects/wc_age_effects.txt
  common/scripted_triggers/wc_age_triggers.txt
  common/traits/wc_infusion_traits.txt
  common/trigger_localization/wc_character_triggers.txt
  events/wc_events/wc_race_events.txt
  gfx/interface/icons/modifiers/aging_penalty.dds
  localization/english/modifiers/wc_age_penalty_modifiers_l_english.yml
  localization/english/triggers/wc_character_triggers_l_english.yml
  localization/english/wc_traits_l_english.yml
Labels: bug fix :hammer:, suggestion :question:, vanilla modification :icecream:, priority high :exclamation:, good first testing 🧪, racial:fish:

#1025 Refining history
  _mapFiller/provinceDef.xls
  common/culture/cultures/wc_vrykulic.txt
  common/culture/name_lists/wc_vrykulic.txt
  common/dynasties/124000_frostborn.txt
  common/dynasties/150000_titan.txt
  common/dynasties/60000_pirate.txt
  common/dynasties/70000_vrykul.txt
  common/flavorization/wc_title_holders.txt
  common/landed_titles/01_landed_titles.txt
  common/landed_titles/wc_color_titles.txt
  common/landed_titles/wc_titular_titles.txt
  common/nicknames/wc_nicknames.txt
  common/scripted_rules/00_rules.txt
  common/scripted_triggers/00_building_requirement_triggers.txt
  common/scripted_triggers/wc_war_triggers.txt
  history/characters/100000_vrykul.txt
  history/characters/17000_28000_bronzebeard.txt
  history/characters/290000_frozen_giant.txt
  history/characters/300000_frostborn.txt
  history/characters/340000_night_elf.txt
  history/characters/390000_sethrak.txt
  history/characters/400000_titan.txt
  history/characters/440000_storm_giant.txt
  history/characters/500000_pandaren.txt
  history/characters/60000_63000_lordaeronian.txt
  history/characters/62000_dragon.txt
  history/characters/90000_pirate.txt
  history/characters/northsea.txt
  history/provinces/00_k_dun_niffelem.txt
  history/provinces/00_k_kul_tiras.txt
  history/provinces/00_k_makers_terrace.txt
  history/provinces/00_k_starfall.txt
  history/provinces/00_k_storm_peaks.txt
  history/provinces/00_k_ulduar.txt
  history/provinces/00_k_winterspring.txt
  history/titles/000_wc_other_titles.txt
  history/titles/00_k_dun_niffelem.txt
  history/titles/00_k_makers_terrace.txt
  history/titles/00_k_starfall.txt
  history/titles/00_k_storm_peaks.txt
  history/titles/00_k_ulduar.txt
  history/titles/00_k_winterspring.txt
  history/titles/00_wc_development_history.txt
  localization/english/00_mapfiller_titles_l_english.yml
  localization/english/culture/wc_culture_titles_l_english.yml
  localization/english/dynasties/wc_dynasty_names_l_english.yml
  localization/english/names/wc_character_names_l_english.yml
  localization/english/wc_custom_titles_l_english.yml
  localization/english/wc_nicknames_l_english.yml
  localization/english/wc_other_titles_l_english.yml
  map_data/definition.csv
  map_data/geographical_regions/wc_geographical_region.txt
  map_data/island_region.txt
  tools/mapeditor/nudger_progress.txt
Labels: lore :books:, priority medium :grey_exclamation:, history 👑

#1104 DNA 6 (Tyrande, Black Dragonflight, Nozdormu, Whitemane Family)
  common/dna_data/wc_dragon_dna.txt
  common/dna_data/wc_human_dna.txt
  common/dna_data/wc_nightelf_dna.txt
  common/dna_data/wc_orc_dna.txt
  common/genes/wc_gene_facial_markings.txt
  common/scripted_triggers/wc_his_character_triggers.txt
  gfx/models/portraits/decals/scripted_makeup/decal_nightelf_marking_noeyelids.dds
  gfx/models/portraits/decals/scripted_makeup/decal_whitemane.dds
  gfx/portraits/portrait_modifiers/50_beards_scripted_characters.txt
  gfx/portraits/portrait_modifiers/50_hairstyles_scripted_characters.txt
  gfx/portraits/portrait_modifiers/50_headgear_scripted_characters.txt
  gfx/portraits/portrait_modifiers/wc_facial_markings.txt
  gfx/portraits/portrait_modifiers/wc_scripted_appearances.txt
  gfx/portraits/trait_portrait_modifiers/wc_undead_modifier.txt
  history/characters/340000_night_elf.txt
  history/characters/60000_63000_lordaeronian.txt
  history/characters/62000_dragon.txt
  localization/english/wc_portraits_l_english.yml
Labels: priority medium :grey_exclamation:, character designing 😶, good first testing 🧪

#373 Faithless loa faith
  common/religion/doctrines/wc_doctrines_religions.txt
  common/religion/religions/loa_group.txt
  common/religion/religions/wc_apostasism.txt
  gfx/interface/icons/faith/wcmw_faithless.dds
  history/characters/390000_sethrak.txt
  history/provinces/00_k_voldun.txt
  localization/english/religion/wc_core_tenets_l_english.yml
  localization/english/religion/wc_gods_and_titles_l_english.yml
  localization/english/religion/wc_religion_l_english.yml
Labels: new feature :star:, lore :books:, 2D graphics :paintbrush:

#1053 5th LC (English only)
  localization/english/artifacts/wc_artifacts_l_english.yml
  localization/english/culture/traditions/wc_cultural_heritages_l_english.yml
  localization/english/culture/traditions/wc_cultural_languages_l_english.yml
  localization/english/culture/wc_cultural_innovations_l_english.yml
  localization/english/culture/wc_cultural_maa_innovations_l_english.yml
  localization/english/dlc/ep1/wc_dlc_ep1_flavor_events_l_english.yml
  localization/english/dlc/ep1/wc_dlc_ep1_fund_inspiration_events_l_english.yml
  localization/english/dynasties/wc_dynasty_names_l_english.yml
  localization/english/event_localization/schemes/wc_plague/wc_plague_ongoing_events_l_english.yml
  localization/english/event_localization/schemes/wc_plague/wc_plague_outcome_events_l_english.yml
  localization/english/event_localization/wc_arthas_expedition_events_l_english.yml
  localization/english/event_localization/wc_being_events_l_english.yml
  localization/english/modifiers/wc_modifiers_l_english.yml
  localization/english/religion/wc_core_tenets_l_english.yml
  localization/english/religion/wc_gods_and_titles_l_english.yml
  localization/english/religion/wc_magic_doctrines_l_english.yml
  localization/english/religion/wc_religion_l_english.yml
  localization/english/triggers/wc_character_triggers_l_english.yml
  localization/english/wc_battles_l_english.yml
  localization/english/wc_buildings_l_english.yml
  localization/english/wc_regiment_l_english.yml
  localization/replace/english/culture/traditions/wc_cultural_traditions_l_english.yml
  localization/replace/english/culture/wc_cultural_innovations_l_english.yml
  localization/replace/english/culture/wc_cultural_maa_innovations_l_english.yml
  localization/replace/english/wc_buildings_l_english.yml
  localization/replace/english/wc_dlc_fp1_l_english.yml
  localization/replace/english/wc_game_concepts_l_english.yml
  localization/replace/english/wc_game_rules_l_english.yml
  localization/replace/english/wc_learning_theology_events_l_english.yml
  localization/replace/english/wc_messages_l_english.yml
  localization/replace/english/wc_regiment_l_english.yml
  localization/replace/english/wc_regional_innovations_l_english.yml
  localization/replace/english/wc_replacements_l_english.yml
Labels: localisation :page_facing_up:

#1134 Fixed placement of special buildings
  history/provinces/00_k_ahnqiraj.txt
  history/provinces/00_k_dustwallow.txt
  history/provinces/00_k_eldrethalas.txt
Labels: bug fix :hammer:, priority low :grey_exclamation:, good first testing 🧪, cartography 🌐

#1128 Orcish clans update
  common/bookmarks/bookmarks/00_bookmarks.txt
  common/coat_of_arms/coat_of_arms/00_wc_landed_titles.txt
  common/coat_of_arms/coat_of_arms/wc_dynasties.txt
  common/coat_of_arms/coat_of_arms/wc_orcish_clans.txt
  common/culture/cultures/wc_orcish.txt
  common/landed_titles/wc_orcish_clans.txt
  common/landed_titles/wc_titular_titles.txt
  common/scripted_effects/01_dlc_fp1_scripted_effects.txt
  common/scripted_effects/wc_fp1_effects.txt
  common/scripted_effects/wc_horde_invasion_effects.txt
  gfx/coat_of_arms/colored_emblems/ce_old_horde_symbol.dds
  history/characters/10000_orc.txt
  history/titles/000_wc_other_titles.txt
  history/titles/00_k_alterac.txt
  history/titles/00_k_barrens.txt
  history/titles/00_k_black_morass.txt
  history/titles/00_k_blackrock.txt
  history/titles/00_k_dead_morass.txt
  history/titles/00_k_desolace.txt
  history/titles/00_k_ratchet.txt
  history/titles/00_k_raynewood.txt
  history/titles/00_k_silithus.txt
  history/titles/00_k_stormwind.txt
  history/titles/00_k_vermillion.txt
  history/titles/00_k_wetlands.txt
  history/titles/00_k_wildhammer.txt
  localization/english/wc_other_titles_l_english.yml
  localization/french/wc_other_titles_l_french.yml
  localization/german/wc_other_titles_l_german.yml
  localization/spanish/wc_other_titles_l_spanish.yml
Labels: good first testing 🧪

#1142 Ulduar Hill Forts Fix
  history/provinces/00_k_ulduar.txt
Labels: bug fix :hammer:, priority low :grey_exclamation:

#975 Gorehowl
  common/artifacts/templates/wc_historical_artifacts_templates.txt
  common/artifacts/visuals/wc_historical.txt
  common/modifiers/wc_historical_artifact_modifiers.txt
  common/scripted_effects/wc_historical_artifacts_creation_effect.txt
  events/artifacts/historical_artifacts_events.txt
  gfx/interface/icons/artifact/wc_gorehowl.dds
  localization/english/artifacts/wc_artifacts_l_english.yml
  localization/german/artifacts/wc_artifacts_l_german.yml
Labels: priority low :grey_exclamation:, artifact⚔️
