Repository Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2, pull requests merged in 2023-01, with the labels that each got.

#865 Special Buildings
  common/buildings/wc_duchy_capital_buildings.txt
  common/buildings/wc_special_buildings.txt
  gfx/interface/icons/building_types/icon_structure_dark_portal.dds
  history/provinces/00_k_booty_bay.txt
  history/provinces/00_k_dalaran.txt
  history/provinces/00_k_dead_morass.txt
  history/provinces/00_k_lordaeron.txt
  history/provinces/00_k_quelthalas.txt
  history/provinces/00_k_stromgarde.txt
  localization/english/wc_buildings_l_english.yml
Labels: new feature :star:, lore :books:, priority high :exclamation:, history 👑

#1000 1.5.0 Gui Fixes
  gui/frontend_main.gui
  gui/interaction_declare_war.gui
  gui/multiplayer_lobby.gui
  gui/shared/portraits.gui
  gui/window_activity.gui
  gui/window_character.gui
Labels: vanilla modification :icecream:, priority critical :exclamation:, interface 👁‍🗨

#964 Shoulderpads
  common/genes/07_genes_special_accessories_misc.txt
  gfx/models/portraits/attachments/female_cloaks/secular/human/shoulderpad/wc_female_cloaks_secular_human_shoulderpad.asset
  gfx/models/portraits/attachments/female_cloaks/secular/human/shoulderpad/wc_female_cloaks_secular_human_shoulderpad.mesh
  gfx/models/portraits/attachments/female_cloaks/secular/orc/shoulderpad/wc_female_cloaks_secular_orc_shoulderpad.asset
  gfx/models/portraits/attachments/female_cloaks/secular/orc/shoulderpad/wc_female_cloaks_secular_orc_shoulderpad.mesh
  gfx/models/portraits/attachments/male_cloaks/secular/human/shoulderpad/wc_male_cloaks_secular_human_shoulderpad.asset
  gfx/models/portraits/attachments/male_cloaks/secular/human/shoulderpad/wc_male_cloaks_secular_human_shoulderpad.mesh
  gfx/models/portraits/attachments/male_cloaks/secular/human/shoulderpad/wc_male_cloaks_secular_human_shoulderpad_diffuse.dds
  gfx/models/portraits/attachments/male_cloaks/secular/human/shoulderpad/wc_male_cloaks_secular_human_shoulderpad_mask.dds
  gfx/models/portraits/attachments/male_cloaks/secular/human/shoulderpad/wc_male_cloaks_secular_human_shoulderpad_normal.dds
  gfx/models/portraits/attachments/male_cloaks/secular/human/shoulderpad/wc_male_cloaks_secular_human_shoulderpad_properties.dds
  gfx/models/portraits/attachments/male_cloaks/secular/orc/shoulderpad/wc_male_cloaks_secular_orc_shoulderpad.asset
  gfx/models/portraits/attachments/male_cloaks/secular/orc/shoulderpad/wc_male_cloaks_secular_orc_shoulderpad.mesh
  gfx/models/portraits/attachments/male_cloaks/secular/orc/shoulderpad/wc_male_cloaks_secular_orc_shoulderpad_diffuse.dds
  gfx/models/portraits/attachments/male_cloaks/secular/orc/shoulderpad/wc_male_cloaks_secular_orc_shoulderpad_mask.dds
  gfx/models/portraits/attachments/male_cloaks/secular/orc/shoulderpad/wc_male_cloaks_secular_orc_shoulderpad_normal.dds
  gfx/models/portraits/attachments/male_cloaks/secular/orc/shoulderpad/wc_male_cloaks_secular_orc_shoulderpad_properties.dds
  gfx/portraits/accessories/wc_cloaks.txt
  gfx/portraits/accessory_variations/shoulderpads.txt
  gfx/portraits/accessory_variations/textures/color_palette_wc3_teams.dds
  gfx/portraits/portrait_modifiers/01_clothes.txt
  gfx/portraits/portrait_modifiers/01_custom_cloaks.txt
  localization/english/wc_portraits_l_english.yml
Labels: 3D graphics :triangular_ruler:, cultural :mortar_board:
