Repository Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2, pull requests merged in 2023-03, with the labels that each got.

#954 Special buildings 2
  common/buildings/wc_special_buildings.txt
  gfx/interface/icons/building_types/icon_structure_icecrown_citadel.dds
  gfx/interface/icons/building_types/icon_structure_karazhan.dds
  gfx/interface/icons/building_types/icon_structure_lordaeron_palace.dds
  gfx/interface/icons/building_types/icon_structure_nexus.dds
  gfx/interface/icons/building_types/icon_structure_sunwell.dds
  gfx/interface/icons/building_types/icon_structure_temple_of_atal_hakkar.dds
  gfx/interface/icons/building_types/icon_structure_ulduar.dds
  gfx/interface/icons/building_types/icon_structure_utgarde.dds
  gfx/interface/icons/building_types/icon_structure_violet_citadel.dds
  history/provinces/00_k_coldarra.txt
  history/provinces/00_k_gan_shi.txt
  history/provinces/00_k_icecrown.txt
  history/provinces/00_k_ironforge.txt
  history/provinces/00_k_ulduar.txt
  history/provinces/00_k_utgarde.txt
  localization/english/wc_buildings_l_english.yml
Labels: priority medium :grey_exclamation:

#965 1.5.0 maa tasks
  common/customizable_localization/00_maa_custom_loc.txt
  common/customizable_localization/01_ep1_custom_loc.txt
  common/modifiers/01_dlc_ep1_modifiers.txt
  common/scripted_triggers/00_cultural_triggers.txt
  common/scripted_triggers/wc_cultural_triggers.txt
  events/dlc/ep1/ep1_flavor_events.txt
  localization/english/dlc/ep1/wc_dlc_ep1_flavor_events_l_english.yml
Labels: priority critical :exclamation:

#895 1.5.0 warcraft basic buildings
  common/buildings/00_duchy_capital_buildings.txt
  common/buildings/00_terrain_specific_buildings.txt
  common/buildings/wc_common_buildings.txt
  common/buildings/wc_duchy_capital_buildings.txt
  common/buildings/wc_special_buildings.txt
  common/culture/innovations/wc_cultural_maa_innovations.txt
  common/culture/innovations/wc_regional_innovations.txt
  common/culture/traditions/00_regional_traditions.txt
  common/holdings/00_holdings.txt
  common/modifier_definition_formats/wc_unit_definitions.txt
  common/script_values/wc_men_at_arms_values.txt
  common/scripted_triggers/wc_building_requirement_triggers.txt
  common/scripted_triggers/wc_maa_related_triggers.txt
  common/scripted_triggers/wc_maa_triggers.txt
  gfx/interface/icons/building_types/icon_building_aerodrome.dds
  gfx/interface/icons/building_types/icon_building_aviary_complex.dds
  gfx/interface/icons/building_types/icon_building_caster_college.dds
  gfx/interface/icons/building_types/icon_building_citadel.dds
  gfx/interface/icons/building_types/icon_structure_dark_portal.dds
  gfx/interface/icons/building_types/icon_structure_icecrown_citadel.dds
  gfx/interface/icons/building_types/icon_structure_karazhan.dds
  gfx/interface/icons/building_types/icon_structure_lordaeron_palace.dds
  gfx/interface/icons/building_types/icon_structure_nexus.dds
  gfx/interface/icons/building_types/icon_structure_sunwell.dds
  gfx/interface/icons/building_types/icon_structure_temple_of_atal_hakkar.dds
  gfx/interface/icons/building_types/icon_structure_ulduar.dds
  gfx/interface/icons/building_types/icon_structure_utgarde.dds
  gfx/interface/icons/building_types/icon_structure_violet_citadel.dds
  history/cultures/frostwolf.txt
  history/cultures/mantid.txt
  history/provinces/00_k_booty_bay.txt
  history/provinces/00_k_coldarra.txt
  history/provinces/00_k_dalaran.txt
  history/provinces/00_k_dead_morass.txt
  history/provinces/00_k_gan_shi.txt
  history/provinces/00_k_icecrown.txt
  history/provinces/00_k_ironforge.txt
  history/provinces/00_k_lordaeron.txt
  history/provinces/00_k_quelthalas.txt
  history/provinces/00_k_stromgarde.txt
  history/provinces/00_k_ulduar.txt
  history/provinces/00_k_utgarde.txt
  localization/english/wc_buildings_l_english.yml
  localization/french/culture/wc_cultural_innovations_l_french.yml
Labels: priority critical :exclamation:

#1020 Quick bug fix
  Warcraft-Guardians-of-Azeroth-2.mod
  common/culture/cultures/wc_hyenaic.txt
  common/culture/traditions/00_societal_traditions.txt
  common/culture/traditions/wc_societal_traditions.txt
  common/customizable_localization/01_ep1_custom_loc.txt
  thumbnail.png
Labels: priority critical :exclamation:

#1030 CoA bookmark fix for dynasties+titles
  common/coat_of_arms/coat_of_arms/00_wc_landed_titles.txt
  common/coat_of_arms/coat_of_arms/wc_dynasties.txt
  gfx/coat_of_arms/colored_emblems/ce_aran.dds
  gfx/coat_of_arms/colored_emblems/ce_coilfang.dds
  gfx/coat_of_arms/colored_emblems/ce_drathir.dds
  gfx/coat_of_arms/colored_emblems/ce_illidari.dds
  gfx/coat_of_arms/colored_emblems/ce_karazhan.dds
  gfx/coat_of_arms/colored_emblems/ce_solliden.dds
  gfx/coat_of_arms/colored_emblems/ce_stormrage.dds
  gfx/coat_of_arms/colored_emblems/ce_stormreaver.dds
  gfx/coat_of_arms/colored_emblems/ce_sunfury.dds
  gfx/coat_of_arms/colored_emblems/ce_thalassian_pass.dds
  gfx/coat_of_arms/colored_emblems/ce_valonforth.dds
  gfx/coat_of_arms/colored_emblems/ce_vashj.dds
  gfx/coat_of_arms/colored_emblems/ce_wintergarde.dds
Labels: 2D graphics :paintbrush:

#990 Bookmark screen
  common/bookmark_portraits/anasterian_character.txt
  common/bookmark_portraits/arthas_menethil_character.txt
  common/bookmark_portraits/blackhand_character.txt
  common/bookmark_portraits/daelin_character.txt
  common/bookmark_portraits/darkhan_character.txt
  common/bookmark_portraits/durotan_character.txt
  common/bookmark_portraits/guldan_character.txt
  common/bookmark_portraits/illidan_character.txt
  common/bookmark_portraits/kaelthas_character.txt
  common/bookmark_portraits/llane_wrynn_character.txt
  common/bookmark_portraits/malakk_character.txt
  common/bookmark_portraits/medivh_character.txt
  common/bookmark_portraits/nerzhul_character.txt
  common/bookmark_portraits/othmar_garithos_character.txt
  common/bookmark_portraits/valonforth_character.txt
  common/bookmark_portraits/vashj_character.txt
  common/bookmarks/00_bookmarks.txt
  common/coat_of_arms/coat_of_arms/00_wc_landed_titles.txt
  common/coat_of_arms/coat_of_arms/wc_dynasties.txt
  gfx/coat_of_arms/colored_emblems/ce_aran.dds
  gfx/coat_of_arms/colored_emblems/ce_coilfang.dds
  gfx/coat_of_arms/colored_emblems/ce_drathir.dds
  gfx/coat_of_arms/colored_emblems/ce_illidari.dds
  gfx/coat_of_arms/colored_emblems/ce_karazhan.dds
  gfx/coat_of_arms/colored_emblems/ce_solliden.dds
  gfx/coat_of_arms/colored_emblems/ce_stormrage.dds
  gfx/coat_of_arms/colored_emblems/ce_stormreaver.dds
  gfx/coat_of_arms/colored_emblems/ce_sunfury.dds
  gfx/coat_of_arms/colored_emblems/ce_thalassian_pass.dds
  gfx/coat_of_arms/colored_emblems/ce_valonforth.dds
  gfx/coat_of_arms/colored_emblems/ce_vashj.dds
  gfx/coat_of_arms/colored_emblems/ce_wintergarde.dds
  gfx/interface/bookmarks/bm_the_frozen_throne.dds
  gfx/interface/bookmarks/bm_the_invasion_from_draenor.dds
  gfx/interface/bookmarks/bm_the_reign_of_chaos.dds
  localization/english/bookmark/bookmark_508_l_english.yml
  localization/english/bookmark/bookmark_583_l_english.yml
  localization/english/bookmark/bookmark_603_l_english.yml
  localization/english/bookmark/bookmark_605_l_english.yml
  localization/french/bookmark/bookmark_508_l_french.yml
  localization/french/bookmark/bookmark_583_l_french.yml
  localization/french/bookmark/bookmark_603_l_french.yml
  localization/french/bookmark/bookmark_605_l_french.yml
Labels: localisation :page_facing_up:

#881 Frostmourne
  common/artifacts/templates/wc_historical_artifacts_templates.txt
  common/artifacts/visuals/wc_historical.txt
  common/character_interactions/00_artifact_interactions.txt
  common/combat_phase_events/00_commander_phase_events.txt
  common/combat_phase_events/00_knight_phase_events.txt
  common/decisions/test_decision.txt
  common/effect_localization/01_ep1_effects.txt
  common/game_concepts/wc_artifact_game_concepts.txt
  common/genes/07_genes_special_accessories_misc.txt
  common/modifiers/wc_historical_artifact_modifiers.txt
  common/scripted_animations/00_scripted_animations.txt
  common/scripted_effects/00_ep1_artifact_effects.txt
  common/scripted_effects/00_ep1_inspiration_effects.txt
  common/scripted_effects/wc_arthas_expedition_effects.txt
  common/scripted_effects/wc_artifact_effects.txt
  common/scripted_effects/wc_being_effects.txt
  common/scripted_effects/wc_combat_effects.txt
  common/scripted_effects/wc_historical_artifacts_creation_effect.txt
  common/scripted_effects/wc_single_combat_effects.txt
  common/scripted_effects/wc_vanilla_effects.txt
  common/scripted_modifiers/wc_artifact_modifiers.txt
  common/scripted_modifiers/wc_scourge_invasion_modifiers.txt
  common/scripted_triggers/wc_artifact_triggers.txt
  common/scripted_triggers/wc_combat_triggers.txt
  common/story_cycles/wc_story_cycle_scourge_invasion.txt
  common/traits/wc_special_traits.txt
  events/activities/arthas_expedition_activity/wc_arthas_expedition_events.txt
  events/artifacts/artifact_events.txt
  events/artifacts/historical_artifacts_events.txt
  events/jester_stress_relief_events.txt
  events/scheme_events/murder_scheme/murder_saves/murder_save_events.txt
  events/scheme_events/wc_plague_scheme/wc_plague_outcome_events.txt
  events/single_combat_events.txt
  events/war_events/combat_events.txt
  gfx/FX/court_scene.shader
  gfx/FX/jomini/portrait.shader
  gfx/interface/icons/artifact/wc_frostmourne.dds
  gfx/models/artifacts/weapons/wc_frostmourne/undead_arthasevil_sword_diffuse.dds
  gfx/models/artifacts/weapons/wc_frostmourne/undead_arthasevil_sword_normal.dds
  gfx/models/artifacts/weapons/wc_frostmourne/undead_arthasevil_sword_orm.dds
  gfx/models/artifacts/weapons/wc_frostmourne/wc_frostmourne.asset
  gfx/models/artifacts/weapons/wc_frostmourne/wc_frostmourne_portrait.mesh
  gfx/portraits/accessories/wc_props.txt
  gfx/portraits/portrait_animations/animations.txt
  gfx/portraits/portrait_modifiers/01_animation_props.txt
  localization/english/artifacts/wc_artifacts_l_english.yml
  localization/english/event_localization/wc_arthas_expedition_events_l_english.yml
  localization/english/modifiers/wc_modifiers_l_english.yml
  localization/english/wc_character_interactions_l_english.yml
  localization/english/wc_effects_l_english.yml
  localization/english/wc_game_concepts_l_english.yml
  localization/english/wc_messages_l_english.yml
  localization/english/wc_traits_l_english.yml
Labels: artifact⚔️

#1035 French Localisation fixes for 1.5
  .vs/slnx.sqlite
  localization/french/bookmark/bookmark_508_l_french.yml
  localization/french/bookmark/bookmark_583_l_french.yml
  localization/french/bookmark/bookmark_603_l_french.yml
  localization/french/bookmark/bookmark_605_l_french.yml
  localization/french/dynasties/wc_dynasty_names_l_french.yml
  localization/french/wc_character_interactions_l_french.yml
  localization/french/wc_custom_titles_l_french.yml
  localization/french/wc_other_titles_l_french.yml
Labels: localisation :page_facing_up:, WIP :construction:

#1041 1st German localisation crusade and some last minute fixes
  localization/english/bookmark/bookmark_583_l_english.yml
  localization/english/bookmark/bookmark_603_l_english.yml
  localization/english/bookmark/bookmark_605_l_english.yml
  localization/english/dynasties/wc_dynasty_names_l_english.yml
  localization/german/artifacts/wc_court_artifacts_l_german.yml
  localization/german/bookmark/bookmark_508_l_german.yml
  localization/german/bookmark/bookmark_583_l_german.yml
  localization/german/bookmark/bookmark_603_l_german.yml
  localization/german/bookmark/bookmark_605_l_german.yml
  localization/german/culture/wc_culture_titles_l_german.yml
  localization/german/dynasties/wc_dynasty_names_l_german.yml
  localization/german/event_localization/wc_arthas_expedition_events_l_german.yml
  localization/german/wc_traits_l_german.yml
  localization/replace/german/wc_fixes_l_german.yml
  localization/replace/german/wc_replacements_l_german.yml
Labels: localisation :page_facing_up:, localisation - german :page_facing_up:, priority high :exclamation:

#1061 Thumbnail Changed
  thumbnail.png
Labels: 2D graphics :paintbrush:

#994 Special buildings 3
  common/buildings/wc_special_buildings.txt
  gfx/interface/icons/building_types/icon_structure_atul_aman.dds
  gfx/interface/icons/building_types/icon_structure_caverns_of_time.dds
  gfx/interface/icons/building_types/icon_structure_corpse_of_agamaggan.dds
  gfx/interface/icons/building_types/icon_structure_dire_maul_arena.dds
  gfx/interface/icons/building_types/icon_structure_necropolis.dds
  gfx/interface/icons/building_types/icon_structure_onyxias_lair.dds
  gfx/interface/icons/building_types/icon_structure_stormwind_harbor.dds
  gfx/interface/icons/building_types/icon_structure_sulfuron_spire.dds
  gfx/interface/icons/building_types/icon_structure_temple_of_ahn_qiraj.dds
  gfx/interface/icons/building_types/icon_structure_temple_of_arkkoran.dds
  gfx/interface/icons/building_types/icon_structure_zuldazar.dds
  history/provinces/00_k_ahnqiraj.txt
  history/provinces/00_k_azshara.txt
  history/provinces/00_k_dustwallow.txt
  history/provinces/00_k_eldrethalas.txt
  history/provinces/00_k_kaldoran.txt
  history/provinces/00_k_kezan.txt
  history/provinces/00_k_razorfen.txt
  history/provinces/00_k_stormwind.txt
  history/provinces/00_k_tanaris.txt
  history/provinces/00_k_voldun.txt
  history/provinces/00_k_zandalar.txt
  localization/english/wc_buildings_l_english.yml
Labels: priority medium :grey_exclamation:

#1071 Portrait Error Fixes
  common/bookmark_portraits/anasterian_character.txt
  common/bookmark_portraits/arthas_menethil_character.txt
  common/bookmark_portraits/blackhand_character.txt
  common/bookmark_portraits/daelin_character.txt
  common/bookmark_portraits/darkhan_character.txt
  common/bookmark_portraits/durotan_character.txt
  common/bookmark_portraits/guldan_character.txt
  common/bookmark_portraits/illidan_character.txt
  common/bookmark_portraits/kaelthas_character.txt
  common/bookmark_portraits/llane_wrynn_character.txt
  common/bookmark_portraits/malakk_character.txt
  common/bookmark_portraits/medivh_character.txt
  common/bookmark_portraits/nerzhul_character.txt
  common/bookmark_portraits/valonforth_character.txt
  common/dna_data/wc_dragon_dna.txt
  common/dna_data/wc_dwarf_dna.txt
  common/dna_data/wc_easter_egg_dna.txt
  common/dna_data/wc_elf_dna.txt
  common/dna_data/wc_gnome_dna.txt
  common/dna_data/wc_goblin_dna.txt
  common/dna_data/wc_human_dna.txt
  common/dna_data/wc_nightelf_dna.txt
  common/dna_data/wc_orc_dna.txt
  common/dna_data/wc_troll_dna.txt
  common/genes/wc_genes_static_hairstyles.txt
Labels: bug fix :hammer:, priority high :exclamation:

#941 1.5.x Portrait Updates (Humans, Elves, Dragons)
  common/dna_data/wc_dragon_dna.txt
  common/dna_data/wc_elf_dna.txt
  common/dna_data/wc_human_dna.txt
  common/dna_data/wc_nightelf_dna.txt
Labels: bug fix :hammer:, priority medium :grey_exclamation:, character designing 😶

#1082 Demon Becoming Undead Fix
  common/scripted_triggers/wc_being_triggers.txt
Labels: bug fix :hammer:, priority high :exclamation:
