Repository Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2, pull requests merged in 2024-01, with the labels that each got.

#973 Hammer of twilight
  common/artifacts/templates/wc_historical_artifacts_templates.txt
  common/artifacts/visuals/wc_historical.txt
  common/modifiers/wc_historical_artifact_modifiers.txt
  common/scripted_effects/wc_historical_artifacts_creation_effect.txt
  events/artifacts/historical_artifacts_events.txt
  events/error_suppression_events.txt
  gfx/interface/icons/artifact/wc_hammer_of_twilight.dds
  localization/english/artifacts/wc_artifacts_l_english.yml
  localization/english/opinions/wc_opinions_l_english.yml
  localization/german/artifacts/wc_artifacts_l_german.yml
Labels: priority low :grey_exclamation:, artifact⚔️

#1290 hoely sites
  common/buildings/wc_special_buildings.txt
  common/customizable_localization/00_building_custom_localization.txt
  common/religion/holy_sites/wc_holy_sites.txt
  common/religion/religions/doombringer.txt
  common/religion/religions/druidism_group.txt
  common/religion/religions/fel_group.txt
  common/religion/religions/necromancy_group.txt
  common/religion/religions/shamanism_group.txt
  common/religion/religions/titanic_group.txt
  common/religion/religions/wc_draconism.txt
  gfx/interface/icons/building_types/icon_building_blackrook_hold.dds
  gfx/interface/icons/building_types/icon_structure_vault_of_the_wardens.dds
  history/provinces/00_k_broken_shores.txt
  history/provinces/00_k_highmountain.txt
  history/provinces/00_k_valsharah.txt
  localization/english/religion/wc_holy_sites_l_english.yml
  localization/english/wc_buildings_l_english.yml
Labels: priority low :grey_exclamation:, religious :pray:

#1323 Racial stats
  common/traits/wc_race_traits.txt
Labels: racial:fish:

#1117 Dragon Ethnicities
  common/culture/cultures/wc_draconic.txt
  common/ethnicities/wc_ethnicities_dragon.txt
  common/genes/wc_genes_special_eyes.txt
  gfx/models/portraits/female_head/female_eyes.asset
  gfx/models/portraits/male_head/male_eyes.asset
  gfx/models/portraits/male_head/male_eyes_magic_dragon.dds
  gfx/portraits/accessories/bodyparts.txt
  gfx/portraits/portrait_modifiers/wc_custom_eyes.txt
  gui/window_ruler_designer.gui
  localization/english/wc_portraits_l_english.yml
Labels: suggestion :question:, WIP :construction:, character designing 😶, good first testing 🧪

#1339 Rebalanced the various cultural and regional MaAs
  common/men_at_arms_types/wc_cultural_maa_types.txt
Labels: balance :balance_scale:

#955 Tortollan Creature Trait
  common/court_positions/types/wc_court_positions.txt
  common/culture/cultures/wc_chelonian.txt
  common/culture/name_lists/wc_chelonian.txt
  common/culture/name_lists/wc_zulite.txt
  common/culture/pillars/wc_heritage.txt
  common/dynasties/178000_tortollan.txt
  common/dynasties/8000_troll.txt
  common/genes/wc_genes_morph.txt
  common/genes/wc_genes_static_models.txt
  common/nicknames/wc_nicknames.txt
  common/script_values/wc_age_values.txt
  common/scripted_effects/wc_race_effects.txt
  common/scripted_triggers/wc_cultural_triggers.txt
  common/scripted_triggers/wc_portrait_triggers.txt
  common/scripted_triggers/wc_race_triggers.txt
  common/traits/wc_race_traits.txt
  gfx/interface/icons/traits/creature_tortollan.dds
  gfx/models/portraits/static_races/tortollan/babytortollan.mesh
  gfx/models/portraits/static_races/tortollan/babytortollan_blue.dds
  gfx/models/portraits/static_races/tortollan/babytortollan_brown.dds
  gfx/models/portraits/static_races/tortollan/babytortollan_green.dds
  gfx/models/portraits/static_races/tortollan/babytortollan_grey.dds
  gfx/models/portraits/static_races/tortollan/tortollan.asset
  gfx/models/portraits/static_races/tortollan/tortollan0.mesh
  gfx/models/portraits/static_races/tortollan/tortollan1.mesh
  gfx/models/portraits/static_races/tortollan/tortollan2.mesh
  gfx/models/portraits/static_races/tortollan/tortollan3.mesh
  gfx/models/portraits/static_races/tortollan/tortollan4.mesh
  gfx/models/portraits/static_races/tortollan/tortollan_blue.dds
  gfx/models/portraits/static_races/tortollan/tortollan_brown.dds
  gfx/models/portraits/static_races/tortollan/tortollan_green.dds
  gfx/models/portraits/static_races/tortollan/tortollan_grey.dds
  gfx/portraits/accessories/wc_static_races.txt
  gfx/portraits/portrait_modifiers/wc_race_portrait_modifiers.txt
  history/characters/66000_zandalari.txt
  history/characters/tortollan.txt
  history/provinces/00_k_ungoro.txt
  history/provinces/00_k_voldun.txt
  history/provinces/00_k_zandalar.txt
  history/titles/00_k_ungoro.txt
  history/titles/00_k_voldun.txt
  history/titles/00_k_zandalar.txt
  localization/english/dynasties/wc_dynasty_names_l_english.yml
  localization/english/names/wc_character_names_l_english.yml
  localization/english/wc_court_positions_l_english.yml
  localization/english/wc_nicknames_l_english.yml
  localization/english/wc_traits_l_english.yml
Labels: new feature :star:, lore :books:, priority medium :grey_exclamation:, history 👑

#1352 Man'ari Creature Trait
  common/culture/cultures/wc_demonic.txt
  common/ethnicities/wc_ethnicities_draenei.txt
  common/game_concepts/wc_racial_game_concepts.txt
  common/genes/wc_genes_morph.txt
  common/script_values/wc_age_values.txt
  common/scripted_effects/wc_race_effects.txt
  common/scripted_triggers/wc_portrait_triggers.txt
  common/scripted_triggers/wc_race_triggers.txt
  common/traits/wc_race_traits.txt
  gfx/interface/icons/traits/creature_manari.dds
  gui/window_ruler_designer.gui
  history/characters/draenei.txt
  localization/english/culture/wc_culture_gfx_l_english.yml
  localization/english/wc_racial_game_concepts_l_english.yml
  localization/english/wc_traits_l_english.yml
Labels: racial:fish:
