Repository Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2, pull requests merged in 2024-10, with the labels that each got.

#1467 Thorium Brotherhood
  common/decisions/wc_thorium_decisions.txt
  common/modifiers/wc_event_modifiers.txt
  common/on_action/wc_thorium_on_actions.txt
  common/scripted_character_templates/wc_thorium_templates.txt
  common/scripted_effects/wc_thorium_effects.txt
  common/scripted_triggers/wc_thorium_triggers.txt
  events/decisions_events/wc_thorium_events.txt
  gfx/interface/illustrations/decisions/wc_dark_iron_dwarf.dds
  localization/english/event_localization/wc_thorium_brotherhood_l_english.yml
  localization/english/modifiers/wc_modifiers_l_english.yml
  localization/english/wc_decisions_l_english.yml
Labels: lore :books:, priority low :grey_exclamation:, WIP :construction:, artifact⚔️

#1457 Tales of the Past Machinima Easter Egg Characters
  common/dna_data/wc_easter_egg_dna.txt
  common/dynasties/wc_easter_egg_dynasties.txt
  common/scripted_triggers/wc_his_character_triggers.txt
  gfx/portraits/portrait_modifiers/50_beards_scripted_characters.txt
  gfx/portraits/portrait_modifiers/50_hairstyles_scripted_characters.txt
  gfx/portraits/portrait_modifiers/wc_facial_markings.txt
  history/characters/wc_easteregg_characters.txt
  history/provinces/00_k_azshara.txt
  history/titles/00_k_azshara.txt
  localization/english/dynasties/wc_dynasty_names_l_english.yml
  localization/english/names/wc_character_names_l_english.yml
  localization/replace/english/wc_title_replacements_l_english.yml
Labels: priority low :grey_exclamation:, character designing 😶

#1461 Theramorean Culture Innovations
  history/cultures/theramore.txt
Labels: cultural :mortar_board:

#1475 Old history stuff
  common/landed_titles/01_landed_titles.txt
  common/landed_titles/wc_titular_titles.txt
  history/characters/1_azerothian.txt
  history/characters/320000_centaur.txt
  history/titles/000_wc_other_titles.txt
  history/titles/00_k_black_morass.txt
  history/titles/00_k_dead_morass.txt
  history/titles/00_k_stormwind.txt
  localization/english/wc_other_titles_l_english.yml
  localization/english/wc_titles_cultural_names_l_english.yml
  localization/replace/english/wc_title_replacements_l_english.yml
Labels: history 👑

#1506 Fix exotic locations scoping
  common/scripted_effects/wc_ce1_effects.txt
Labels: bug fix :hammer:

#1508 Genocide Errors
  common/on_action/title_on_actions.txt
  common/on_action/wc_genocide_on_actions.txt
  common/script_values/wc_genocide_values.txt
  common/scripted_effects/wc_genocide_effects.txt
  common/scripted_triggers/wc_genocide_triggers.txt
  common/scripted_triggers/wc_war_triggers.txt
  events/councillor_task_events/wc_genocide_task_events.txt
  localization/english/event_localization/wc_genocide_task_events_l_english.yml
  localization/english/wc_council_tasks_l_english.yml
Labels: bug fix :hammer:

#1513 Shadow Corruption Modifier Fix
  common/modifiers/wc_genocide_modifiers.txt
Labels: bug fix :hammer:, priority critical :exclamation:

#1527 Holy Light icons by Kal
  common/artifacts/visuals/wc_historical.txt
  common/character_interactions/wc_religious_interactions.txt
  common/religion/religions/wc_tyrism.txt
  common/scripted_effects/wc_historical_artifacts_creation_effect.txt
  gfx/interface/icons/artifact/wcka_artifact_libram_of_compassion.dds
  gfx/interface/icons/artifact/wcka_artifact_libram_of_holiness.dds
  gfx/interface/icons/artifact/wcka_artifact_libram_of_justice.dds
  gfx/interface/icons/artifact/wcka_artifact_libram_of_protection.dds
  gfx/interface/icons/artifact/wcka_artifact_libram_of_retribution.dds
  gfx/interface/icons/artifact/wcka_artifact_lordaeron_urn.dds
  gfx/interface/icons/artifact/wcka_artifact_phylactery.dds
  gfx/interface/icons/artifact/wcka_libram_base.dds
  gfx/interface/icons/artifact/wcka_libram_base_2.dds
  gfx/interface/icons/artifact/wcka_libram_base_3.dds
  gfx/interface/icons/character_interactions/wcka_surrender_to_the_inquisition.dds
  gfx/interface/icons/faith/wcka_argent_dawn.dds
Labels: 2D graphics :paintbrush:

#1481 Mongrel Races Rework
  common/culture/name_lists/wc_agamagganic.txt
  common/culture/name_lists/wc_amphibian.txt
  common/culture/name_lists/wc_avianic.txt
  common/culture/name_lists/wc_murine.txt
  common/culture/name_lists/wc_xavic.txt
  common/dynasties/1000_forsaken.txt
  common/dynasties/110000_satyr.txt
  common/dynasties/112000_quilboar.txt
  common/dynasties/119000_harpy.txt
  common/dynasties/12000_gnoll.txt
  common/dynasties/126000_centaur.txt
  common/dynasties/18000_kobold.txt
  common/dynasties/6000_murloc.txt
  common/dynasty_houses/wc_dynasty_houses.txt
  common/landed_titles/01_landed_titles.txt
  common/landed_titles/wc_orcish_clans.txt
  common/landed_titles/wc_titular_titles.txt
  common/nicknames/wc_nicknames.txt
  history/characters/140000_satyr.txt
  history/characters/160000_quilboar.txt
  history/characters/250000_harpy.txt
  history/characters/29000_gnoll.txt
  history/characters/320000_centaur.txt
  history/characters/34000_murloc.txt
  history/characters/50000_kobold.txt
  history/characters/77000_wolvar.txt
  history/provinces/00_k_darkshore.txt
  history/provinces/00_k_desolace.txt
  history/provinces/00_k_hyjal.txt
  history/provinces/00_k_kalidar.txt
  history/provinces/00_k_razorfen.txt
  history/provinces/00_k_starfall.txt
  history/provinces/00_k_stonetalon.txt
  history/provinces/00_k_stromgarde.txt
  history/provinces/00_k_wetlands.txt
  history/titles/000_wc_other_titles.txt
  history/titles/00_k_azuremyst.txt
  history/titles/00_k_darkshore.txt
  history/titles/00_k_desolace.txt
  history/titles/00_k_durotan.txt
  history/titles/00_k_hyjal.txt
  history/titles/00_k_kalidar.txt
  history/titles/00_k_lordaeron.txt
  history/titles/00_k_mulgore.txt
  history/titles/00_k_ratchet.txt
  history/titles/00_k_razorfen.txt
  history/titles/00_k_starfall.txt
  history/titles/00_k_stonetalon.txt
  history/titles/00_k_stormwind.txt
  history/titles/00_k_stromgarde.txt
  history/titles/00_k_thalanaar.txt
  history/titles/00_k_tranquillien.txt
  history/titles/00_k_wetlands.txt
  localization/english/dynasties/wc_dynasty_names_l_english.yml
  localization/english/names/wc_character_names_l_english.yml
  localization/english/wc_nicknames_l_english.yml
  localization/english/wc_other_titles_l_english.yml
  localization/english/wc_titles_cultural_names_l_english.yml
  localization/replace/english/wc_title_replacements_l_english.yml
Labels: lore :books:, history 👑
